### ISSUE TITLE
Implement `final class`

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#1023]
### Problem

Add ability to define a class that cannot be subclassed.
We have asks for this ~every week.
### Proposed solution
A check in Sorbet-static & in runtime.

**Comment by DarkDimius** [comment]
cc @benbuckman

**Comment by azdavis** [comment]
In addition to this, it would be nice to have final methods (methods that may not be overridden by subclasses) as a separate but related concept. This would allow for the class itself not to be final, but some chosen methods to be final.

Note that if the class is final, all the methods on that class are automatically final because you can't override the methods because you can't subclass the class.

**Comment by DarkDimius** [comment]
> Note that if the class is final, all the methods on that class are automatically final because you can't override the methods because you can't subclass the class.


note that we want to _enforce_ that, by redefining `define_method` and friends.

**Comment by azdavis** [comment]
Closed in #1394, #1364, #1353, #1341, #1316, #1181, #1178, and others.
