### ISSUE TITLE
You're killing my inbox every time you release

### ISSUE THREAD

**Issue by Trevoke** [sorbet/sorbet#1198]
I'm sure you have a good internal reason for doing this, but I use a tool that tells me when a new version of a package I use is released, sooooo here's you:

![image](https://user-images.githubusercontent.com/67913/60631242-8ca4a380-9dcc-11e9-8cfc-d3ed5041f0a7.png)

**Comment by jez** [comment]
Thanks for the feedback!

This is annoying for me too, because I watch the repo so that I can see all issues that are opened (like this one 🙂) and all pull requests. The way I fixed this was to set up a Gmail filter that auto-archived these emails.

I'm not actually sure if anyone uses the GitHub releases instead of the releases on RubyGems. It's possible we could stop publishing there (the context is that we published to GitHub when sorbet was a private repo, which predated publishing to rubygems.org).

**Comment by jez** [comment]
If you wanted to be notified of a supposed "0.5.x" release, I think you could set up a Gmail filter that auto-archives `0.4.x` instead of everything.

**Comment by jez** [comment]
(closing; thanks again for the feedback!)

**Comment by Trevoke** [comment]
I'm sorry, why exactly are you closing this issue? I don't think this is resolved.

Using a gmail filter is not a solution to this problem, nor is it a bandaid. What you're suggesting is that I use a tool to hide a tool that is supposed to make information more transparent to me.

I'd like to be notified of *releases* on the premise that "a release" is something that is released to me, the end user. Saying "I want to be notified of releases, but maybe not all releases, because maybe not all releases are useful to me" makes me think that *possibly* there's a mismatch in the contract that I'm using with you.

If the release is not supposed to be useful to me, the end user, then why is it a release at all?

**Comment by Trevoke** [comment]
If I understand correctly, what you're suggesting here is that *everyone* who wants to track new releases to stay up to date should create a special workflow, different from the way they track updates to all other gems? And you think this is.... Not going to be a problem for adoption of the tool?
