### ISSUE TITLE
Typing an attr_writer raises an exception at runtime

### ISSUE THREAD

**Issue by elliottt** [sorbet/sorbet#1239]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Arequire%20'sorbet-runtime'%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20initialize%0A%20%20%20%20%40foo%20%3D%20T.let(0%2C%20Integer)%0A%20%20end%0A%0A%20%20sig%20%7Bparams(foo%3AInteger).returns(Integer)%7D%0A%20%20attr_writer%20%3Afoo%0A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20dbg%0A%20%20%20%20puts%20%40foo%0A%20%20end%0A%0Aend%0A%0Aa%20%3D%20A.new%0A%0Aa.foo%20%3D%20T.let(10%2C%20Integer)%0A%0Aa.dbg%0A)

```ruby
# typed: strict

require 'sorbet-runtime'

class A
  extend T::Sig

  sig {void}
  def initialize
    @foo = T.let(0, Integer)
  end

  sig {params(foo:Integer).returns(Integer)}
  attr_writer :foo

  sig {void}
  def dbg
    puts @foo
  end

end

a = A.new

a.foo = T.let(10, Integer)

a.dbg

```

#### Observed output
No errors during type-checking, but at runtime:

```
<home>/sorbet/gems/sorbet-runtime/lib/types/private/methods/signature.rb:65:in `initialize': The declaration for `foo=` is missing parameter(s):  (RuntimeError)
        from <home>/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:219:in `new'
        from <home>/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:219:in `build_sig'
        from <home>/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:188:in `run_sig'
        from <home>/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:119:in `block in _on_method_added'
        from <home>/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:282:in `run_sig_block_for_key'
        from <home>/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:272:in `run_sig_block_for_method'
        from <home>/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:143:in `block in _on_method_added'
        from test.rb:24:in `<main>'
```

#### Expected behavior

No runtime error.
- - -

**Comment by JPDuchesne** [comment]
The problem is that sorbet runtime depends on reflection to check for missing / extra parameters in signatures here: https://github.com/sorbet/sorbet/blob/master/gems/sorbet-runtime/lib/types/private/methods/signature.rb#L60, but Ruby doesn't expose the parameter name for `attr_writer`, resulting in a `nil` parameter name.

A workaround for now would be to forgo use of `attr_writer` and do:

```
# typed: strict
class Foo
  extend(T::Sig)

  sig { void }
  def initialize
    @bar = T.let("initial_value", String)
  end

  # Here, Ruby correctly returns [[:req, :value]] instead of just [[:req]] when doing method(:bar=).parameters
  sig { params(value: String).returns(String) }
  def bar=(value)
    @bar = value
  end
end
```

**Comment by paracycle** [comment]
I have an idea of how we can fix this and I would like to run it by the team to get feedback before I dive in to an implementation.

As @JPDuchesne points out, the issue stems from the fact that for an `attr_writer` (or `attr_accessor` for that matter) generated `foo=` writer method, the single parameter is "nameless". If we can special case this, then we can make this problem go away.

The special casing should:
1. cover this case and not be likely to match other cases
2. be fast enough to check so that it does not add overhead.

My thinking is that while we are extracting `name`s from `parameters`, if 
(a) `parameters.size == 1` **and** 
(b) `parameters.first.name.nil?` **and** 
(c) `method_name[-1] == "="`, 
then we can assume that this is a writer method and make `param_names = [method_name[0...-1]]`. 

The check should fail really fast for most unrelated methods, since most will not have 1 params and of ones that do majority will have names for the params and if it happens that they are C-defined functions their method name will most probably not end with a `=`.

Thoughts?

**Comment by jez** [comment]
@paracycle That approach works for me. I looked into this a while back and came to essentially the same solution, thought it was gross, and decided to not do it. But I can't think of any better way to do it, so if you're down to implement it, that'd be great. Please add tests in `gems/sorbet-runtime/test/`
