### ISSUE TITLE
Dynamic constant assignment allowed in blocks

### ISSUE THREAD

**Issue by elliottt** [sorbet/sorbet#1334]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20%5B%5D.each%20do%0A%20%20%20%20X%20%3D%2010%0A%20%20end%0Aend)

```ruby
# typed: true
class A
  [].each do
    X = 10
  end
end
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

This should raise an error, as the dynamic constant assignment is not valid.

- - -

**Comment by mojanjz** [comment]
After investigating this issue in #4248  and chatting with the Shopify team about it, we came to the conclusion that in some cases dynamic constant assignment within blocks should be allowed. Example use cases would be:
- [`T::Enum`](https://sorbet.org/docs/tenum) blocks
- constant assignment in [`silence_warnings`](https://apidock.com/rails/Kernel/silence_warnings) blocks.
- constant assignment in Rake namespaces
It might make more sense to add this as a cop rather than strictly forbidding it.

**Comment by jez** [comment]
sounds good, thanks for looking! closing for now.
