### ISSUE TITLE
Sorbet doesn't correctly handle windows line endings

### ISSUE THREAD

**Issue by kevin-klein** [sorbet/sorbet#1372]
I have a file called order.rb and order.rbi:

order.rbi:
```ruby
# typed: true

class Order < ApplicationRecord
  extend T::Sig

  sig { returns(T::Array[T::Hash[String, String]]) }
  def changelog(); end

  sig { params(value: T::Array[T::Hash[String, String]]).void }
  def changelog=(value); end
end
```

First line of order.rb:
```ruby
# typed: true
```

When i run type check i get these errors:

```
$ bundle exec srb tc
app/models/order.rbi:6: To use `sig`, this file must declare an explicit `# typed:` sigil (found: none). If you're not sure which one to use, start with `# typed: false` https://srb.help/5038
     6 |  sig { returns(T::Array[T::Hash[String, String]]) }
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

app/models/order.rbi:9: To use `sig`, this file must declare an explicit `# typed:` sigil (found: none). If you're not sure which one to use, start with `# typed: false` https://srb.help/5038
     9 |  sig { params(value: T::Array[T::Hash[String, String]]).void }
```

I am using sorbet-rails and i attempted to do this: https://github.com/chanzuckerberg/sorbet-rails#overriding-generated-signatures

**Comment by jez** [comment]
@kevin-klein I can't reproduce this issue. Can you make a reproducer that reproduces with `bundle exec srb tc --no-config` ? You can pass individual filenames to `srb tc` to minimize the test case.

**Comment by kevin-klein** [comment]
https://github.com/kevin-klein/sorbet-reproduction

There should be a reproduction of the issue.

```
$ bundle exec srb tc --no-config app/models/order.rbi 
app/models/order.rbi:6: To use `sig`, this file must declare an explicit `# typed:` sigil (found: none). If you're not sure which one to use, start with `# typed: false` https://srb.help/5038
     6 |  sig { returns(T::Array[T::Hash[String, String]]) }
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

app/models/order.rbi:9: To use `sig`, this file must declare an explicit `# typed:` sigil (found: none). If you're not sure which one to use, start with `# typed: false` https://srb.help/5038
     9 |  sig { params(value: T::Array[T::Hash[String, String]]).void }
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 2
```

**Comment by jez** [comment]
This is a problem with Windows vs Unix style line endings. It's definitely a bug in Sorbet.

I couldn't reproduce it when I copy / pasted your example into a file, because the act of copy / pasting destroyed the line endings. Thank you for creating the git repo; that was a pretty good reproducer.

For posterity's sake I'm uploading a windows-style line encoded reproducer in this comment.

[order.txt](https://github.com/sorbet/sorbet/files/3428335/order.txt)

(GitHub doesn't support `.rb` file uploads, so rename the file extension and reproduce with

```
sorbet order.rb
```

To whoever takes fixing this, using lldb pointed me to these lines:

https://github.com/sorbet/sorbet/blob/d6211a003e0ee975b396ed908a1009dc47c80e71/core/Files.cc#L70-L72

The current workaround is to change the file to use Unix-style line endings. My preferred tool for this is `dos2unix` (`brew install dos2unix`).

**Comment by kevin-klein** [comment]
That makes sense as my text editor is running on windows and i executed sorbet inside wsl.
