### ISSUE TITLE
Autocorrects punchlist

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#1474]
Here is a set of autocorrects that makes sense to add

- [x] https://github.com/sorbet/sorbet/blob/6689d9086a866f490ee3bba5480c0a494c8d23d3/infer/environment.cc#L1048
- [x] https://github.com/sorbet/sorbet/blob/21b05b4018be869ce282dd4e48e3046e8c8f93e8/core/types/calls.cc#L935
- [ ] https://github.com/sorbet/sorbet/blob/21b05b4018be869ce282dd4e48e3046e8c8f93e8/infer/environment.cc#L1053
- [x] https://github.com/sorbet/sorbet/blob/d922217336adea4098f4f8c84309c77f6ff80fd3/resolver/type_syntax.cc#L302
- [ ] https://github.com/sorbet/sorbet/blob/d922217336adea4098f4f8c84309c77f6ff80fd3/resolver/type_syntax.cc#L329
- [x] https://github.com/sorbet/sorbet/blob/d922217336adea4098f4f8c84309c77f6ff80fd3/resolver/type_syntax.cc#L763
- [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/definition_validator/validator.cc#L62
- [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/definition_validator/validator.cc#L72
 - [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/definition_validator/validator.cc#L81
 - [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/definition_validator/validator.cc#L106
 - [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/definition_validator/validator.cc#L118
 - [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/definition_validator/validator.cc#L126
 - [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/definition_validator/validator.cc#L144
 - [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/definition_validator/validator.cc#L150
- [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/definition_validator/validator.cc#L158
 - [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/definition_validator/validator.cc#L391
 - [x] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/namer/namer.cc#L311
 - [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/namer/namer.cc#L527
- [ ] https://github.com/sorbet/sorbet/blob/88a8efcdfe0f2a0b21437de9e7c33f4e0fe0ade8/namer/namer.cc#L758
- [x] https://github.com/sorbet/sorbet/blob/21b05b4018be869ce282dd4e48e3046e8c8f93e8/resolver/resolver.cc#L1208
- [ ] https://github.com/sorbet/sorbet/blob/21b05b4018be869ce282dd4e48e3046e8c8f93e8/resolver/resolver.cc#L1222
- [ ] https://github.com/sorbet/sorbet/blob/21b05b4018be869ce282dd4e48e3046e8c8f93e8/resolver/resolver.cc#L1216
- [ ] https://github.com/sorbet/sorbet/blob/21b05b4018be869ce282dd4e48e3046e8c8f93e8/resolver/resolver.cc#L1295
- [x] https://github.com/sorbet/sorbet/blob/84ca94bb59b7444a97368ee90aadc20740be43ab/ast/desugar/Desugar.cc#L177
- [ ] https://github.com/sorbet/sorbet/blob/8cf63a86bdf6dd98f0ece3190dc47443b4efa6a2/resolver/GlobalPass.cc#L53

- [ ] #1750 

### Proposed solution
Add them

**Comment by jez** [comment]
Heads up I built the `T.must` one to make a codemod easier, but didn't feel like writing a test for it:

```diff
diff --git a/core/types/calls.cc b/core/types/calls.cc
index 11e78426d..89bc742a1 100644
--- a/core/types/calls.cc
+++ b/core/types/calls.cc
@@ -929,16 +929,19 @@ public:
         if (args.args.empty()) {
             return;
         }
+        auto loc = args.locs.call;
         if (!args.args[0]->type->isFullyDefined()) {
-            if (auto e = ctx.state.beginError(args.locs.call, errors::Infer::BareTypeUsage)) {
+            if (auto e = ctx.state.beginError(loc, errors::Infer::BareTypeUsage)) {
                 e.setHeader("T.must() applied to incomplete type `{}`", args.args[0]->type->show(ctx));
             }
             return;
         }
         auto ret = Types::approximateSubtract(ctx, args.args[0]->type, Types::nilClass());
         if (ret == args.args[0]->type) {
-            if (auto e = ctx.state.beginError(args.locs.call, errors::Infer::InvalidCast)) {
+            if (auto e = ctx.state.beginError(loc, errors::Infer::InvalidCast)) {
                 e.setHeader("T.must(): Expected a `T.nilable` type, got: `{}`", args.args[0]->type->show(ctx));
+                auto locWithoutTmust = Loc{loc.file(), loc.beginPos() + 7, loc.endPos() - 1};
+                e.replaceWith(loc, locWithoutTmust.source(ctx));
             }
         }
         res.returnType = move(ret);
```

if someone wants to write a test for it and commit it, that'd be great.

**Comment by sushain97** [comment]
Another one that I think might be useful is to support this pattern:

```
class Foo
  def self.bar
      @bar ||= ...
   end
end
```

in pay-server, the pattern is used ~2000 times. It would be nice if I could autocorrect to:

```
class Foo
  @bar = T.let(nil, T.nilable(...))  

  def self.bar
      @bar ||= ...
   end
end
```

**Comment by sushain97** [comment]
- [ ] Type argument suggestions for both constants and sigs are always `T.untyped`. Deleting the `T.let` or `sig` entirely gives a better suggestion with the real inferred types (unfortunate UX)

e.g. [sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0AA%20%3D%20T.let(%5B42%5D%2C%20Array)%0A%0Asig%20%7Breturns(Array)%7D%0Adef%20foo%0A%20%20%20%20%5B42%5D%0Aend%0A)

```
# typed: strict

A = T.let([42], Array)

sig {returns(Array)}
def foo
    [42]
end
```

**Comment by azdavis** [comment]
@sushain97 I've been thinking a bit about this, here's my thoughts.
Unfortunately I'm not sure if this is an easy fix.

- We detect and issue an error correcting `Array` -> `T::Array[T.untyped]` in
  [resolver][2] but sig suggestion happens in [infer][3] and T.let suggestions
  happen [in calls.cc][4] as an intrinsic. I'm not really sure at what phase
  calls.cc "happens", but in any case it seems to be quite separated from
  resolver.
- Going off of this, we already have 2 separate places where we infer types and
  suggest them as annotations: sig suggestion and T.let suggestions. I'm not
  sure it'd be a good idea to introduce this place in resolver as a third place
  where we do things like this. Actually, I doubt it's even possible: I think
  we'd need the information infer gives us, which happens later in the pipeline.
  [This comment][1] seems to indicate we might not be able to do this logic in
  resolver.

Given this, a possible idea I had was to somehow delete the existing T.let/sig
that contains the bad generic, so that the later logic that infers a T.let/sig
can run. (This is essentially going off of what you said about deleting the
T.let/sig entirely gives a better suggestion in some cases). However, this has
some problems too.

- The errors say things like "This function doesn't have a sig" or "This
  constant doesn't have a T.let" even though the user wrote one. We'd have to
  somehow communicate that we deleted the sig or T.let so the error is better.
- The bad generic might be arbitrary nested inside the sig/T.let. I don't think
  we want to totally throw away everything the user wrote just to replace the
  bad generics. What if, when we throw away the sig and then infer a new one, we
  improved `Array` to `T::Array[Integer]`, but in the sig that we deleted, there
  was some other method parameter and we weren't able to infer its type, so we
  come back with `T.untyped` or something?

Then, perhaps what we want is something that "merges" a suggested sig/T.let with
what the user wrote. But this seems non-trivial and not very clean. But, such a
'merging' operation might have further applications: for instance, if you have a
sig that has some things typed, but some `T.untyped`, could we generate a
suggestion and see if we were able to remove any of the `T.untyped`? Perhaps
such a 'merging' operation actually has more general applications like this one.

[1]: https://github.com/sorbet/sorbet/blob/4a16e846bdd7b5b0856db066a23a53bed7065913/resolver/resolver.cc#L1240
[2]: https://github.com/sorbet/sorbet/blob/4a16e846bdd7b5b0856db066a23a53bed7065913/resolver/type_syntax.cc#L590
[3]: https://github.com/sorbet/sorbet/blob/4a16e846bdd7b5b0856db066a23a53bed7065913/infer/inference.cc#L218
[4]: https://github.com/sorbet/sorbet/blob/4a16e846bdd7b5b0856db066a23a53bed7065913/core/types/calls.cc#L1626

**Comment by sushain97** [comment]
Here's another that seems to be potentially auto-correctable (but maybe too special case-y/specific):

```
# typed: strict

a = ["foo"] + [nil]
# fixed
a = T.let(["foo"], T::Array[T.nilable(String)]) + [nil]
```

```
editor.rb:3: Expected T::Enumerable[String] but found [NilClass] for argument arg0 https://srb.help/7002
     3 |a = ["foo"] + [nil]
            ^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/array.rbi#L41: Method Array#+ has specified arg0 as T::Enumerable[String]
    41 |        arg0: T::Enumerable[Elem],
                ^^^^
  Got [NilClass] originating from:
    editor.rb:3:
     3 |a = ["foo"] + [nil]
                      ^^^^^
Errors: 1
```

**Comment by sushain97** [comment]
Another one that would be really helpful and potentially simple since we already do it for `interface!`, `abstract!`, etc. is suggesting the addition of `extend T::Sig` when there's something like `sig {void}` that produces an error. e.g. [sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20self.bar%0A%20%20end%0Aend%0A)

**Comment by azdavis** [comment]
Looks like we already have `maybeSuggestExtendTSig` used elsewhere. Maybe we can give that suggestion more often.

**Comment by sushain97** [comment]
- [ ] Something that would be really helpful is having these suggestions surfaced as autocorrects:

```
# typed: true
class Foo
    def bar
    end
end

Foo.new.baz
```

```
editor.rb:7: Method baz does not exist on Foo https://srb.help/7003
     7 |Foo.new.baz
        ^^^^^^^^^^^
    editor.rb:3: Did you mean: Foo#bar?
     3 |    def bar
            ^^^^^^^
Errors: 1
```

[sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Foo%0A%20%20%20%20def%20bar%0A%20%20%20%20end%0Aend%0A%0AFoo.new.baz%0A)

I think this might be relatively straightforward to implement and very high usage when the feature is shipped.

**Comment by jez** [comment]
I've converted most of these issues into separate tickets for discoverability. See

https://github.com/sorbet/sorbet/milestone/15
