### ISSUE TITLE
Unexpected union (T.any) behavior?

### ISSUE THREAD

**Issue by panthomakos** [sorbet/sorbet#1483]
#### Input

[→ View on sorbet.run](https://sorbet.run/#extend%20T%3A%3ASig%0A%0ANumber%20%3D%20T.type_alias(T.any(Integer%2C%20Float))%0A%0Asig%20%7B%20params(a%3A%20Integer%2C%20b%3A%20Number).returns(Integer)%20%7D%0Adef%20multiply(a%2C%20b)%0A%20%20(a%20*%20b).round%0Aend)

```ruby
extend T::Sig

Number = T.type_alias(T.any(Integer, Float))

sig { params(a: Integer, b: Number).returns(Integer) }
def multiply(a, b)
  (a * b).round
end
```

#### Observed output

```
editor.rb:7: Expected Integer but found T.any(Integer, Float) for argument arg0 https://srb.help/7002
     7 |  (a * b).round
           ^^^^^
    https://github.com/sorbet/sorbet/tree/0c6bdf75780d2f5dd627c7054ce09c67a938304f/rbi/core/integer.rbi#L40: Method Integer#* has specified arg0 as Integer
    40 |        arg0: Integer,
                ^^^^
  Got T.any(Integer, Float) originating from:
    editor.rb:6:
     6 |def multiply(a, b)
                        ^
Errors: 1
```

#### Expected behavior

This is a simplified example, but variations on this theme all produce similar errors (for example, replace `a: Integer` with `a: Number` in the type signature). I would expect this type signature to work. `Integer` supports multiplication with both `Integer` and `Float`.

**Comment by DarkDimius** [comment]
This is a known limitation of our current overload selection algorithm.
It's unlikely that we'll fix it soon, as the complexity of supporting it is tremendous. 
The workaround is either `(a * b.to_f).round` or `(a * b.to_i).round`.

Note that we also consider the current behavior as beneficial, as otherwise figuring out what happens from user perspective with more complex overload resolution is quite hard.

**Comment by DarkDimius** [comment]
As we don't currently intend to fix this limitation, closing to not pile up issues.
