### ISSUE TITLE
Filter Sorbet::Private namespace from hidden.rbi

### ISSUE THREAD

**Issue by connorshea** [sorbet/sorbet#1488]
When running `srb init` for a blank project, the generated `hidden.rbi` file includes some classes in the Sorbet::Private namespace that should probably be filtered out.

For example:
```ruby
class Sorbet::Private::ConstantLookupCache
  def all_module_aliases(); end

  def all_module_names(); end

  def all_named_modules(); end

  def class_by_name(name); end

  def name_by_class(klass); end
  DEPRECATED_CONSTANTS = ::T.let(nil, ::T.untyped)
end

class Sorbet::Private::ConstantLookupCache::ConstantEntry
  def aliases(); end

  def aliases=(_); end

  def const(); end

  def const=(_); end

  def const_name(); end

  def const_name=(_); end

  def found_name(); end

  def found_name=(_); end

  def owner(); end

  def owner=(_); end

  def primary_name(); end

  def primary_name=(_); end
end

class Sorbet::Private::ConstantLookupCache::ConstantEntry
  def self.[](*_); end

  def self.members(); end
end

class Sorbet::Private::ConstantLookupCache
end
```

There are somewhere around ~350 lines of stuff related to Sorbet::Private. Other namespaces are already being filtered here: https://github.com/sorbet/sorbet/blob/85bc1175c3769aee44fee9dba0286e09d519c7f2/gems/sorbet/lib/serialize.rb

**Comment by DarkDimius** [comment]
The proper way would be to publish an `rbi` rather then to filter it.

**Comment by jez** [comment]
I think that we probably don't want to have an RBI for these things, because we don't expect people to ever use them. We certainly could, but I'd still prefer to blacklist them.

The normal way to skip serializing these definitions would be to either mark the gem `require: false` in the `Gemfile` or to add an empty entry in `gem_loader.rb`, but that won't work here because `srb init` has already required itself before it attempts to require any other code for the sake of serializing it. So there's no way to force `srb init` to not see itself, which is why I think that a blacklist for `Sorbet::Private` specifically is warranted.
