### ISSUE TITLE
documentSymbols does not report @foo = 3

### ISSUE THREAD

**Issue by azdavis** [sorbet/sorbet#1552]
## Input

```rb
# typed: true
class C
  @foo = 3
  @bar = T.let(3, Integer)
end
```

## Expected symbols

- `C`
- `@foo`
- `@bar`

## Actual symbols

- `C`
- `@bar`

---

I'm not actually sure if this is a bug, perhaps we don't want to report symbols
that are untyped.

**Comment by jez** [comment]
It's not that it's untyped, but that it's not declared. We can't know whether you meant this to exist, or whether it was accidental. That's why we require instance variables to have types, because otherwise all instances variables can be written to and read from (they're all `nil`) and we can't catch typos.
