### ISSUE TITLE
wrong unreachable warning for code in block

### ISSUE THREAD

**Issue by md-work** [sorbet/sorbet#1610]
The `This code is unreachable` detection has a false positive for code inside a block.

Is there some workaround to silence the warning? E.g. writing some `# ignore Unreachable` beside the else?

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20timer(%26b)%0A%20%20%23%20implements%20some%20timer%20which%20calls%20block%20later%20on%0Aend%0A%0Aalive%20%3D%20true%0Atimer%20do%0A%20%20if%20alive%0A%20%20%20%20puts%20'alive'%0A%20%20else%0A%20%20%20%20puts%20'dying'%0A%20%20%20%20%23%20%3D%3E%20This%20code%20is%20unreachable%0A%20%20end%0Aend%0A%23%20...%20some%20work%20done%20here%0Aalive%20%3D%20false)
```
# typed: true

def timer(&b)
  # implements some timer which calls block later on
end

alive = true
timer do
  if alive
    puts 'alive'
  else
    puts 'dying'
    # => This code is unreachable
  end
end
# ... some work done here
alive = false
```

**Comment by aisamanra** [comment]
This is similar (but not identical) to a current weakness that Sorbet has with loops that's described in the error reference [here](https://sorbet.org/docs/error-reference#7001). In short, because `true` and `false` are instances of `TrueClass` and `FalseClass`, respectively, Sorbet will infer the types of variables like `alive` above as having _just_ the type `TrueClass`, and then the blocked will be typechecked with the then-current environment in which `alive` will never be false.

The workaround is to give an explicitly wider type signature to `alive` using `T.let` which tells Sorbet that it can be either `TrueClass` or `FalseClass`:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20timer(%26b)%0A%20%20%23%20implements%20some%20timer%20which%20calls%20block%20later%20on%0Aend%0A%0Aalive%20%3D%20T.let(true%2C%20T%3A%3ABoolean)%0Atimer%20do%0A%20%20if%20alive%0A%20%20%20%20puts%20'alive'%0A%20%20else%0A%20%20%20%20puts%20'dying'%0A%20%20%20%20%23%20%3D%3E%20This%20code%20is%20unreachable%0A%20%20end%0Aend%0A%23%20...%20some%20work%20done%20here%0Aalive%20%3D%20false)

```ruby
# typed: true

def timer(&b)
  # implements some timer which calls block later on
end

alive = T.let(true, T::Boolean)
timer do
  if alive
    puts 'alive'
  else
    puts 'dying'
    # => This code is unreachable
  end
end
# ... some work done here
alive = false
```

**Comment by md-work** [comment]
> This is similar (but not identical) to a current weakness that Sorbet has with loops that's described in the error reference [here](https://sorbet.org/docs/error-reference#7001). [...]

Hmm I wouldn't fully agree to this.
Actually I think the problem behind my bug is, that it's not trivial way to determine when a Proc in Ruby is being called.

&nbsp;
E.g. for this it might seem clear, that the block is being run immediately. But someone might overwrite the method `Numeric#times`, so that the given block is being run some when later.
```
3.times do |i|
  puts i
end
```

&nbsp;
I actually assume, that there's no easy automatic solution to solve my problem for the static checker. That's why I asked for some kind of `# ignore Unreachable` annotation, to workaround this lack of static knowledge.

For the moment, I just want the error to disappear from the `srb tc` output without moving the code to another file. So developers don't get disturbed by it.

**Comment by jez** [comment]
@aisamanra is on the money with his suggestion. The annotation you're looking for is

```ruby
alive = T.let(true, T::Boolean)
```

Without that annotation, Sorbet thinks that `alive` will be unconditionally `true`, and the annotation says that it might be either `true` or `false`.

Going to close this, because we consider this a sufficient workaround, and there's no obvious work to be done to change this.
