### ISSUE TITLE
Detect boolean

### ISSUE THREAD

**Issue by Paxa** [sorbet/sorbet#1690]
### Problem

Need to add `T.let(true, T::Boolean)` for all boolean values

### Proposed solution

Allow to assign `true` to `false` and vice versa.

I guess this behaviour caused by lack of `Boolean` parent class in ruby, and sorbet checks strictly by parent class. May be we could make an exception?

Now it just makes code not elegant

**Comment by aisamanra** [comment]
Thank you for the suggestion! Unfortunately, while we agree that annotating boolean variables can be verbose at times, we're unlikely to change the current behavior for technical reasons. The underlying problem is that Sorbet [uses the inferred types of variables in order to do flow analysis](https://stackoverflow.com/questions/57829279/why-not-infer-tboolean-for-true-and-false/57829415#57829415), which in turn means we've discovered that it's very difficult to do this generalization in a way that still preserves the flow-sensitivity properties that we want.

Because we're unlikely to change the current behavior, I'm going to close this issue, but if you'd like to discuss this further, we'd be happy to continue discussing it either here or [on the Sorbet slack](https://sorbet.org/en/community). Thank you!

**Comment by Paxa** [comment]
If some day sorbet decide to make it nice and elegant for users, will it be easier to patch ruby to add common parent class for `TrueClass` and `FalseClass` or add some kind of middleware with regex?
```ruby
source.gsub!(/\s=\s(true|false)/, " = T.let(\\1, T::Boolean)")
```

---
btw I found some other bug:

```ruby
  begin
    a = open("123")
    return 123
  ensure
    if a
      p a # => This code is unreachable https://srb.help/7006. Why??
    end
  end
```

Does sorbet has something similar to `@ts-ignore`?
