### ISSUE TITLE
Bad error message for `attr_accessor` with a signature including a type parameter

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#1710]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AR)%0A%20%20%20%20%20%20.returns(T.nilable(%0A%20%20%20%20%20%20%20%20T.type_parameter(%3AR)%0A%20%20%20%20%20%20))%0A%20%20end%0A%20%20attr_accessor%20%3Ako%0Aend)

```ruby
# typed: true

class Foo
  extend T::Sig

  sig do
    type_parameters(:R)
      .returns(T.nilable(
        T.type_parameter(:R)
      ))
  end
  attr_accessor :ko
end
```

#### Observed output

```
editor.rb:9: Unspecified type parameter https://srb.help/5004
     9 |        T.type_parameter(:R)
                                 ^^
Errors: 1
```

#### Expected behavior

Not sure, maybe we should forbid signatures on `attr_accessor` altogether? Or have another way to state the attribute type on it? Anyway the error currently raised is quite confusing here since `R` is actually defined a few characters before.

Same problem with `attr_writer` ([→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AR)%0A%20%20%20%20%20%20.returns(T.nilable(%0A%20%20%20%20%20%20%20%20T.type_parameter(%3AR)%0A%20%20%20%20%20%20))%0A%20%20end%0A%20%20attr_writer%20%3Ako%0Aend)) but at least, the second error message gives some hints.

This works like it should with `attr_reader` ([→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters(%3AR)%0A%20%20%20%20%20%20.returns(T.nilable(%0A%20%20%20%20%20%20%20%20T.type_parameter(%3AR)%0A%20%20%20%20%20%20))%0A%20%20end%0A%20%20attr_reader%20%3Ako%0Aend))

**Comment by aisamanra** [comment]
This looks like it's just a bug in the DSL pass that implements `attr_accessor`. It should be straightforward to fix—I'll take a stab at it this afternoon.

**Comment by aisamanra** [comment]
On reflection, I think we don't ever want `type_parameters` in `attr_*` types anyway. Even something simple in the `attr_reader` case looks innocuous, but can't actually be instantiated:
```
sig { type_parameters(:R).returns(T.type_parameter(:R)) }
attr_reader :foo
```
(c.f. the relevant [sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%20%20)). I'm putting together a PR which will identify type signatures on `attr`s that include type parameters and warn you, so you'll get a sensible error instead of the misleading ones above.

**Comment by jez** [comment]
For the record, the root cause of the bug here is that for `attr_accessor`, in the setter component, the DSL'd method body ends up using a `T.let` to declare the type of the instance variable that backs the attr_accessor:

```ruby
def foo=(foo)
  @foo = T.let(foo, T.nilable(T.type_parameter(:R))
end
```

But we have an unrelated bug that it's not actually possible to refer to a type_parameter within the method body:

#1715
