### ISSUE TITLE
flow sensitivity (type refinement) for destructured nilable array

### ISSUE THREAD

**Issue by kenneth-stripe** [sorbet/sorbet#1759]
### Problem

If a method returns either nil or multiple values (in an array), should flow sensitivity be smart enough to refine all the types of the child elements?

```ruby
# typed: true
extend T::Sig

sig {returns(T.nilable([String, String]))}
def bar
end

a, b = bar

if a
  T.reveal_type(a)
  T.reveal_type(b) # Should sorbet be smart enough to know that this is String instead of T.nilable(String)?
end

combined = bar
if combined 
  c, d = combined
  T.reveal_type(c)
  T.reveal_type(d)
end
```

https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Breturns(T.nilable(%5BString%2C%20String%5D))%7D%0Adef%20bar%0Aend%0A%0Aa%2C%20b%20%3D%20bar%0A%0Aif%20a%0A%20%20T.reveal_type(a)%0A%20%20T.reveal_type(b)%20%23%20Should%20sorbet%20be%20smart%20enough%20to%20know%20that%20this%20is%20String%20instead%20of%20T.nilable(String)%3F%0Aend%0A%0Acombined%20%3D%20bar%0Aif%20combined%20%0A%20%20c%2C%20d%20%3D%20combined%0A%20%20T.reveal_type(c)%0A%20%20T.reveal_type(d)%0Aend

**Comment by jez** [comment]
Thanks for the suggestion!

We're unlikely to change this in the short term. There's already a fine workaround, and arguably the workaround leads to clearer code (the logic follows the structure of the type).

Because it's unlikely to change soon, I'm going to close this issue. If you'd like to chat about this feature, we're happy to keep the conversation going in the #ruby-types channel on Slack. It's a bit easier to explain these sorts of things there, because everyone has their own background and assumptions of how Sorbet "should" work.

Thanks again for the suggestion!
