### ISSUE TITLE
Repos with Sorbet are problematic on NTFS partitions due to filenames

### ISSUE THREAD

**Issue by AaronC81** [sorbet/sorbet#1782]
The characters `<` and `>` are not valid characters for a file or directory name on an NTFS filesystem. (https://docs.microsoft.com/en-us/windows/win32/fileio/naming-a-file)

Because sorbet-typed uses this to differentiate RBIs between versions, a repo which uses Sorbet will likely contain this character. This means that these parts of the repo cannot be cloned or downloaded onto any NTFS drive.

Here's an example of trying to clone a repo with Sorbet onto my NTFS drive mounted at `/mnt/hdd`:
```
/mnt/hdd/public-gits >>> git clone https://github.com/connorshea/VideoGameList/
Cloning into 'VideoGameList'...
remote: Enumerating objects: 401, done.
remote: Counting objects: 100% (401/401), done.
remote: Compressing objects: 100% (248/248), done.
remote: Total 11811 (delta 240), reused 250 (delta 141), pack-reused 11410
Receiving objects: 100% (11811/11811), 5.76 MiB | 2.36 MiB/s, done.
Resolving deltas: 100% (8159/8159), done.
fatal: cannot create directory at 'sorbet/rbi/sorbet-typed/lib/activerecord/>=5.2': Invalid argument
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

Running `srb rbi sorbet-typed` also fails:

```
/mnt/.../public-gits/VideoGameList >>> srb rbi sorbet-typed
Running command: sorbet-typed
Generating: sorbet/rbi/sorbet-typed/
Traceback (most recent call last):
	13: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4755/bin/srb-rbi:237:in `<main>'
	12: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4755/bin/srb-rbi:224:in `main'
	11: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4755/bin/srb-rbi:232:in `block in make_step'
	10: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4755/lib/fetch-rbis.rb:118:in `main'
	 9: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4755/lib/fetch-rbis.rb:85:in `vendor_rbis_within_paths'
	 8: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4755/lib/fetch-rbis.rb:85:in `each'
	 7: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sorbet-0.4.4755/lib/fetch-rbis.rb:89:in `block in vendor_rbis_within_paths'
	 6: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/2.6.0/fileutils.rb:200:in `mkdir_p'
	 5: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/2.6.0/fileutils.rb:200:in `each'
	 4: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/2.6.0/fileutils.rb:215:in `block in mkdir_p'
	 3: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/2.6.0/fileutils.rb:215:in `reverse_each'
	 2: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/2.6.0/fileutils.rb:217:in `block (2 levels) in mkdir_p'
	 1: from /home/aaron/.rbenv/versions/2.6.3/lib/ruby/2.6.0/fileutils.rb:239:in `fu_mkdir'
/home/aaron/.rbenv/versions/2.6.3/lib/ruby/2.6.0/fileutils.rb:239:in `mkdir': Invalid argument @ dir_s_mkdir - sorbet/rbi/sorbet-typed///lib/activerecord/>=5.2 (Errno::EINVAL)
```

**Comment by eni9889** [comment]
@AaronC81 I am running into the same issue, have you figured out a work around?

**Comment by AaronC81** [comment]
I haven't figured out a workaround, I'm afraid...

**Comment by connorshea** [comment]
A friend of mine just ran into this when trying to contribute to my project that uses Sorbet :/

One idea I had for a workaround would be to do something kinda crazy (and that would require changes in the Sorbet gem):
- Stop including sorbet-typed in the repo directly
- Instead, the repo would only track a `.sorbet-typed-sha` file that just has the SHA hash for whatever commit the sorbet-typed repo is on.
- When the user clones the repo, they can run `bundle exec srb sync` (or something like that) to pull down the sorbet-typed files. (Assuming the check was fast enough, maybe `srb tc` could even pull down sorbet-typed for you automatically?)
- Sorbet would automatically use the 'normal' `>=3` style for directory names when on a compatible filesystem, otherwise it would use an escaped version like `gt;=3`. We'd need to modify Sorbet to understand the escaped directory names when on an NTFS filesystem.

So the directory names that cause problems wouldn't be in the git repo and the repo would be clone-able on NTFS filesystems.

You could probably jerry-rig this in your own repo without _that_ much trouble. You'd just need to have contributors always use a wrapper Rake task (or Bash script) when interacting with Sorbet and then you'd abuse the `SORBET_TYPED_REVISION` environment variable to have sorbet fetch a specific commit for sorbet-typed.

The only problem would be that pulling down the sorbet-typed git repo would fail on NTFS filesystems, which would be a problem for getting the files from the command in the first place 🤔  I'm not sure if git provides some weird magic to work around that problem with a flag or something?

**Comment by connorshea** [comment]
Of course, the easiest fix would always be to just change all the directories in sorbet-typed to not have these bad names.

**Comment by connorshea** [comment]
Detecting the filesystem type is surprisingly difficult in Ruby, it seems (I guess you could just try creating a tempfile with a `<` in its name and see if it errors but that feels really gross). The best option I've found would require a dependency on the `sys-filesystem` gem.

**Comment by AaronC81** [comment]
I feel like the simplest solution - changing the `<` and `>` symbols to something else in sorbet-typed - might well be the most effective. Although the `.sorbet-typed-sha` method certainly has its advantages and cuts down diff sizes in repos using Sorbet, I think a lot of weird bodging would be required to get it working seamlessly.

I think the `gt;` and `lt;` escape syntax you've suggested would work well, since it's easy to understand, and `;` isn't already a requirement separator used by Sorbet:

https://github.com/sorbet/sorbet/blob/13564f69aca8710852547fc0e23cb505ec1a7583/gems/sorbet/lib/fetch-rbis.rb#L56-L60

**Comment by nitsujri** [comment]
We just ran into this issue on a new member coming in on Win/NTFS. Has anyone figured out an elegant/easy work around?

**Comment by jez** [comment]
This is a sorbet-typed problem. Switching to Tapioca will involve switching away from using sorbet-typed.

Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
