### ISSUE TITLE
Type members should encourage safe typing by default

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#1804]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Arequire%20'sorbet-runtime'%0A%0Amodule%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member()%0A%0A%20%20sig%20%7Bparams(x%3A%20Elem).void%7D%0A%20%20def%20foo(x)%3B%20end%0A%0A%20%20sig%20%7Bparams(x%3A%20A%5BElem%5D).void%7D%0A%20%20def%20bar(x)%3B%20end%0Aend%0A%0Aclass%20B%0A%20%20include%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Elem%20%3D%20type_member(upper%3A%20String)%0Aend%0A%0Aclass%20Test%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20params(x%3A%20A%5BObject%5D).void%20%7D%0A%20%20def%20foo(x)%0A%20%20%20%20x.foo(10)%20%23%20Boom!%0A%20%20end%0Aend%0A%0ATest.new.foo(B.new))

```ruby
# typed: true

require 'sorbet-runtime'

module A
  extend T::Sig
  extend T::Generic

  Elem = type_member()

  sig {params(x: Elem).void}
  def foo(x); end

  sig {params(x: A[Elem]).void}
  def bar(x); end
end

class B
  include A
  extend T::Sig
  extend T::Generic

  Elem = type_member(upper: String)
end

class Test
  extend T::Sig

  sig { params(x: A[Object]).void }
  def foo(x)
    x.foo(10) # Boom!
  end
end

Test.new.foo(B.new)
```

#### Observed output

```
No errors! Great job.
```

#### Expected behavior

I think this should be rejected by default if the developer doesn't specify any `:in` or `:out` in the `type_member` as it leads to statically unsafe code.

**Comment by elliottt** [comment]
We don't currently have a way of describing a type member as invariant (both in and out) explicitly; type members are invariant by default. Supporting this change will require us to address this, and allow type members to be marked invariant explicitly.

**Comment by jez** [comment]
The problem here is that `B.new`, without being passed explicit type arguments like `B[String].new`, is simply typed as `B[T.untyped]`, which is then compatible with `A[Object]`.

If you change the example to say `B[String].new`, then an error is reported.

So the real issue here is either requiring or inferring a better type than `T.untyped` for the result of `new` here. We have some other issues for that:

#4978 

#4450 

So I'm going to close this one. It is a good test case though.
