### ISSUE TITLE
T.cast should be allowed as a way to set attribute value

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#1844]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strong%0A%0Aclass%20A%3B%20end%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20sig%20%7B%20void%20%7D%0A%20%20def%20initialize%0A%20%20%20%20%40foo%20%3D%20T.let(A.new%2C%20A)%0A%20%20end%0A%0A%20%20sig%20%7B%20params(obj%3A%20Object).void%20%7D%0A%20%20def%20error(obj)%0A%20%20%20%20%40foo%20%3D%20T.cast(obj%2C%20A)%0A%20%20end%0A%0A%20%20sig%20%7B%20params(obj%3A%20Object).void%20%7D%0A%20%20def%20ok(obj)%0A%20%20%20%20foo%20%3D%20T.cast(obj%2C%20A)%0A%20%20%20%20%40foo%20%3D%20foo%0A%20%20end%0Aend)

```ruby
# typed: strong

class A; end

class Foo
  extend T::Sig
  
  sig { void }
  def initialize
    @foo = T.let(A.new, A)
  end

  sig { params(obj: Object).void }
  def error(obj)
    @foo = T.cast(obj, A)
  end

  sig { params(obj: Object).void }
  def ok(obj)
    foo = T.cast(obj, A)
    @foo = foo
  end
end
```

#### Observed output

```
editor.rb:15: Use T.let to specify the type of constants https://srb.help/5013
    15 |    @foo = T.cast(obj, A)
                   ^^^^^^^^^^^^^^

editor.rb:15: The instance variable @foo must be declared inside initialize or declared nilable https://srb.help/5005
    15 |    @foo = T.cast(obj, A)
            ^^^^
Errors: 2
```

#### Expected behavior

I would expect the first form to be correct and accepted by Sorbet. Furthermore if the second one is accepted as well.

- - -

If the idea is to remind to the user about declaring the attribute with `T.let` I think there are other possible avenues:
* Outputting a warning instead of an error
* Merging the message with the one of the 5005: `The instance variable @foo must be declared inside initialize **with T.let** or declared nilable.`

**Comment by jez** [comment]
I think if we were to make changes here, we'd be **more** likely to introduce a third helper method, rather than jam even more stuff into the existing ones.

First things first: you have a slight problem with your repro. Because all the examples are in the same class, `@foo` only needs to be declared once. That's why the `def ok` examples doesn't complain. If you put all the methods into their own class, you'll see that we complain:

```ruby
# typed: strong
class Module
  include T::Sig
end

class A
  sig {void}
  def initialize
    @foo = T.let(Object.new, Integer)
  end
end

class B
  sig {void}
  def initialize
    @foo = T.cast(Object.new, Integer)
  end
end

class C
  sig {void}
  def initialize
    foo = T.cast(Object.new, Integer)
    @foo = foo
  end
end
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strong%0Aclass%20Module%0A%20%20include%20T%3A%3ASig%0Aend%0A%0Aclass%20A%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20initialize%0A%20%20%20%20%40foo%20%3D%20T.let(Object.new%2C%20Integer)%0A%20%20end%0Aend%0A%0Aclass%20B%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20initialize%0A%20%20%20%20%40foo%20%3D%20T.cast(Object.new%2C%20Integer)%0A%20%20end%0Aend%0A%0Aclass%20C%0A%20%20sig%20%7Bvoid%7D%0A%20%20def%20initialize%0A%20%20%20%20foo%20%3D%20T.cast(Object.new%2C%20Integer)%0A%20%20%20%20%40foo%20%3D%20foo%0A%20%20end%0Aend)

Or alternatively, if in your example we use a different name for the instance variable in `def ok`:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strong%0A%0Aclass%20A%3B%20end%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20sig%20%7B%20void%20%7D%0A%20%20def%20initialize%0A%20%20%20%20%40foo%20%3D%20T.let(A.new%2C%20A)%0A%20%20end%0A%0A%20%20sig%20%7B%20params(obj%3A%20Object).void%20%7D%0A%20%20def%20error(obj)%0A%20%20%20%20%40foo%20%3D%20T.cast(obj%2C%20A)%0A%20%20end%0A%0A%20%20sig%20%7B%20params(obj%3A%20Object).void%20%7D%0A%20%20def%20ok(obj)%0A%20%20%20%20bar%20%3D%20T.cast(obj%2C%20A)%0A%20%20%20%20%40bar%20%3D%20bar%0A%20%20end%0Aend)

To my original point, currently `T.let` is doing double duty:

1. it's a way to ask sorbet to strictly widen the type of an expression
  - kind of the same, but kind of different: it's a way to pin the type of a local variable outside a block
2. it's a way to declare the type of an instance variable

We probably shouldn't have re-used `T.let` for (2), and instead kept it as only doing (1). That's an unfortunate historical accident, and we've considered pulling these behaviors apart in the past.

In that hierarchy, `T.cast` is just sort of unrelated: it throws away type information and uses other information, rather than strictly widening the type.
