### ISSUE TITLE
Sorbet wrongly flags Hash.new with object that has #to_hash as input

### ISSUE THREAD

**Issue by ivoanjo** [sorbet/sorbet#1923]
#### Input

[→ View on sorbet.run](https://sorbet.run/#class%20Foo%0Adef%20to_hash%0A%7Bfoo%3A%201%7D%0Aend%20%20%0Aend%20%20%0A%0AHash%5BFoo.new%5D%0A)

```ruby
class Foo
def to_hash
{foo: 1}
end  
end  

Hash[Foo.new]
```

#### Observed output

```ruby
editor.rb:7: Expected T::Array[[U, V]] but found Foo for argument arg0 https://srb.help/7002
     7 |Hash[Foo.new]
        ^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/hash.rbi#L165: Method Hash.[] has specified arg0 as T::Array[[U, V]]
     165 |      arg0: T::Array[[T.type_parameter(:U), T.type_parameter(:V)]],
                ^^^^
  Got Foo originating from:
    editor.rb:7:
     7 |Hash[Foo.new]
             ^^^^^^^
Errors: 1
```

#### Expected behavior

- - -

As documented in <https://ruby-doc.org/core-2.5.6/Hash.html#method-c-5B-5D> it's possible to call `Hash[]` with "an object convertible to a hash".

(This seems a sibling of the Array issue I reported -- https://github.com/sorbet/sorbet/issues/1913 )

**Comment by jez** [comment]
Sorbet does not support implicit interfaces like this. The workaround in this case is to just call `.to_hash` directly, instead of relying on `Hash#[]` to do it.

```ruby
Hash[Foo.new.to_hash]
```

I normally suggest changing the RBI to allow things that Ruby allows, but the only way to do this would be to untype the definition of `Hash#[]`, which would mean that a lot of people would lose valuable type checking.

Thanks for the report.
