### ISSUE TITLE
provide safe way to handle variables as boolean

### ISSUE THREAD

**Issue by md-work** [sorbet/sorbet#1947]
Sorbet only accept true and false for T::Boolean, which is probably good because it increases chances to see if a value is unwillingly used as boolean.

But there are many situations, where one might use a value as boolean. In this case some might use !! (double negation). But this might be a problem too and so it's forbidden by systems like Rubocop.
I guess one problem might be, that it's quite risky to write an odd number of exclamation marks instead of an even one.

I see two possible nice solutions which Sorbet could provide:
- a type T::Boolish - in contrast to T::Boolean this accepts any value and converts it to boolean.
- a method T.to_b(value) - converts the given value to boolean, like !! does

**Comment by elliottt** [comment]
The second approach seems pretty reasonable to me, would you like to make a PR?

**Comment by jez** [comment]
Actually can we hold on a second? I'd like for us to think this over.

**Comment by jez** [comment]
Some counter points:

- The fact that `!!` is built-in to Ruby means that everyone can already understand what it does, without having to learn something Sorbet-specific
- The Rubocop rule is useful in a world without types, because Rubocop is the only other way to enforce consistency. But with Sorbet, the types dictate when `!!` must or must not be used. Arguably, that rule should be disabled in codebases using Sorbet, because Sorbet knows better than Rubocop (it can see the type information).
- The `T` namespace is a public API that we have to commit to maintaining. We should not add things to it without good reason, especially when alternatives exist.

**Comment by elliottt** [comment]
All good points. Maybe a project-local version of `to_b` is the best option here?

**Comment by jez** [comment]
I think there are too many points in favor of simply using `!!x` (it's Ruby code that people already understand, it solves the problem of expecting a `T::Boolean`, it's fast because the Ruby VM has special handling to make calling the `!` method fast, etc.)

Adding some sort of `T.to_b` method would just be a way to disable the Rubocop rule without explicitly disabling the rule, which indicates to me that the rule isn't providing much value.

Thanks for the feature suggestion, but I think we'll pass on this for the time being.
