### ISSUE TITLE
Control flow should understand `T.must` as implying non-nil

### ISSUE THREAD

**Issue by benbuckman** [sorbet/sorbet#2034]
### Problem
If a variable is defined as `nilable`, but its runtime value is known to be non-`nil`, a single `T.must` should be sufficient for the flow control parser to understand that the value is not `nil`.

`T.must` will `raise` if the value is `nil`, and the flow control currently works with `raise`, but not with `T.must`.

For example:
1. [sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(n%3A%20T.nilable(Integer)).void%7D%0A%20%20def%20initialize(n)%0A%20%20%20%20%40n%20%3D%20T.let(n%2C%20T.nilable(Integer))%0A%20%20end%0A%0A%20%20sig%20%7Breturns(T.nilable(Integer))%7D%0A%20%20def%20add!%0A%20%20%20%20raise("missing%20number")%20if%20!%40n%0A%20%20%20%20%40n%20%2B%201%0A%20%20end%0Aend%0A)
 – Sorbet understands that @n in `add!` is not nil, and can execute `+` on it. ✅ 
```ruby
# typed: strict
class A
  extend T::Sig

  sig {params(n: T.nilable(Integer)).void}
  def initialize(n)
    @n = T.let(n, T.nilable(Integer))
  end

  sig {returns(T.nilable(Integer))}
  def add!
    raise("missing number") if !@n
    @n + 1
  end
end
```

2. [sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(n%3A%20T.nilable(Integer)).void%7D%0A%20%20def%20initialize(n)%0A%20%20%20%20%40n%20%3D%20T.let(n%2C%20T.nilable(Integer))%0A%20%20end%0A%0A%20%20sig%20%7Breturns(T.nilable(Integer))%7D%0A%20%20def%20add!%0A%20%20%20%20T.must(%40n)%0A%20%20%20%20%40n%20%2B%201%0A%20%20end%0Aend%0A) – With `T.must`, Sorbet says `Method + does not exist on NilClass component of T.nilable(Integer)`: 
```ruby
# typed: strict
class A
  extend T::Sig

  sig {params(n: T.nilable(Integer)).void}
  def initialize(n)
    @n = T.let(n, T.nilable(Integer))
  end

  sig {returns(T.nilable(Integer))}
  def add!
    T.must(@n)
    @n + 1
  end
end
```

### Proposed solution

`T.must` should be understood as implying non-`nil` in the same method, in the same way that it understands `raise if n.nil?`.

**Comment by jez** [comment]
100% of control-flow sensitive typing is tied to... control flow. If there is no control flow, Sorbet will not apply control-flow sensitive typing.

Thanks for the suggestion, but this is probably a won't do.

**Comment by paracycle** [comment]
> `T.must` will `raise` if the value is `nil`

Btw, this is not a valid assumption to make. For example, we suppress the runtime checker on production which means `T.must` will do nothing. So, you can't just assume that `T.must` and `raise` are interchangeable and start treating `T.must` like a control flow operator.

**Comment by benbuckman** [comment]
> 100% of control-flow sensitive typing is tied to... control flow.

Thanks.
It seems that the distinction is whether Sorbet thinks the variable is definitely local, vs possibly being a method, the return value of which it can't guarantee.
However, there seems to be a hole with `raise`, which can also be overridden at runtime.
It does seem to understand the difference between an explicitly-overridden `raise` vs none – 

https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20%23%23%20UNCOMMENT%20ME%20FOR%20ERROR%20-%20THAT'S%20GOOD%2C%0A%20%20%23%23%20BUT%20WHAT%20IF%20THIS%20WAS%20IN%20AN%20UNTYPED%20FILE%3F%0A%20%20%23sig%20%7Bparams(msg%3A%20T.untyped).void%7D%0A%20%20%23def%20raise(msg)%0A%20%20%23%20%20puts%20"Hello%20%23%7Bmsg%7D%2C%20carry%20on"%0A%20%20%23end%0Aend%0A%0Aclass%20B%20<%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(n%3A%20T.nilable(Integer)).returns(T.nilable(Integer))%7D%0A%20%20def%20add(n)%0A%20%20%20%20raise("missing%20number")%20if%20!n%0A%20%20%20%20n%20%2B%201%0A%20%20end%0Aend%0A

– but Sorbet's confidence there that it knows where `raise` is defined seems inconsistent with the other behaviors here, e.g. it could similarly see what `T.must` is doing, or any other method; or it similarly does not know if `raise` is overridden.

This inconsistency leads me to be confused about Sorbet's definition of control flow.

**Comment by jez** [comment]
> Btw, this is not a valid assumption to make

Sorbet is not guaranteed to work when the runtime checks are disabled. That is why we strongly recommend turning on the runtime checks.

> but Sorbet's confidence there that it knows where `raise` is defined seems inconsistent with the other behaviors here, e.g. it could similarly see what `T.must` is doing, or any other method; or it similarly does not know if `raise` is overridden.

To sorbet, `raise` is always either an unconditional raise. The condition of whether to raise or not to raise must be visible in the source of the method—in this case, it's the `if !n` that Sorbet uses to do control-flow sensitive typing.

Other than that, `raise` works like any other method that's defined to return `T.noreturn`:

https://github.com/sorbet/sorbet/blob/19e6ed2468a2cf62794e21bf255f24c894b8cb4c/rbi/core/kernel.rbi#L2563-L2568

Since Sorbet could see that the overridden `raise` no longer returned `T.noreturn`, it knew that there were two paths of control flow through the program that could affect `n`'s type, whereas before it knew there were 2.

**Comment by jez** [comment]
Note that anyone is free to implement methods that unconditionally raise; Sorbet will treat them identically to `raise` itself, as long as they return `T.noreturn`. What Sorbet does not allow users to model is methods that sometimes raise and sometimes don't, because then the condition is hidden inside that method definition.

All inference in Sorbet is 100% local to the current method being type checked. For sorbet to let the implementation of one method affect the implementation of another method would be a large architectural shift, and would force us to reconsider nearly everything about how we optimize editor query response times.
