### ISSUE TITLE
Segfault when intersecting interface and generics

### ISSUE THREAD

**Issue by gmalette** [sorbet/sorbet#206]
https://sorbet.run/#module%20Interface%0A%20%20extend(T%3A%3ASig)%0A%20%20interface!%0Aend%0A%0Aclass%20Klass%0A%20%20R%20%3D%20type_member%0A%20%20%0A%20%20sig%20%7B%20params(params%3A%20T.all(R%2C%20Interface)).void%20%7D%0A%20%20def%20foo(params)%0A%20%20end%0Aend

```ruby
module Interface
  extend(T::Sig)
  interface!
end

class Klass
  R = type_member
  
  sig { params(params: T.all(R, Interface)).void }
  def foo(params)
  end
end
```

**Comment by benbuckman-stripe** [comment]
Probably the same issue – a similar segfault occurs with `abstract!` + `type_member`:

https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Instruction%20%3C%20T%3A%3AStruct%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20TypeElem%20%3D%20type_member%0A%20%20const%20%3Atype%2C%20T.all(TypeElem%2C%20AbstractType)%20%23%20static%20and%20runtime%3F%0Aend%0A%0Amodule%20AbstractType%0A%20%20extend%20T%3A%3AHelpers%0A%20%20abstract!%0Aend%0A%0Aclass%20FooType%20%3C%20T%3A%3AStruct%0A%20%20extend%20AbstractType%0A%20%20const%20%3Afoo%2C%20Integer%0Aend%0A%0Aclass%20BarType%20%3C%20T%3A%3AStruct%0A%20%20extend%20AbstractType%0A%20%20const%20%3Abar%2C%20Integer%0Aend

**Comment by andrejewski-stripe** [comment]
Tacking on to this as it seems roughly the same as my case of:
```rb
# typed: true
class A
  extend T::Sig
  extend T::Generic

  M = type_member

  sig {params(x: T.all(M, Integer)).returns(String)}
  def bar(x); end
end
```
[[Playground link]](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20M%20%3D%20type_member%0A%0A%20%20sig%20%7Bparams(x%3A%20T.all(M%2C%20Integer)).returns(String)%7D%0A%20%20def%20bar(x)%3B%20end%0Aend)

---

For those trying to get around this limitation, you may want to try, instead of `T.all(M, C)`, the type member `type_member(upper: C)` which is saying "a type member which is a subtype of C" which in my case was preferable to using `T.all`.
