### ISSUE TITLE
Offer homebrew formulae for sorbet

### ISSUE THREAD

**Issue by fzakaria** [sorbet/sorbet#2213]
### Problem

At the moment, those that are using JRuby, sorbet-static can never be installed via gem/bundler.

sorbet-static is platform dependent and has the gem name such as: `sorbet-static-0.4.5055-universal-darwin-19.gem` (darwin being OSX & universal the CPU type)

However when running on JRuby platform the only platforms available are:

```
$ gem env
...
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-java-1.8
```

Whereas on MRI it will list
```
$ gem env
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-18
```

This means that the sorbet-static gem can **never** be installed while using JRuby :(

This is unconventional use of using `gems`  -- typically the platform in the gem name would make sense because JRuby cannot use a library that is native C code. However in this case `sorbet-static` is never required by the codebase in question and just used a tool to run the type check.

### Proposed solution

1. I've already contributed https://github.com/sorbet/sorbet/pull/2212 to search for `sorbet` on the PATH via `srb`
2. submit a formulae to [homebrew](https://brew.sh/) that will install from source or prebuilt binary and make available the sorbet binary.

**Comment by jez** [comment]
You don't need (1) to implement (2). The only thing that `srb tc` is doing is finding an executable for `sorbet` and then calling it. If you've already put `sorbet` on your path, then calling `sorbet` is identical to calling `srb tc`.

Homebrew is a package manager maintained by the community. If you want to maintain a formula for sorbet, feel free to make one. On the Sorbet team we're more interested in providing only the most essential distribution channels so that we don't have to maintain so many things.

In particular, we publish pre-built binaries for mac and linux on ever master commit to our [Releases](https://github.com/sorbet/sorbet/releases) tab. Feel free to use that or something else as a starting point.

In particular though, using Sorbet on JRuby is known to be poorly supported right now, and the Sorbet team has no intention of staffing an effort to support it in the near future, so know that if you want to go down that road, you'll likely be paving your own way.

**Comment by fzakaria** [comment]
I offered (1) because the documentation streamlines just running `srb` rather than `sorbet` ?
Seems advantageous to make the native code installable regardless of Ruby environment.

**Comment by fzakaria** [comment]
I have proffered a brew file to homebrew-core: https://github.com/Homebrew/homebrew-core/pull/47173
