### ISSUE TITLE
Does not allow ->() to be used in a module

### ISSUE THREAD

**Issue by YunZhi246** [sorbet/sorbet#2261]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Amodule%20Bar%0A%20%20extend(T%3A%3ASig)%0A%0A%20%20sig%20%7B%20returns(T.proc.params(a%3A%20T.untyped%2C%20b%3A%20T.untyped).void)%20%7D%0A%20%20def%20hello%0A%20%20%20%20-%3E%20(a%2Cb)%20%7B%20a%20%2B%20b%20%7D%0A%20%20end%0Aend)

```ruby
# typed: strict
module Bar
  extend(T::Sig)

  sig { returns(T.proc.params(a: T.untyped, b: T.untyped).void) }
  def hello
    -> (a,b) { a + b }
  end
end
```

#### Observed output

```
editor.rb:7: Method lambda does not exist on Bar https://srb.help/7003
     7 |    -> (a,b) { a + b }
            ^^^^^^^^^^^^^^^^^^
  Did you mean to `include Kernel` in this module?
    https://github.com/sorbet/sorbet/tree/master/rbi/core/kernel.rbi#L1715: Did you mean: Kernel#lambda?
    1715 |  def lambda(&blk); end
            ^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behaviour

No issues to be displayed.

**Comment by jez** [comment]
This is expected behavior. See https://github.com/sorbet/sorbet/issues/2236

**Comment by aisamanra** [comment]
This is something we could model more precisely, but it's going to be a lot of work for comparatively little benefit. You can already work around this problem by using `include Kernel` in the body of your module, like the error message suggests.

**Comment by paracycle** [comment]
@jez I think this particular case is a little different, though, since this is actually valid Ruby code being flagged as invalid by Sorbet.

For example:
```ruby
module Bar
  def hello
    -> (a,b) { a + b }
  end
end

class Foo < BasicObject
  include ::Bar
end

Foo.new.hello # is ok
Foo.new.hello.(1, 2) #=> 3
```

I think the problem is that Sorbet desugars `->` to `lambda` but `lambda` happens to be a `Kernel` method, thus causing the error in Sorbet. However, at runtime `->` has slightly different semantics than `Kernel.lambda`, so the code is actually valid.

But I see the point @aisamanra is making, that it might be way more hassle to model this precisely. I just wanted to point out that this is not exactly the same case as #2236, though.

**Comment by Morriar** [comment]
What about desugaring `->` as `Kernel.lambda`?

```ruby
module Bar
  def hello
    Kernel.lambda { |a, b| a + b }
  end
end

class Foo < BasicObject
  include ::Bar
end

puts Foo.new.hello # is ok
puts Foo.new.hello.(1, 2) #=> 3
```

And it [typechecks](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20Bar%0A%20%20def%20hello%0A%20%20%20%20Kernel.lambda%20%7B%20%7Ca%2C%20b%7C%20a%20%2B%20b%20%7D%0A%20%20end%0Aend%0A%0Aclass%20Foo%20%3C%20BasicObject%0A%20%20include%20%3A%3ABar%0Aend%0A%0Aputs%20Foo.new.hello%20%23%20is%20ok%0Aputs%20Foo.new.hello.(1%2C%202)%20%23%3D%3E%203).

**Comment by DarkDimius** [comment]
Nice idea! can you make a PR with it?
