### ISSUE TITLE
Support signature aliases

### ISSUE THREAD

**Issue by asilano** [sorbet/sorbet#2286]
### Problem

When implementing a dispatcher-type pattern, I have ended up with a lot of functions all with the same signature. I have to provide the full `sig` invocation for each, like this:

```ruby
sig { params(arg1: Integer, arg2: Integer).returns(Integer) }
def do_foo(arg1, arg2)
end

sig { params(arg1: Integer, arg2: Integer).returns(Integer) }
def do_bar(arg1, arg2)
end

sig { params(arg1: Integer, arg2: Integer).returns(Integer) }
def do_wibble(arg1, arg2)
end

def dispatch(method, arg1, arg2) # `method` is symbol
  send(method, arg1, arg2)
end
```
### Proposed solution

It would be helpful to be able to alias a `sig` declaration to a meaningful name. Something like:

```ruby
operator = T.sig_alias(sig { params(arg1: Integer, arg2: Integer).returns(Integer) })

operator
def do_foo(arg1, arg2)
end

operator
def do_bar(arg1, arg2)
end

operator
def do_wibble(arg1, arg2)
end

def dispatch(method, arg1, arg2) # `method` is symbol
  send(method, arg1, arg2)
end
```

**Comment by Morriar** [comment]
In my opinion there are at least two aspects to a signature:
1. benefit from the safety of a type checker (*writer*-end);
2. understand the intent (*reader*-end).

While I like the proposed feature for the signature *writer*, I'm not sure I would like it as a *reader*:

* For the *writer* it makes the typing process less of a burden since he can factorize its definitions and benefit from the type checker;

* On the other hand, as a *reader*, most of the time, I'm looking to use a method and will directly jump/grep to the method and find the signature here. Having to do a second indirection to find the actual signature seems a bit tedious.

From the specification point-of-view it also comes with a lot of questions. Can the signature alias be used across files? Should we namespace it to avoid conflicts? Can we redefine it? Can it be combined with type aliases?

Considering that you shouldn't be writing this kind of code every morning, what are the real benefits of this feature compared to changes needed?

**Comment by asilano** [comment]
All aliases increase the burden on the reader in the way you describe - with `AB = T.type_alias {T.any(A, B)}` the reader has to know or look up `AB` when it appears in signatures. 

In practice, if an alias is well-named, it also reduces burden on the reader since they only have to understand the alias rather than parse the original syntax (dropping into C++ for a moment, `typedef std::map<int, std::string>::iterator int_to_str_iter;` makes any code that needs to use it far more readable).

As for a use-case, as it happens I _am_ writing code like the above, albeit in a slightly artificial situation. Another thought, although it's obviously another step up in complexity: if you could somehow combine the sig alias with the parameter type for blocks, it would give a clearer way for functions that `yield` to describe to their callers the sort of methods that can be passed for the block - eg

```ruby
module Enumerable
  sig { params(blk: predicate).returns(T::Boolean) }
  def any?(&blk)
    #...
  end
end

class Integer
  predicate
  def even?
    self % 2 == 0
  end
end
```

**Comment by jez** [comment]
+1 to everything @Morriar said. We've had the same conversation internally from people asking for this at stripe and sided in favor of being explicit every time.

Thanks for the idea, but I think we're going to pass on this for the time being.
