### ISSUE TITLE
Alias method inside a self <<

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#23]
https://sorbet.run/#class%20A%0A%20%20def%20self.foo%0A%20%20%20%20puts%20%27hi%27%0A%20%20end%0Aend%0A%0Aclass%20B%20%3C%20A%0A%20%20class%20%3C%3C%20self%0A%20%20%20%20alias_method%20%3Anew_foo%2C%20%3Afoo%0A%20%20end%0Aend%0A%0AB.new_foo

should typecheck

Originally reported by @pt-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1545

**Comment by halorgium** [comment]
I can report that the issue seems to be related to inheritance, not the `class << self`. 

https://sorbet.run/#class%20A%0A%20%20class%20%3C%3C%20self%0A%20%20%20%20def%20foo%0A%20%20%20%20%20%20puts%20'hi'%0A%20%20%20%20end%0A%0A%20%20%20%20alias_method%20%3Anew_foo%2C%20%3Afoo%0A%20%20end%0Aend%0A%0AA.new_foo

The problem manifests using instance methods too. 

https://sorbet.run/#class%20A%0A%20%20def%20foo%0A%20%20%20%20puts%20'hi'%0A%20%20end%0Aend%0A%0Aclass%20B%20%3C%20A%0A%20%20alias_method%20%3Anew_foo%2C%20%3Afoo%0Aend%0A%0AB.new.new_foo

**Comment by jez** [comment]
Duplicate of https://github.com/sorbet/sorbet/issues/2378#issuecomment-567739010
