### ISSUE TITLE
Method in dynamic class definition incorrectly applied to unrelated class

### ISSUE THREAD

**Issue by jimmycuadra** [sorbet/sorbet#2341]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aa%20%3D%20Class.new%20do%0A%20%20def%20initialize(x%2C%20y)%0A%20%20end%0Aend%0A%0Aclass%20B%0Aend%0A%0Adef%20main%0A%20%20B.new%0Aend)

```ruby
# typed: true
a = Class.new do
  def initialize(x, y)
  end
end

class B
end

def main
  B.new
end
```

#### Observed output

```
editor.rb:11: Not enough arguments provided for method Object#initialize. Expected: 2, got: 0 https://srb.help/7004
    11 |  B.new
          ^^^^^
    editor.rb:3: Object#initialize defined here
     3 |  def initialize(x, y)
          ^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

The input should result in no errors from Sorbet.

- - -

This only happens when the result of the dynamic class is assigned to a non-constant value. To illustrate this, if you change the variable `a` in the example code to the constant `A`, the error goes away.

The example code in this issue is a reduced demonstration of the problem I ran into when trying to adopt Sorbet in a real project. Here is the real error:

```
$ srb
lib/lita/configuration_builder.rb:202: Not enough arguments provided for method Object#initialize. Expected: 1..2, got: 0 https://srb.help/7004
     202 |      nested_object = Configuration.new
                                ^^^^^^^^^^^^^^^^^
    spec/lita/handler/http_router_spec.rb:130: Object#initialize defined here
     130 |      def initialize(app, use_header = false, &block)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

With the referenced code available here:

* Call site: https://github.com/litaio/lita/blob/964a827c0b99f742ddbcd143b178e79c59aed56a/lib/lita/configuration_builder.rb#L201
* Incorrectly applied method definition: https://github.com/litaio/lita/blob/964a827c0b99f742ddbcd143b178e79c59aed56a/spec/lita/handler/http_router_spec.rb#L129

**Comment by jez** [comment]
Thanks for reporting this.

This behavior is unlikely to change soon.

Sorbet does not in general understand that `Class.new` modifies the class hierarchy, because it's frequently impossible to know how it will do so without running the code. The suggestion is to not use `Class.new`.

When that is not possible, Sorbet has limited support for understanding how `Class.new` works when the result is assigned to a constant. For example:

```ruby
A = Class.new {}
```

Making that change makes your example have zero errors.

When that is not possible, the suggestion is to move the `Class.new` into a file that is marked `typed: ignore`. This will completely hide it from Sorbet's perspective. That action is viral; if a `typed: ignore` file contained any definitions that were required for **any other part** of the codebase to type check, you'll have to silence / work around those errors, transitively. `typed: ignore` is a last resort.

Thanks again for reporting this, but unfortunately Sorbet has no real intention of supporting stuff like this any time soon.
