### ISSUE TITLE
`Module#name` is not resolved

### ISSUE THREAD

**Issue by jimmycuadra** [sorbet/sorbet#2342]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Foo%0A%20%20def%20my_name%0A%20%20%20%20name%0A%20%20end%0Aend)

```ruby
# typed: true
module Foo
  def my_name
    name
  end
end
```

#### Observed output

```
editor.rb:4: Method name does not exist on Foo https://srb.help/7003
     4 |    name
            ^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/module.rbi#L1121: Did you mean: Module#name?
    1121 |  def name(); end
            ^^^^^^^^^^
Errors: 1
```

#### Expected behavior

The input should successfully type check.

- - -

For some reason Sorbet is not detecting the `name` method from `Module`, even though [it's already in the relevant RBI file](https://github.com/sorbet/sorbet/blob/d306af25e64be0fc52205fdbf7f768a828cf7a20/rbi/core/module.rbi#L1121). Since the source of the method is `Module` itself, it cannot simply be included manually as per [7003](https://sorbet.org/docs/error-reference#7003).

**Comment by jez** [comment]
This is working as expected. Sorbet makes no assumptions about what context a module is included into. In particular, if your module is `extend`ed instead of being `include`d`, it will be a runtime error:

```ruby
# typed: true

module Foo
  def my_name
    name
  end
end

class MyClass
  include Foo
end

MyClass.new.my_name
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amodule%20Foo%0A%20%20def%20my_name%0A%20%20%20%20name%0A%20%20end%0Aend%0A%0Aclass%20MyClass%0A%20%20include%20Foo%0Aend%0A%0AMyClass.new.my_name)

```
Traceback (most recent call last):
        1: from foo.rb:13:in `<main>'
foo.rb:5:in `my_name': undefined local variable or method `name' for #<MyClass:0x00007ffbd207e9c0> (NameError)
```

The Sorbet error and the runtime error match.
