### ISSUE TITLE
Incorrect signature for Exception#initialize

### ISSUE THREAD

**Issue by manhhung741** [sorbet/sorbet#2382]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0AStandardError.new(%3Aa_symbol))

```ruby
# typed: true

StandardError.new(:a_symbol)
```

#### Observed output

```
editor.rb:3: Expected T.nilable(String) but found Symbol(:"a_symbol") for argument arg0 https://srb.help/7002
     3 |StandardError.new(:a_symbol)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/exception.rbi#L172: Method Exception#initialize has specified arg0 as T.nilable(String)
     172 |        arg0: T.any(String, NilClass),
                  ^^^^
  Got Symbol(:"a_symbol") originating from:
    editor.rb:3:
     3 |StandardError.new(:a_symbol)
                          ^^^^^^^^^
Errors: 1
```

#### Expected behavior

```
irb(main):041:0> StandardError.new(:asdf)
=> #<StandardError: asdf>
```

- - -

**Comment by manhhung741** [comment]
I suspect there is an implicit string conversion. The solution may be just that: changing the sig to accept T.nilable(String, Symbol).

**Comment by aisamanra** [comment]
`Exception#initialize` technically accepts anything that implements `to_s`, so it's arguably an even broader type than that:
```
irb(main):001:0> Exception.new(5)
=> #<Exception: 5>
irb(main):002:0> Exception.new(true)
=> #<Exception: true>
irb(main):003:0> Exception.new(->(x) { x + 1 })
=> #<Exception: #<Proc:0x00007fc32f952438@(irb):3 (lambda)>>
```
I don't think we necessarily want to allow all of those, though: even though Ruby would _accept_ them at runtime, I think many programmers (myself included!) would want to be warned if I was accidentally passing a lambda instead of something more sensible to `Exception.new`.

**Comment by jez** [comment]
https://sorbet.org/docs/faq#it-looks-like-sorbet-s-types-for-the-stdlib-are-wrong
