### ISSUE TITLE
passing generics to functions that has optional & kwargs causes a crash

### ISSUE THREAD

**Issue by DarkDimius** [sorbet/sorbet#25]
This likely should be a user-facing error.

Given

```

[1] pry(main)> class S
[1] pry(main)*   def self.has_kwarg(value, foo = 1, baz: 2)
[1] pry(main)*     puts "value: #{value}, path: #{path}"
[1] pry(main)*   end
[1] pry(main)* end
=> :has_kwarg
[2] pry(main)> class S
[2] pry(main)*   def self.has_kwarg(value, foo = 1, baz: 2)
[2] pry(main)*     puts "value: #{value}, foo: #{foo}, baz: #{baz}"
[2] pry(main)*   end
[2] pry(main)* end
=> :has_kwarg
[4] pry(main)> S.has_kwarg(1, {baz:3})
value: 1, foo: 1, baz: 3
=> nil
[5] pry(main)> S.has_kwarg(1, {bar:3})
ArgumentError: unknown keyword: bar
from (pry):7:in `has_kwarg'
[6] pry(main)> S.has_kwarg(1, 's')
value: 1, foo: s, baz: 2
=> nil

```

what should 

```

class C
  extend T::Generic
  A = type_member
  sig {params(value:A).void}
  def dd(value)
    S.has_kwarg(1, value)
  end
end

```

do?

Originally reported by @dmitry-stripe at https://jira.corp.stripe.com/browse/RUBYPLAT-1543

**Comment by jez** [comment]
I think this is a simple problem of `has_kwarg` not having a sig. Without a signature, Sorbet simply binds `value` to `foo`, which is allowed since `foo` is `T.untyped` in the absence of a sig.

Adding a sig makes the expected error appear:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20S%0A%20%20extend%20T%3A%3ASig%0A%20%20sig%20%7Bparams%28value%3A%20Integer%2C%20foo%3A%20Integer%2C%20baz%3A%20Integer%29.void%7D%0A%20%20def%20self.has_kwarg%28value%2C%20foo%20%3D%201%2C%20baz%3A%202%29%0A%20%20end%0Aend%0A%0Aclass%20C%0A%20%20extend%20T%3A%3ASig%0A%20%20extend%20T%3A%3AGeneric%0A%20%20A%20%3D%20type_member%0A%20%20sig%20%7Bparams%28value%3A%20A%29.void%7D%0A%20%20def%20dd%28value%29%0A%20%20%20%20S.has_kwarg%281%2C%20value%29%0A%20%20end%0Aend)

```ruby
# typed: true

class S
  extend T::Sig
  sig {params(value: Integer, foo: Integer, baz: Integer).void}
  def self.has_kwarg(value, foo = 1, baz: 2)
  end
end

class C
  extend T::Sig
  extend T::Generic
  A = type_member
  sig {params(value: A).void}
  def dd(value)
    S.has_kwarg(1, value)
  end
end
```

#### Observed output

```
editor.rb:16: Expected Integer but found C::A for argument foo https://srb.help/7002
    16 |    S.has_kwarg(1, value)
                           ^^^^^
  Expected Integer for argument foo of method S.has_kwarg:
    editor.rb:5:
     5 |  sig {params(value: Integer, foo: Integer, baz: Integer).void}
                                      ^^^
  Got C::A originating from:
    editor.rb:15:
    15 |  def dd(value)
                 ^^^^^
Errors: 1
```
