### ISSUE TITLE
Support typing with interfaces (structural subtyping aka static duck typing)

### ISSUE THREAD

**Issue by ric2b** [sorbet/sorbet#2582]
### Problem

Ruby often makes use of duck-typing. Sorbet currently has no support for duck-typing.

### Proposed solution

Since using `responds_to?` is to limited ([explanation here](https://github.com/sorbet/sorbet/issues/983#issuecomment-504703140)) I suggest something like [Python's Protocols](https://www.python.org/dev/peps/pep-0544/), so that you can add signatures to the methods you expect to receive.

Essentially sorbet would check that the typed variable both had the methods defined by the protocol/interface and that their signatures matched/were compatible.

**Comment by DarkDimius** [comment]
We don't have plans to support this feature at the time. We have discovered that migration to _intentional_ nominal types is useful on its own, as it allows to share a vocabulary of types, for both users and machines.

If you insist that you want them, have a look on https://github.com/tupl-tufts/rdl as alternative coming from research.

**Comment by anujbiyani** [comment]
@DarkDimius I think there's a valid use case for supporting duck-typing while also retaining intentional nominal types:
We like to use the [provider pattern](https://en.wikipedia.org/wiki/Provider_model) in my company so that we can swap between different third parties that meet the same need (e.g. different companies that all send text messages to users). In our Typescript code we create an interface that represents all of the behavior we need an SMS service to supply, and then each SMS provider class implements that interface.

The return type that most of the codebase interacts with is that interface, so now the application is divorced from the specific SMS provider.

In Sorbet it'd be nice to do something similar: define an intentional type that represents the set of behavior we want to do, and say that this method returns that type. Then the implementation could return any provider that matches that interface.

That gives us a shared vocabulary that is also not tied to the third party.

Does that sound reasonable? Or is there already a way to do this within Sorbet?
