### ISSUE TITLE
Resolved intersection type looks wrong when one of the types is a union

### ISSUE THREAD

**Issue by marianosimone** [sorbet/sorbet#2699]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20I1%0A%20%20def%20i1%3B%20end%0Aend%0A%0Aclass%20A%0A%20%20include%20I1%0Aend%0A%0Aclass%20B%0A%20%20include%20I1%0Aend%0A%0Asig%20%7Bparams(x%3A%20T.all(I1%2C%20T.any(A%2C%20B))).void%7D%0Adef%20foo(x)%0A%20%20T.reveal_type(x)%0Aend)

```ruby
# typed: true
extend T::Sig

module I1
  def i1; end
end

class A
  include I1
end

class B
  include I1
end

sig {params(x: T.all(I1, T.any(A, B))).void}
def foo(x)
  T.reveal_type(x)
end
```

#### Observed output

```
Revealed type: T.any(A, B)
```

#### Expected behavior

```
Revealed type: T.all(I1, T.any(A, B))
```

**Comment by aisamanra** [comment]
This is expected behavior. The reason that the output here is `T.any(A, B)` instead of `T.all(I1, T.any(A, B))` is that both `A` and `B` already include `I1`, so the `I1` part is redundant: every value of `A` or `B` is already also an `I1`, so Sorbet simplifies it away. If either `A` or `B` didn't include `I1`, then it wouldn't be redundant, and you'd see the whole type. For example:

```ruby
# typed: true
extend T::Sig

module I1
  def i1; end
end

class A
end

class B
  include I1
end

sig {params(x: T.all(I1, T.any(A, B))).void}
def foo(x)
  T.reveal_type(x)  # Revealed type: T.all(I1, T.any(A, B))
end
```

[→ view on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Amodule%20I1%0A%20%20def%20i1%3B%20end%0Aend%0A%0Aclass%20A%0Aend%0A%0Aclass%20B%0A%20%20include%20I1%0Aend%0A%0Asig%20%7Bparams(x%3A%20T.all(I1%2C%20T.any(A%2C%20B))).void%7D%0Adef%20foo(x)%0A%20%20T.reveal_type(x)%0Aend%0A)

This kind of simplification isn't unique to `T.all` and shows up with just `T.any` types, too: for example, even though the declared parameter type here is `T.any(A, B)`, Sorbet knows that every `B` is also necessarily an `A`, so the revealed type is just `A`:

```ruby
# typed: true
extend T::Sig
class A; end
class B < A; end

sig{params(x: T.any(A, B)).void}
def foo(x)
  T.reveal_type(x) # Revealed type: A
end
```

[→ view on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0Aclass%20A%3B%20end%0Aclass%20B%20%3C%20A%3B%20end%0A%0Asig%7Bparams(x%3A%20T.any(A%2C%20B)).void%7D%0Adef%20foo(x)%0A%20%20T.reveal_type(x)%0Aend%0A)
