### ISSUE TITLE
Option to skip certain lines or support for undefined constants?

### ISSUE THREAD

**Issue by bencgreenberg** [sorbet/sorbet#3209]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%23%20frozen_string_literal%3A%20true%0A%0Alogger%20%3D%20(defined%3F(Rails.logger)%20%26%26%20Rails.logger)%20%7C%7C%20STDOUT)

```ruby
# typed: strict
# frozen_string_literal: true

logger = (defined?(Rails.logger) && Rails.logger) || STDOUT
```

#### Observed output

```
editor.rb:4: Unable to resolve constant Rails https://srb.help/5002
     4 |logger = (defined?(Rails.logger) && Rails.logger) || STDOUT
                                            ^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:4: Replace with T::Props::Utils
     4 |logger = (defined?(Rails.logger) && Rails.logger) || STDOUT
                                            ^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:4: Replace with T::Utils
     4 |logger = (defined?(Rails.logger) && Rails.logger) || STDOUT
                                            ^^^^^
  Autocorrect: Use `-a` to autocorrect
    editor.rb:4: Replace with WEBrick::Utils
     4 |logger = (defined?(Rails.logger) && Rails.logger) || STDOUT
                                            ^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/sorbet/tprops.rbi#L95: Did you mean: T::Props::Utils?
    95 |module T::Props::Utils
        ^^^^^^^^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/sorbet/t.rbi#L152: Did you mean: T::Utils?
     152 |module T::Utils
          ^^^^^^^^^^^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/stdlib/webrick.rbi#L3350: Did you mean: WEBrick::Utils?
    3350 |module WEBrick::Utils
          ^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

I would expect not to raise an error if I was able to add a way to skip that line or an allowlist of constants.

**Comment by paracycle** [comment]
You can always shim a definition of `Rails` in an RBI file like:
```ruby
# typed: true

module Rails
  def logger; end
end
```

That would allow your code to be typechecked by telling Sorbet about the `Rails` constant as much as it needs to know about it.

**Comment by benhayehudi** [comment]
> You can always shim a definition of `Rails` in an RBI file like:
> 
> ```ruby
> # typed: true
> 
> module Rails
>   def logger; end
> end
> ```
> 
> That would allow your code to be typechecked by telling Sorbet about the `Rails` constant as much as it needs to know about it.

Thanks for responding, I appreciate it. 

While the solution above does work, with the slight modification that it should be `self.logger`, it feels more like a workaround than a long-term solution. What I mean by that is a common use case for the tools we create to be used in both a Rails application and outside of a Rails application. As such, we often have checks like the above in our gems to determine where the application is being run from, and act accordingly. I would have imagined a better way to tell Sorbet about this behavior than to generate an empty RBI file, which seems like a bit of additional weight without must benefit. 

Thanks again for lending a hand!

**Comment by jez** [comment]
Sorbet does not support ignore comments, intentionally. I have written about that elsewhere[1].

Sorbet is by-and-large designed for projects that are large and applications (not libraries). Large projects are multi-file, where adding "one more RBI file" isn't a burden. Applications have pinned dependencies, unlike libraries where the libraries are chosen by the user. That's why I'm thinking we're probably not going to invest in some sort of special-purpose solution.

There is already a workaround for the situation you mention:

https://sorbet.run/#%23%20typed%3A%20strict%0A%23%20frozen_string_literal%3A%20true%0A%0Alogger%20%3D%20STDOUT%0Arails%20%3D%20const_defined%3F(%3ARails)%20%26%26%20const_get(%3ARails)%0Alogger%20%3D%20if%20rails.respond_to%3F(%3Alogger)%20then%20rails.logger%20else%20STDOUT%20end

which is basically to use `const_get`.

[1] https://blog.jez.io/sorbet-fixme-comment/
