### ISSUE TITLE
Option to disable `Method X does not exist on module Y` (5023)

### ISSUE THREAD

**Issue by snitko** [sorbet/sorbet#3315]
Here's the code that fails the static check, yet is perfectly valid in Ruby:

```
module A
  def foo
    self.bar
  end
end

module B
  def bar;end
end

class C
  include A
  include B
end
```

Reading https://sorbet.org/docs/error-reference#5023 I understand that the solution is to define an empty `bar` method in `module A`, yet this seems excessive, especially when you have lots of those. I think there must be a way to disable this check on config altogether. Or, at the very least, have some sort of `must_be` statement as suggested here: https://github.com/sorbet/sorbet/issues/2236

**Comment by paracycle** [comment]
I would argue that the above is very unsafe Ruby since if you do:
```ruby
class D
  include A
end

D.new.foo #=> this raises an exception
```

There are no guarantees that people will not do that with the module `A`, so Sorbet is actually preventing you from making that mistake. After all, that is the job of the type checker.

What is really missing from Ruby (and from Sorbet) is a way for `A` to declare that it expects the module `B` to also be included wherever `A` is included. If that existed, this whole thing would have been type-safe, but as it stands, it is not.

**Comment by jez** [comment]
Thanks for the feedback, but I don't think we're going to implement this feature.

The feature that paracycle mentions has been implemented as `requires_ancestor` if you'd like to use it (currently experimental).
