### ISSUE TITLE
sig{void} returns T::Private::Types::Void::VOID to the class end-user 

### ISSUE THREAD

**Issue by grzegorz-jakubiak** [sorbet/sorbet#3343]
#### Input

With this dummy example you can see that calling `A.new.bar` or `main` result in returning `T::Private::Types::Void::VOID` to a class end-user.

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer).void%7D%0A%20%20def%20bar(x)%0A%20%20%20%20x.to_s%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20A.new.bar(91)%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: Integer).void}
  def bar(x)
    x.to_s
  end
end

def main
  A.new.bar(91)
end
```

#### Observed output

When running main method

```
irb(main):020:0> main
=> T::Private::Types::Void::VOID
```

#### Expected behavior

```
irb(main):020:0> main
=> nil
```

In my opinion this looks strange and from what I read it's because of `sorbet-runtime`. Is there a way to disable it? I'm working on a gem and I don't want my end-users to see sth like this especially when there is `Private` in it.
- - -

**Comment by paracycle** [comment]
I disagree that the expected behaviour is:
```
irb(main):020:0> main
=> nil
```
since that would mean `main` returns something that has a type of `NilClass`, which, in turn means that `A.new.bar` returns something that has a type of `NilClass`. But the sig of `bar` says that it does not return anything, so the return value is a `VOID` type. Since Ruby does not have a `VOID` type, Sorbet has to supply its own.

If you are building a gem and the gem has a runtime dependency on `sorbet-runtime`, then the consumers of your gem will also have a runtime dependency on `sorbet-runtime` as well. Thus, end-users could get exposed to Sorbet types, like in this case, since now it is one of their dependencies. I don't think you can get around that.

**Comment by grzegorz-jakubiak** [comment]
I see what you mean and now I'm actually getting it. I'm just a bit of concern of `Private` in the namespace shouldn't this type be just `T::VOID`?

**Comment by paracycle** [comment]
Not the author of the code, but as far as I understand, the constant is in a private namespace since the `sorbet-runtime` library does not want any user code to be returning/accepting that explicit type, except for the cases where it is implied by a `.void` return.

Basically, the implementation and the type of `Void` is an internal `sorbet-runtime` concern that does not need to be public outside the library.

**Comment by grzegorz-jakubiak** [comment]
fair enough! then I reckon this issue can be closed!
