### ISSUE TITLE
runtime checks on T::Array are incorrect (and do not match static checks)

### ISSUE THREAD

**Issue by hudon** [sorbet/sorbet#3389]
#### Input

Sorbet.run: https://sorbet.run/#%23%20typed%3A%20true%0AT.let(%5B%22foo%22%5D%2C%20T%3A%3AArray%5BInteger%5D)

```ruby
x = T.let(["foo"], T::Array[Integer])
```

#### Observed output

```
editor.rb:2: Argument does not have asserted type T::Array[Integer] https://srb.help/7007
     2 |x = T.let(["foo"], T::Array[Integer])
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  Got [String("foo")] originating from:
    editor.rb:2:
     2 |x = T.let(["foo"], T::Array[Integer])
                  ^^^^^^^
Errors: 1
```

`sorbet-runtime` behavior does not raise any exception and instead considers the invalid cast as valid:

```
irb(main):001:0> T.let(["foo"], T::Array[Integer])
=> ["foo"]
```

#### Expected behavior

I am expecting the runtime behavior to raise an exception, like so:

```
irb(main):002:0> T.let(["foo"], T::Array[Integer])
Traceback (most recent call last):
        1: from (irb):2
TypeError (T.let: Expected type T::Array[Integer], got T::Array[String])
Caller: (irb):2
```

This was the case in `sorbet-runtime` 0.5.5820, but seems to have regressed somewhere along the way to 0.5880

```
✗ ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
```

**Comment by aisamanra** [comment]
This was [a deliberate change to the way the runtime worked](https://github.com/sorbet/sorbet/pull/3293) and is [mentioned in the documentation on this page](https://sorbet.org/docs/stdlib-generics). Doing runtime type-checking on all the elements of arrays was a common and hard-to-pin-down source of performance problems for many Sorbet users (c.f. [the benchmarking done here](https://github.com/bbuchalter/sorbet_sig_performance#benchmarks)), so we decided instead to remove this feature from the runtime to avoid hidden gotchas.

If you want to have runtime type-checking of the elements inside arrays, a good way to do so is to write your code so that you type-check the individual elements, e.g.
```
["foo"].each do |elem|
  elem = T.let(elem, Integer)
  # do something with `elem`
end
```
which will continue to work in the way you expect, but without accidentally introducing slowdowns whenever you pass around a ten-thousand-element array.

**Comment by hudon** [comment]
Thank you so much for the detailed response.
