### ISSUE TITLE
Got T.nilable when T::Boolean expected

### ISSUE THREAD

**Issue by novokshonovp** [sorbet/sorbet#3429]
#### Input

[→ View on sorbet.run](TODO_replace_this_with_your_sorbet_run_link)

```ruby
# typed: true

class SrbTest
  extend T::Sig

  sig { returns(T::Boolean) }
  def call
    [true, false].sample
  end
end
```

#### Observed output

```
editor.rb:9: Returning value that does not conform to method result type https://srb.help/7005
     9 |    [true, false].sample
            ^^^^^^^^^^^^^^^^^^^^
  Expected T::Boolean
    editor.rb:8: Method call has return type T::Boolean
     8 |  def call
          ^^^^^^^^
  Got T.nilable(T.any(TrueClass, FalseClass, T::Array[T::Boolean])) originating from:
    editor.rb:9:
     9 |    [true, false].sample
            ^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior
No errors.

The example call function expectations are strictly true/false why the sorbet shows a nilable (T.nilable(T::Array[T::Boolean]))?

**Comment by paracycle** [comment]
This is the expected behaviour of Sorbet, since the definition of `Array#sample` is overloaded. `Array#sample` can return `nil`, a single value or an array of values depending on the parameters supplied to the `sample` method:

```ruby
> [].sample
=> nil
> [1, 2, 3].sample
=> 1
> [1, 2, 3].sample(2)
=> [3, 1]
```

There is no way for Sorbet to statically know which one of these types will be returned, so the return result is the most general it can be.

The documentation and signature for the method can be seen here: https://github.com/sorbet/sorbet/blob/master/rbi/core/array.rbi/#L2184-L2212
