### ISSUE TITLE
Autogenerated rbi file for a gem module not being recognized

### ISSUE THREAD

**Issue by xcskier56** [sorbet/sorbet#3448]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Amodule%20Delayed%0Aend%0Amodule%20Delayed%3A%3ARecurringJob%0A%20%20%23%20...%0Aend%0Amodule%20Delayed%3A%3ARecurringJob%3A%3AClassMethods%0A%20%20def%20run_at(*times)%3B%20end%0A%20%20def%20timezone(zone%20%3D%20nil)%3B%20end%0Aend%0A%0A%23%20typed%3A%20strict%0A%0A%23%20lib%2Frecurring_jobs%2Fmy_job%0Amodule%20RecurringJobs%0A%20%20class%20MyJob%0A%20%20%20%20extend%20T%3A%3ASig%0A%20%20%20%20include%20Delayed%3A%3ARecurringJob%0A%0A%20%20%20%20run_at%20'12%3A00am'%0A%20%20%20%20timezone%20'US%2FCentral'%0A%0A%20%20%20%20sig%20%7B%20void%20%7D%0A%20%20%20%20def%20perform%0A%20%20%20%20%20%20%23%20...%0A%20%20%20%20end%0A%20%20end%0Aend%0A)

```ruby
# /sorbet/rbi/gems/delayed_job_recurring.rbi

# typed: strict
module Delayed
end
module Delayed::RecurringJob
  # ...
end
module Delayed::RecurringJob::ClassMethods
  # ...
  def run_at(*times); end
  def timezone(zone = nil); end
end
```

```ruby
# typed: strict

# lib/recurring_jobs/my_job
module RecurringJobs
  class MyJob
    extend T::Sig
    include Delayed::RecurringJob

    run_at '12:00am'
    timezone 'US/Central'

    sig { void }
    def perform
      # ...
    end
  end
end
```

#### Observed output

```
editor.rb:20: Method run_at does not exist on T.class_of(RecurringJobs::MyJob) https://srb.help/7003
    20 |    run_at '12:00am'
            ^^^^^^^^^^^^^^^^

editor.rb:21: Method timezone does not exist on T.class_of(RecurringJobs::MyJob) https://srb.help/7003
    21 |    timezone 'US/Central'
            ^^^^^^^^^^^^^^^^^^^^^
Errors: 2
```

#### Expected behavior

The gem's rbi file was generated with `srb rbi gems`. I would expect that it would properly pick up on that `include Delayed::RecurringJob` adds the appropriate methods to the `MyJob` class and passes `srb tc` but it doesn't

**Comment by paracycle** [comment]
The problem in this case is that `include Delayed::RecurringJob` on its own does not pull in `run_at` nor `timezone` as class methods. `include` can only add instance methods from the included module. That's why there is a separate `Delayed::RecurringJob::ClassMethods` module, which gets included to the singleton class of your `RecurringJobs::MyJob` class when the `include Delayed::RecurringJob` is ran.

The way to model that with Sorbet is to use the `mixes_in_class_methods` method so that `Delayed::RecurringJob` can say that is mixes in class methods from `Delayed::RecurringJob::ClassMethods`. Refer to the documentation of that method: https://sorbet.org/docs/abstract#interfaces-and-the-included-hook

Now, the problem is that it is super hard to infer that this is happening from the runtime behaviour of types so that the RBI generator can generate that annotation for you. That's why the `srb` gem RBI generator does not attempt it. https://github.com/Shopify/tapioca is an alternative gem RBI generator that aims to do that as well; you might have better luck using that instead.

If you want a quick fix, though, it is as simple as adding a manual RBI file in your codebase that says:
```ruby
# typed: true

module Delayed::RecurringJob
  mixes_in_class_methods(ClassMethods)
end
```

**Comment by xcskier56** [comment]
@paracycle, thank you for the quick answer and great explanation. I think this somewhat from my incomplete understanding of Ruby loading, as well as an assumption that because the modules were in the RBI file that they would be loaded. Is there any interest in adding a section to the documentation for `srb rbi gems` that maybe warns users of this potential issue and the quick fix? I'd be happy to help.

**Comment by paracycle** [comment]
@xcskier56 Not a problem, happy to help. I'll defer your documentation question to @jez.
