### ISSUE TITLE
Add implements alias for include

### ISSUE THREAD

**Issue by doodzik** [sorbet/sorbet#3578]
### Problem

We ran into an issue at Shopify, where including an interface in a class is ambiguous if it is an interface or a normal Module. This issue isn’t a big thing, but it makes it a little bit harder to understand the intention behind the code and makes it harder to maintain.

```ruby
class A
  include B
  include C # Is this an interface or a regular module
end
```

### Proposed solution

We thought that adding an alias for `include` would help communicate that we are including an interface.
Using a dedicated keyword makes it easy to scan the file and clearly communicates the intentions.

```ruby
class A
  implements B
  include C
end
```
 
We could potentially suffix an Interface with `Interface` to communicate the same thing, but that is an anti-pattern that we would not like to do.

**Comment by jez** [comment]
This would come with a monkey patch of `Module` and potentially collide with other methods that people have defined called `implements`.

We've discussed this in the past and generally come to the conclusion that the sugar is not worth it (it's one more thing for people to learn on top of vanilla Ruby. Imagine a conversation with a new team member:

"what's the difference between `include` and `implements`?"

"nothing." 

"When should I use one or the other?"

"Use implements with interfaces"

"Is that machine checked?"

"No, because it would be a breaking change in old code."

I think there's a very small upside here (syntactic sugar) at the cost of making it unclear what the preferred way of doing things is.

**Comment by jez** [comment]
Thanks for the feature request. It seems like this feature adds more confusion for new users of Sorbet than it solves. Going to close it for now.
