### ISSUE TITLE
sorbet-runtime fails to consume sig for respond_to_missing

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#3939]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0A%0Arequire_relative%20'.%2Fgems%2Fsorbet-runtime%2Flib%2Fsorbet-runtime'%0A%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(m%3A%20Symbol%2C%20include_private%3A%20T%3A%3ABoolean).returns(T%3A%3ABoolean)%7D%0A%20%20def%20respond_to_missing%3F(m%2C%20include_private%3Dfalse)%0A%20%20%20%20true%0A%20%20end%0Aend%0A%0AA.new.respond_to%3F(%3Afoo))

```ruby
# typed: strict

require_relative './gems/sorbet-runtime/lib/sorbet-runtime'

class A
  extend T::Sig

  sig {params(m: Symbol, include_private: T::Boolean).returns(T::Boolean)}
  def respond_to_missing?(m, include_private=false)
    true
  end
end

A.new.respond_to?(:foo)

```

#### Observed output

This is a bug in the runtime.

```
Traceback (most recent call last):
        12: from foo.rb:13:in `<main>'
        11: from foo.rb:13:in `respond_to?'
        10: from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:212:in `block in _on_method_added'
         9: from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:373:in `maybe_run_sig_block_for_method'
         8: from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:377:in `maybe_run_sig_block_for_key'
         7: from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:397:in `run_sig_block_for_key'
         6: from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:203:in `block in _on_method_added'
         5: from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:298:in `run_sig'
         4: from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/_methods.rb:341:in `build_sig'
         3: from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/signature_validation.rb:39:in `validate'
         2: from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/signature.rb:18:in `new_untyped'
         1: from /Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/signature.rb:18:in `new'
/Users/jez/stripe/sorbet/gems/sorbet-runtime/lib/types/private/methods/signature.rb:72:in `initialize': The declaration for `respond_to_missing?` has arguments with duplicate names (RuntimeError)
Reflection: [[:req], [:req]]
From sig:   {nil=>#<T::Private::Types::NotTyped:0x00007fcec78b4438>}
```

Note: those last two lines are two extra lines of debugging information I added. They are not printed on master at time of report.

#### Expected behavior

The sig provides types for all the arguments of the method, so there should be no error.

- - -

(repro courtesy of @damolina-stripe)

**Comment by froydnj** [comment]
This happens because we attempt to find a signature for `A#respond_to_missing?`'s `super` method:

https://github.com/sorbet/sorbet/blob/49e90fca13518a24f82de9e879f7a8e6cafea271/gems/sorbet-runtime/lib/types/private/methods/signature_validation.rb#L22-L44

 We don't find one, so we attempt to construct an untyped signature.  To construct that untyped signature, we take what `Kernel.method(:respond_to_missing?).parameters` tells us:

```
irb(main):001:0> Kernel.method(:respond_to_missing?).parameters
=> [[:req], [:req]]
```

and then we turn it into a hash for the arguments:

https://github.com/sorbet/sorbet/blob/49e90fca13518a24f82de9e879f7a8e6cafea271/gems/sorbet-runtime/lib/types/private/methods/signature.rb#L14-L16

but this process loses information about how many arguments we had, since `#parameters` indicated that we have two arguments with the same "name"...and then we hit the error from the original report.

I think this will happen when attempting to override any method that's written in C with more than one parameter, since we don't have appropriate parameter information for such methods.  But I would have suspected such problems to show up before now?

**Comment by jez** [comment]
Wow thanks for the investigation @froydnj! Nice find.
