### ISSUE TITLE
Could not find a valid gem 'sorbet-static' (= 0.5.5631) (required by 'sorbet' (= 0.5.5631)) in any repository

### ISSUE THREAD

**Issue by michelleheh** [sorbet/sorbet#3972]
#### Input

On MacOS Big Sur version 11.1

```bash
gem install sorbet -v 0.5.5631
```

#### Observed output

```bash
ERROR:  Could not find a valid gem 'sorbet-static' (= 0.5.5631) (required by 'sorbet' (= 0.5.5631)) in any repository
ERROR:  Possible alternatives: sorbet-static
```
#### Expected behavior
`gem install sorbet -v 0.5.5631` should succeed on Big Sur.

- - -
I suspect that older versions of `sorbet-static` is not available for `universal-darwin-20`.

When I install `gem install sorbet`, it actually succeeds:
```bash
gem install sorbet
Fetching sorbet-static-0.5.6267-universal-darwin-20.gem
Fetching sorbet-0.5.6267.gem
Successfully installed sorbet-static-0.5.6267-universal-darwin-20

  Thanks for installing Sorbet! To use it in your project, first run:

    bundle exec srb init

  which will get your project ready to use with Sorbet.
  After that whenever you want to typecheck your code, run:

    bundle exec srb tc

  For more docs see: https://sorbet.org/docs/adopting
Successfully installed sorbet-0.5.6267
Parsing documentation for sorbet-static-0.5.6267-universal-darwin-20
Installing ri documentation for sorbet-static-0.5.6267-universal-darwin-20
Parsing documentation for sorbet-0.5.6267
Installing ri documentation for sorbet-0.5.6267
Done installing documentation for sorbet-static, sorbet after 0 seconds
2 gems installed
```

**Comment by jez** [comment]
`0.5.5874` was the first version to publish a gem archive for universal-darwin-20

Sorbet only support HEAD, so we have no plans to update old gem versions.

If you want to hack around this, all `universal-darwin-*` binaries are identical.
Here are the lines in our CI where we use the same folder with a quick `sed` to make all the versions of macOS:

https://github.com/sorbet/sorbet/blob/d570e3bac6ccbc5e7678eeef00e8b7763b4a78f8/.buildkite/build-static-release.sh#L26-L43

You could unpack the universal-darwin-19 gem, sed 19 to 20 everywhere, and re-tar it up, and host the `*.gem` file somewhere.

Otherwise, i'd recommend upgrading. You're on a 9 month old sorbet version—we've made a lot of improvements since then.

**Comment by michelleheh** [comment]
Thank you, @jez, 🙏   for the lighting fast response that confirmed my suspicion and suggested workarounds.
