### ISSUE TITLE
Segfault with 0.5.6307

### ISSUE THREAD

**Issue by ashkulz** [sorbet/sorbet#4031]
#### Input

Not sure, this happens on the whole code-base and is a segfault. This doesn't occur with `0.5.6303` but does happen with `0.5.6307` -- so it's a recent regression.

#### Observed output

```
$ srb tc
Exception::raise(): ast/verifier/Verifier.cc:34 enforced condition methodDepth == 0 has failed: Found constant definition inside method definition

Backtrace:
  #3 0xeddb82 sorbet::ast::TreeMapper<>::mapIt()
  #4 0xedbc38 sorbet::ast::TreeMapper<>::mapIt()
  #5 0xede794 sorbet::ast::TreeMapper<>::mapBlock()
  #6 0xedcc62 sorbet::ast::TreeMapper<>::mapIt()
  #7 0xedc225 sorbet::ast::TreeMapper<>::mapIt()
  #8 0xedbf60 sorbet::ast::TreeMapper<>::mapIt()
  #9 0xedbf60 sorbet::ast::TreeMapper<>::mapIt()
  #10 0xedbf60 sorbet::ast::TreeMapper<>::mapIt()
  #11 0xeda92e sorbet::ast::TreeMap::apply<>()
  #12 0xeda885 sorbet::ast::Verifier::run()
  #13 0xe76b0d sorbet::rewriter::Rewriter::run()
  #14 0x8468ee sorbet::realmain::pipeline::indexOne()
  #15 0x862300 std::__1::__function::__func<>::operator()()
  #16 0x1157435 std::__1::__function::__func<>::operator()()
  #17 0x1156b13 std::__1::__function::__func<>::operator()()
  #18 0x11578b2 Joinable::trampoline()
  #19 0x7fd165a68fa3 start_thread
  #20 0x7fd1659944cf __clone

/usr/local/rvm/gems/ruby-2.5.8/gems/sorbet-0.5.6307/bin/srb: line 46:  3997 Segmentation fault      "${sorbet}" "${args[@]}"
```

#### Expected behavior

Shouldn't segfault, but raise an error.

**Comment by elliottt** [comment]
Are you using concerns in your codebase? If so, could you try building a debug build with 86d00f558dd2dd97400c4d4752b8e60e035fb32e reverted? It's the only commit in the range you mentioned that looks like it might trigger that enforce.

**Comment by KaanOzkan** [comment]
I believe this is due to my commit that @elliottt linked, however I was unable to reproduce the enforce failure and the segfault. Is it possible for you to add a debug statement and rerun typechecking on the application?

One useful statement would be adding:
`std::cout << original.showRaw(ctx) << std::endl;` 
Inside this if conditional https://github.com/sorbet/sorbet/blob/master/ast/verifier/Verifier.cc#L33.

From that output we should be able to see the constant being assigned and its value. That information should help you narrow down which statement is triggering the segfault.

**Comment by ashkulz** [comment]
It looks like one of the recent commits has fixed it, as I no longer get a segfault (just `No errors! Great job.`) with 0.5.6317 but still get the segfault with 0.5.6307. Thanks for the quick fix!

**Comment by ashkulz** [comment]
It's possible that the above was a red herring and the actual error was #4033.
