### ISSUE TITLE
Invalid unreachable code reported

### ISSUE THREAD

**Issue by kyku** [sorbet/sorbet#4080]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%7Bvoid%7D%0A%20%20def%20simple_operation%0A%20%20%20%20retried%20%3D%20false%0A%20%20%20%20begin%0A%20%20%20%20%20%20raise%20if%20rand%20%3C%200.5%0A%20%20%20%20%20%20puts%20%22passed%22%0A%20%20%20%20rescue%0A%20%20%20%20%20%20raise%20if%20retried%0A%20%20%20%20%20%20retried%20%3D%20true%0A%20%20%20%20%20%20retry%0A%20%20%20%20end%0A%20%20end%0Aend)

```ruby
# typed: strict
class A
  extend T::Sig

  sig{void}
  def simple_operation
    retried = false
    begin
      raise "xxx" if rand < 0.5
      puts "passed"
    rescue
      raise if retried
      retried = true
      retry
    end
  end
end
```

#### Observed output

```
editor.rb:12: This code is unreachable https://srb.help/7006
    12 |      raise if retried
              ^^^^^
    editor.rb:12: This condition was always falsy (FalseClass)
    12 |      raise if retried
                       ^^^^^^^
  Got FalseClass originating from:
    editor.rb:7:
     7 |    retried = false
                      ^^^^^
Errors: 1
```

#### Expected behavior

No errors should be reported for this sample.

- - -
Sorbet does not seem to take into account that variable retried is assigned the value of true and the block is rerun after the retry keyword.

**Comment by trevor-stripe** [comment]
This can be fixed by adding a type annotation to `retried`:

[sorbet.run link](https://sorbet.run/#%23%20typed%3A%20strict%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%7Bvoid%7D%0A%20%20def%20simple_operation%0A%20%20%20%20retried%20%3D%20T.let(false%2C%20T%3A%3ABoolean)%0A%20%20%20%20begin%0A%20%20%20%20%20%20raise%20if%20rand%20%3C%200.5%0A%20%20%20%20%20%20puts%20%22passed%22%0A%20%20%20%20rescue%0A%20%20%20%20%20%20raise%20if%20retried%0A%20%20%20%20%20%20retried%20%3D%20true%0A%20%20%20%20%20%20retry%0A%20%20%20%20end%0A%20%20end%0Aend)
```ruby
# typed: strict
class A
  extend T::Sig

  sig{void}
  def simple_operation
    retried = T.let(false, T::Boolean)
    begin
      raise if rand < 0.5
      puts "passed"
    rescue
      raise if retried
      retried = true
      retry
    end
  end
end
```

The issue here is that the type of `retried` is initially `FalseClass`, so when the rescue block is processed it looks like the `raise` will never happen.

**Comment by kyku** [comment]
Thanks for the tip!
