### ISSUE TITLE
Incorrect "unreachable code" error (sorbet 7006) for loop conditional on boolean switch

### ISSUE THREAD

**Issue by smackesey** [sorbet/sorbet#4174]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0As%20%3D%20false%0A2.times%20do%0A%20%20puts%20'ok'%20if%20s%0A%20%20s%20%3D%20true%0Aend%0A)

```ruby
s = false
2.times do
  puts 'ok' if s
  s = true
end
```

#### Observed output

```

# typed: true
extend T::Sig

s = false
2.times do
  puts 'ok' if s
  s = true
end
editor.rb:6: This code is unreachable https://srb.help/7006
     6 |  puts 'ok' if s
               ^^^^
    editor.rb:6: This condition was always falsy (FalseClass)
     6 |  puts 'ok' if s
                       ^
  Got FalseClass originating from:
    editor.rb:4:
     4 |s = false
            ^^^^^

editor.rb:7: Changing the type of a variable in a loop is not permitted https://srb.help/7001
     7 |  s = true
              ^^^^
  Existing variable has type: FalseClass
  Attempting to change type to: TrueClass

  Original type from:
    editor.rb:4:
     4 |s = false
            ^^^^^
    editor.rb:6:
     6 |  puts 'ok' if s
                       ^
Errors: 2 
```

#### Expected behavior

There should not be a `7006` error. It's just incorrect, the code is not unreachable. I understand why it says that, since it infers that s is always `false`. But still, claiming this is unreachable based on an aggressive inference seems inconsistent with Sorbet's philosophy of gradualism.

Might it make more sense to by default infer that locals assigned to `true`/`false` are `T::Boolean` rather than `TrueClass`/`FalseClass`?

- - -

The error goes away when you declare `s` with `s = T.let(false, T::Boolean)`.

**Comment by yob** [comment]
I think this might be a similar case, although it variable being checked is a Symbol rather than a boolean.

## Input
[→ View on sorbet.run](https://sorbet.run/#class%20Foo%0A%20%20extend%20T%3A%3ASig%0A%20%20%0A%20%20sig%20%7B%20params%28data%3A%20String%29.void%20%7D%0A%20%20def%20process_data%28data%29%0A%20%20%20%20mode%20%3D%20%3Anone%0A%20%20%20%20instructions%20%3D%20%5B%5D%0A%0A%20%20%20%20while%20token%20%3D%20random_method%0A%20%20%20%20%20%20if%20token%20%3D%3D%20%22beginbfchar%22%0A%20%20%20%20%20%20%20%20mode%20%3D%20%3Achar%0A%20%20%20%20%20%20%20%20instructions%20%3D%20%5B%5D%0A%20%20%20%20%20%20elsif%20token%20%3D%3D%20%22endbfchar%22%0A%20%20%20%20%20%20%20%20mode%20%3D%20%3Anone%0A%20%20%20%20%20%20elsif%20mode%20%3D%3D%20%3Achar%0A%20%20%20%20%20%20%20%20instructions%20%3C%3C%20token%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0A%0A%20%20sig%20%7B%20returns%28String%29%20%7D%0A%20%20def%20random_method%0A%20%20%20%20%5B%22beginbfchar%22%2C%20%22endbfchar%22%2C%20%22beginbfrange%22%2C%20%22endbfrange%22%2C%20%221%22%2C%20%222%22%5D.shuffle.first%20%7C%7C%20%22%22%0A%20%20end%0Aend)

```ruby
class Foo
  extend T::Sig
  
  sig { params(data: String).void }
  def process_data(data)
    mode = :none
    instructions = []

    while token = random_method
      if token == "beginbfchar"
        mode = :char
        instructions = []
      elsif token == "endbfchar"
        mode = :none
      elsif mode == :char
        instructions << token
      end
    end
  end

  sig { returns(String) }
  def random_method
    ["beginbfchar", "endbfchar", "beginbfrange", "endbfrange", "1", "2"].shuffle.first || ""
  end
end
```

Sorbet raises:

```
editor.rb:16: This code is unreachable https://srb.help/7006
    16 |        instructions << token
                ^^^^^^^^^^^^^^^^^^^^^
    editor.rb:15: This condition was always falsy (T::Boolean)
    15 |      elsif mode == :char
                    ^^^^^^^^^^^^^
  Got T::Boolean originating from:
    editor.rb:15:
    15 |      elsif mode == :char
                    ^^^^^^^^^^^^^
Errors: 1
```

Changing  to `mode = T.let(:none, Symbol)` makes the error go away, but unfortunately I'm working in a gem where sorbet isn't a runtime dependency so I can't use `T.let()`

**Comment by jez** [comment]
The example that yob mentions above is an example of #2348.

The example in the original issue request is actually behaving as expected.

Sorbet prohibits changing the type of a variable in a loop, requiring that variables must be explicitly widened before the loop in such cases.

There is more explanation here: https://sorbet.org/docs/error-reference#7001

Note that at one point we attempted to change this, to explicitly special case `true`/`false` to not participate in this widening decision (#4368) but we eventually closed that PR because we discovered that too much code relied on the current behavior (#4370).
