### ISSUE TITLE
Runtime affecting arity of attributes

### ISSUE THREAD

**Issue by gustavompo** [sorbet/sorbet#4216]
Similar to https://github.com/sorbet/sorbet/issues/2643 but for attributes
#### Input

```ruby
class Foo
  extend T::Sig

  sig {returns(Integer)}
  attr_accessor :with_accessor_sig

  sig {params(with_writer: Integer).returns(Integer)}
  attr_writer :with_writer_sig

  sig {returns(Integer)}
  attr_reader :with_reader_sig

  attr_accessor :with_accessor
  attr_writer :with_writer
  attr_reader :with_reader
end
```

#### Observed output

```
foo = Foo.new

foo.method(:with_accessor_sig).arity   # => -1
foo.method(:with_writer_sig=).arity    # => -1
foo.method(:with_reader_sig).arity     # => -1
```

#### Expected behavior

```
foo.method(:with_accessor).arity     # => 0
foo.method(:with_writer=).arity      # => 1
foo.method(:with_reader).arity       # => 0
```

- - -

Additional note: this is breaking the state_machine's audit_trail component when using a context attribute: 
https://github.com/state-machines/state_machines-audit_trail/blob/master/lib/state_machines/audit_trail/backend.rb#L71

**Comment by jez** [comment]
This is a known incompatibility, and we have no intention of fixing it.

If you absolutely must not change the arity of the method, you can provide a 100% static-only signature with `T::Sig::WithoutRuntime`:

https://sorbet.org/docs/runtime#tsigwithoutruntimesig

Otherwise, if you would like to retrieve the arity of the underlying method, you can use `signature_for_method`, discussed in the issue you linked:

https://github.com/sorbet/sorbet/issues/2643#issuecomment-585401936

If would like to use a monkey patch to get the behavior of always looking up the underlying method's arity, we provide one that you can enable like this:

https://github.com/sorbet/sorbet/blob/6b640d6aa9387f08c1ab7221ac551aa033488672/gems/sorbet-runtime/lib/types/compatibility_patches.rb#L52-L71

Hope that helps, and best of luck.
