### ISSUE TITLE
Unknown "Class is sealed and cannot be inherited" error 5050

### ISSUE THREAD

**Issue by yassinecc** [sorbet/sorbet#4220]
#### Input

I cannot reproduce the issue on sorbet.run

I can reproduce the issue in a file `app/lib/suit.rb`
```ruby
# typed: true
class Suit < T::Enum
  enums do
    Spades = new
    Hearts = new
  end
end
```

and run `bundle exec srb tc app/lib/suit.rb`

#### Observed output

```shell
./app/lib/suit.rb:2: Suit is sealed and cannot be inherited by Suit::Spades https://srb.help/5050
     2 |class Suit < T::Enum
              ^^^^
    ./app/lib/suit.rb:2: Suit was marked sealed and can only be inherited in this file
     2 |class Suit < T::Enum
        ^^^^^^^^^^^^^^^^^^^^

./app/lib/suit.rb:2: Suit is sealed and cannot be inherited by Suit::Hearts https://srb.help/5050
     2 |class Suit < T::Enum
              ^^^^
    ./app/lib/suit.rb:2: Suit was marked sealed and can only be inherited in this file
     2 |class Suit < T::Enum
        ^^^^^^^^^^^^^^^^^^^^

app/lib/suit.rb:2: Suit is sealed and cannot be inherited by Suit::Spades https://srb.help/5050
     2 |class Suit < T::Enum
              ^^^^
    ./app/lib/suit.rb:2: Suit was marked sealed and can only be inherited in this file
     2 |class Suit < T::Enum
        ^^^^^^^^^^^^^^^^^^^^

app/lib/suit.rb:2: Suit is sealed and cannot be inherited by Suit::Hearts https://srb.help/5050
     2 |class Suit < T::Enum
              ^^^^
    ./app/lib/suit.rb:2: Suit was marked sealed and can only be inherited in this file
     2 |class Suit < T::Enum
        ^^^^^^^^^^^^^^^^^^^^
Errors: 4
```

#### Expected behavior

Sorbet should not raise an error on example code cf. https://sorbet.org/docs/tenum, or at least point to a documented error code (5050 is not documented on srb.help). `bundle exec srb tc` does not return errors

- - -

Sorbet version
```shell
> bundle exec srb --version
Sorbet typechecker 0.5.5920 git b89eb263034e4b9754567c73e7983d0a87ffd34a debug_symbols=true clean=1
```

**Comment by jez** [comment]
It appears that you have a `sorbet/config` file in the current directory which includes something like `--dir=.`

That causes Sorbet to read files and give them names prefixed with `./`, like `./app/lib/suit.rb`.

You then also pass `app/lib/suit.rb` on the command line. In combination with `--dir=.`, this causes Sorbet to think that you are passing the file twice, as if you had written `sorbet ./app/lib/suit.rb app/lib/suit.rb`.

Sorbet does not attempt to strongly normalize file path names, because this is in general a problem with a lot of sharp edges.

You have some options:

- Don't do this. Sorbet is not designed to type check single files in isolation when working inside a whole project (in general, it doesn't make sense to type check a single file, because it might depend on any number of things in order to be able to type check, and Sorbet makes no attempt to track and type check those dependencies too).

  If you want to type check a single file in isolation, do it in its own project.

- Pass the `--no-config` flag to `srb tc`. This requests that Sorbet not read the contents of `sorbet/config`, so the only flags and files passed to Sorbet will be those provided at the command line.

- If for whatever reason you **really** want to pass this file at the command line (doesn't make sense, see two previous points), you can avoid these errors by passing the file name prefixed with `./` at the command line, like

  ```
  bundle exec srb tc ./app/lib/suit.rb
  ```

**Comment by yassinecc** [comment]
Thanks @jez I was able to work around my issue 👍
