### ISSUE TITLE
Include superclass when generating hidden definitions

### ISSUE THREAD

**Issue by dduugg** [sorbet/sorbet#4232]
### Problem

`srb rbi hidden-definitions` does not seem to include the parent class when writing out missing classes, e.g.:

https://github.com/dduugg/yard-sorbet/blob/433ea72/sorbet/rbi/hidden-definitions/hidden.rbi#L12195-L12202

This case required a commit to `sorbet-typed` to correct:

https://github.com/sorbet/sorbet-typed/pull/353/files

### Proposed solution

`srb rbi hidden-definitions` should write the parent class when writing classes out to `hidden.rbi`

**Comment by DarkDimius** [comment]
Context from past Sorbet team member(and l'm entirely comfortable with team choosing to do something else)

This was done because some classes have different superclass across ruby versions in stdlib. And thus this would have led to spurious errors for users. In addition, The idea was that hidden-definitions defines missing methods, rather than missing class definitions. At the time Sorbet was being introduced at Stripe, missing class definitions were already eliminated by predecessor system, thus we didn't have the problem with not listing classes.

**Comment by jez** [comment]
Going to close this in favor of Tapioca

https://sorbet.org/blog/2022/07/27/srb-tapioca
