### ISSUE TITLE
What's the status of Sorbet? 

### ISSUE THREAD

**Issue by peternixey** [sorbet/sorbet#4235]
Hi Guys,

I'm a huge fan of Sorbet but I'm also concerned about it's future. There are almost no comms from the core team about what's coming with it or what's changing - the last Tweet (rather than RT) that you sent out from the Sorbet account was last July. Your docs have been saying that VS Code support has been coming for over a year with no updates and there are only 80 questions labelled with Sorbet on StackOverflow. 

I can imagine that subsequent to the Ruby 3 announcements there is probably a lot of internal uncertainty but, as dedicated users of sorbet, it would really help us if you could give us an idea of what's happening and if you're going to continue. 

I take none of this for granted and am very grateful for your open source efforts, I thinkt he project is fantastic. But debugging it can also be a time sink and it would be great to know if we're backing the right horse. 

Are you going to continue with it and if so what can we expect to come out? If you're not then it would really help to know sooner rather than later so as to move to the Ruby RBI paradigm instead. 

Thank you!
Peter

**Comment by froydnj** [comment]
Thanks for using Sorbet and voicing your concerns.

We remain committed to Sorbet — you can see from the commit history that new stuff is landing fairly often.  Sorbet has reached almost 100% adoption at Stripe and is used actively not only by engineers, but also as a foundation for other tools. It addresses real use-cases and is not going anywhere, unless we find even better ways to address the same problems :wink: . It is true that the frequency of commits in this repo has decreased somewhat, but this is because Sorbet has reached its original goals at Stripe and we’re investing in tools that are built on top of Sorbet.  After these tools are successful at Stripe, they will probably be open sourced.

As for the VSCode extension, thousands of engineers inside Stripe use the extension every day.  We do not have a team dedicated to supporting the extension, however, and this is the primary blocker to releasing the extension.  There are also a few outstanding rough edges in the out-of-the-box experience at Stripe. We are aware that this is a hole in Sorbet’s story, we want to address it, but we are not sure when it’s going to reach the top of the priority list.  We’ll have a better idea once we review our upcoming work for the second half of 2021.

The same goes for e.g. Ruby 3 support.  Stripe’s codebase is on Ruby 2.7 and until we start moving to Ruby 3.x, other work takes priority.  We’re happy to review patches adding Ruby 3 features in the interim — similarly how other companies helped us add support for Ruby 2.5, 2.6, and 2.7 (Stripe remained on 2.4 for a pretty long time).

**Comment by peternixey** [comment]
Thanks so much for the response Nathan. It’s a great relief to hear that it’s still front and centre at Stripe as I’d be very sorry to part ways with it. And really, really looking forward to the VSCode extension! Thanks again for your great work 🙏🏻

**Comment by ianks** [comment]
is a team necessary to open source the extension? i, amongst others, would step up if it were open sourced.
