### ISSUE TITLE
RSpec `describe` nested inside a module triggers error 5067

### ISSUE THREAD

**Issue by Bo98** [sorbet/sorbet#4426]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0A%23%20Works%0Adescribe%20SomeModule%3A%3ASomeClass%20do%0Aend%0A%0A%23%20Doesn't%20work%0Amodule%20SomeOtherModule%0A%20%20describe%20SomeClass%20do%0A%20%20end%0Aend%0A)

```ruby
# typed: true

# Works
describe SomeModule::SomeClass do
end

# Doesn't work
module SomeOtherModule
  describe SomeClass do
  end
end
```

#### Observed output

```
editor.rb:9: The super class SomeOtherModule of SomeOtherModule::<describe 'SomeClass'> does not derive from Class https://srb.help/5067
     9 |  describe SomeClass do
    10 |  end
Errors: 1
```

#### Expected behavior

Error 5067 is not triggered.

- - -

**Comment by AlexEvanczuk** [comment]
I've identified the issue comes up in release 0.5.6500.

https://github.com/sorbet/sorbet/compare/0.5.6497.20210713212056-f7d542338...0.5.6500.20210714142733-b4e0f4e79

Best I can tell it comes from this PR https://github.com/sorbet/sorbet/pull/4360 authored by @elliottt . @elliottt would love your eyes on this! Right now this is blocking us from upgrading to the newest version of Sorbet 🙏 Happy to chat through the use case here.

**Comment by Bo98** [comment]
Basically, I think this:

https://github.com/sorbet/sorbet/blob/4f146522e25047f6527a98797672f9b1c462eced/rewriter/Minitest.cc#L283

should only happen on the condition that the `self` reference refers to a class. Minitest similarly checks if `Class === self`.
