### ISSUE TITLE
Gems marked as `require: false` are being loaded

### ISSUE THREAD

**Issue by jflinter** [sorbet/sorbet#4814]
#### Input

- Start a new project with the following Gemfile:
```rb
source 'https://rubygems.org'

gem 'sorbet'
gem 'ulid', '1.3.0', 'require' => false # A random gem I picked from my project that doesn't have any dependencies
```
- Run `bundle exec srb init`

#### Observed output

`sorbet/rbi/gems` contains `ulid.rbi`

#### Expected behavior

`sorbet/rbi/gems` should not contain `ulid.rbi`

- - -

I believe https://github.com/sorbet/sorbet/pull/2637 caused this regression - `require` is not passed into `Gemfile.lock`, so parsing the lockfile instead of the Gemfile makes `srb` think every gem is requred.

**Comment by jez** [comment]
Yeah that looks like the right PR. I have no real preference, because Stripe doesn't use this code. @connorshea maybe you want to chime in?

I'm defaulting to reverting that PR, because it seems worse to require things that explicitly should not be required than it does to not require enough things (because you can ~easily hand write RBIs if something wasn't required aggressively enough).

Also @jflinter you may want to consider using https://github.com/Shopify/tapoica. People who use Sorbet outside of Stripe have reported that it works better in a lot of cases.

**Comment by connorshea** [comment]
I use tapioca so I don't think this change would effect me anyway, but the intent was to load all gems because you need type signatures for all gems. Most of the time when you have a gem set to require: false, you still _use_ that gem it's just that it gets required manually when the gem is needed. And IIRC Sorbet got/gets confused by that.

So I'm not going to block such a change, but I do think it might be a bad idea to revert the change.

**Comment by jflinter** [comment]
I'm using tapioca already to generate .rbi for my gems, but still depend on `srb rbi hidden-definitions` to pick up other hidden methods in our codebase. That command is going to call `require_everything` anyway though, so in practice I just get a ton of unneeded gem sigs in my `hidden.rbi` (that's what got me poking around here).

I agree that sigs should be generated for required gems and their dependencies, but per the original discussion in https://github.com/sorbet/sorbet/issues/1104 there also does need to be a way to indicate to sorbet that a gem should be ignored, and `require: false` seems like the right way to do that.

https://github.com/sorbet/sorbet/pull/4815 is my stab at fixing this, although I'm having trouble writing a test case for it because I can't seem to get the test suite running locally...

**Comment by univerio** [comment]
I'd like to chime in and point out that I find it odd to have .rbis for transitive dependencies at all. If your project `foo` depends on `gem_a` which transitively depends on `gem_b`, then call sites in `foo` (i.e. the only things that Sorbet is useful for) should only reference `gem_a`, even if `gem_b` does get loaded at runtime, so you should only need .rbis for `gem_a`. If code in `foo` also references `gem_b`, then `gem_b` would no longer just be a transitive dependency -- it would be an _explicit dependency_ of `foo`, meaning you should add it to `Gemfile`.

An exception for this argument is perhaps if sigs in `gem_a` reference constants from `gem_b`, but in the context of the `hidden-definitions` tool this exception is irrelevant because it only cares about arity anyway.

**Comment by jflinter** [comment]
I agree in theory, but in practice I feel like it's pretty common (for better or for worse) to reference a gem's explicit dependencies - the main example coming to mind being rails, where you would typically have `gem rails` in your Gemfile but work directly with ActiveRecord or ActiveSupport or whatever in your codebase. ¯\_(ツ)_/¯

**Comment by paracycle** [comment]
> I'd like to chime in and point out that I find it odd to have .rbis for transitive dependencies at all. If your project `foo` depends on `gem_a` which transitively depends on `gem_b`, then call sites in `foo` (i.e. the only things that Sorbet is useful for) should only reference `gem_a`, even if `gem_b` does get loaded at runtime, so you should only need .rbis for `gem_a`. If code in `foo` also references `gem_b`, then `gem_b` would no longer just be a transitive dependency -- it would be an _explicit dependency_ of `foo`, meaning you should add it to `Gemfile`.
> 
> An exception for this argument is perhaps if sigs in `gem_a` reference constants from `gem_b`, but in the context of the `hidden-definitions` tool this exception is irrelevant because it only cares about arity anyway.

This argument is not exactly correct, since you are just thinking about method calls. What usually ends up happening is that the fact that a gem is loaded has a way more global effect that you could imagine.

Suppose that this is your scenario:

```
app
- foo
  - json
- bar
```

Now, your app does not have a direct dependency on `json`, but `foo` does. When `foo` requires the `json` gem, lots of core Ruby classes will have modules mixed into them to add the `to_json` methods. The application could end up depending on this behaviour since it has no idea if that is being added by `foo` or `json`, it just works. So, if you don't generate the RBI file for `json` then you would not be representing the types in your application properly.

**Comment by univerio** [comment]
I understand a gem being required can have global effects at runtime. What I'm arguing is that the mere fact that gems _can_ have such global effects does not automatically mean that Sorbet necessarily has to generate RBIs for any gem that happens to get required at runtime. It is _not_ the case the Sorbet has to know about 100% of method calls that can possibly happen at runtime, nor should it -- it is a design choice.

In the scenario you've outlined, yes, I know that requiring `json` monkeypatches `to_json` on `Object`. However, in this case, just because you happen to depend on `to_json` in `app` does not mean that Sorbet would somehow be wrong if it were to not accommodate this use case. My opinion is that in this case your `Gemfile` is wrong because it didn't explicitly declare a dependency that it has.

I also concede that this argument doesn't work for meta-gems whose sole job is to pull in other gems, but the solution still applies: just add those transitive dependencies directly to your `Gemfile`, which is both semantically correct and not a particularly heavy burden. On the other hand, consider the opposite problem:

- my app has an explicit dependency on gem `foo`
- `foo` declares `bar` as a dependency
- `require 'bar'` has require-time side-effects that monkeypatches `Object`
- `foo` only ever does `require 'bar/util'` which does not have require-time side-effects
- my app has nothing to do with gem `bar`

In this scenario, Sorbet automatically generating RBIs for `bar` is undesirable (due to the monkeypatch), and opting out currently requires me to add `bar` to my `Gemfile` with `require: false` when my app has nothing to do with `bar` at all! (This, by the way, is not a hypothetical scenario. The `sinatra` gem behaves like this -- `require 'sinatra'` monkeypatches `Object` while `require 'sinatra/base'` does not.)
