### ISSUE TITLE
misleading documentation surrounding IDE support

### ISSUE THREAD

**Issue by quinn** [sorbet/sorbet#4916]
The documentation claims IDE support, but there is no information on how this actually work, that I could find. I did however find discussions that editor integrations are still closed-source:

https://github.com/sorbet/sorbet/issues/1013
https://github.com/sorbet/sorbet/pull/4915

Could the sorbet project be more transparent about what it means by "IDE ready" and what the expectations are surrounding that? Does Stripe have an internal vs code extension that is closed-source? is the Sorbet project looking for contributors to create a VS Code extension? As it stands, the documentation is misleading, especially considering this gif on the homepage:

![image](https://sorbet.org/img/autocompleteAndDocs1.gif)

It's somewhat of a tease to show something that doesn't actually exist or is actually closed-source on the project homepage.

**Comment by klardotsh** [comment]
While I've read several times that Stripe has their own proprietary VSCode integration and I'll assume that's likely true, the LSP support in Sorbet works relatively well for me in Neovim. Not a byte of proprietary code needed to make it happen.
![screenshot-2021-12-08-02:38:21Z](https://user-images.githubusercontent.com/799439/145138615-3a3913e0-ba0c-47c6-a8fc-b74fa5874335.png)

[langserver.org](https://langserver.org/) is a good resource for sorting out the language <-> editor matrix for LSP-driven "IDE-like" features. Speaking to VSCode specifically, there appears to be at least one community project to that end at https://github.com/danhuynhdev/sorbet-lsp, though I haven't personally used it (since I don't use VSCode to begin with).

**Comment by connorshea** [comment]
It's available now :) https://sorbet.org/blog/2022/01/06/open-sourcing-sorbet-vscode
