### ISSUE TITLE
Error 4012 incorrectly returned for aliased constants

### ISSUE THREAD

**Issue by jflinter** [sorbet/sorbet#5027]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20returns%28Class%29%20%7D%0Adef%20make_class%0A%20%20Class.new%0Aend%0A%0AFoo%20%3D%20make_class%0ABar%20%3D%20Class.new%0A%0Aclass%20Foo%0Aend%0A%0Aclass%20Bar%0Aend%0A)

```ruby
# typed: true

extend T::Sig

sig { returns(Class) }
def make_class
  Class.new
end

Foo = make_class
Bar = Class.new

class Foo
end

class Bar
end
```

#### Observed output

```
editor.rb:13: Redefining constant Foo https://srb.help/4012
    13 |class Foo
    14 |end
    editor.rb:10: Previous definition
    10 |Foo = make_class
        ^^^
Errors: 1
```

#### Expected behavior

No error should be raised.

- - -

The provided example is valid Ruby - Foo is a class and can be reopened. It's interesting that Sorbet is OK with reopening Bar as defined above, it looks like something about the method call makes it unable to ascertain what kind of constant Foo is, even when annotated with a `sig`.

**Comment by jez** [comment]
For better or worse, this error is correct.  and at the time where Sorbet is about to add a constant into its global table of all constants, it has to make a call on whether the constant is a class or module (which means it can have ancestors and own other definitions like methods and sub constants) or whether it is a dumb field constant, that just holds a value with a return type.

The definition of `Foo =` and `class Foo` could occur in separate files, but each definition is only going to be processed once, not in a fixed point, for performance on large codebases, so the decision can't be changed later if the "wrong" definition is encountered first.

Also, Sorbet can't process signature information until the set of all constants in a program is known (again, this is not done together in a fixed point for performance on large codebases).

Unfortunately, this means that you can't write DSLs like this for defining classes. Some alternative solutions:

- Create helper functions that you would have called inside the block passed to `Class.new`, and call those helper functions inside a `class Foo; end` definition
- Create similar helper functions for the code that you would have passed the result of calling `Class.new` to
- Use a code generation step to generate Ruby files, instead of using a DSL
- Ask Sorbet to ignore the file containing the `Foo = make_class` definition, and create or generate an RBI file for that class. This is similar to how [protoc-gen-rbi](https://github.com/coinbase/protoc-gen-rbi) works, because the Ruby files generated by the protobuf compiler exhibit a similar pattern
- Define classes explicitly but manually, allowing sorbet to see the definition in its entirety

Hopefully one of those alternatives can work for you!

**Comment by jflinter** [comment]
@jez thanks for all the context - I figured something like the syntactic translation you describe was going on. Definitely a bummer but makes sense for cycle-avoiding reasons. I think the first workaround should be fine (although in the meantime I'm just suppressing error 4012 in my sorbet config, which is kind of fine given how rare that error legitimately occurs for us).

Also, nice talking to you again! (I'm @jack, now ex-Stripe.)
