### ISSUE TITLE
Rails.cache.fetch + other blocks hide typing information.

### ISSUE THREAD

**Issue by Overload119** [sorbet/sorbet#5063]
In my codebase I have lots of code that uses blocks.
Rails.cache.fetch and Appsignal.instrument for example.
These basically mask the typing of the given input, but it's always different.

For example:

```rb
# typed: true
sig { returns(Integer) }
def foo
  Rails.cache.fetch('test') do 
    5
  end
end
```

I'm getting around this by writing code like this:

```
# typed: true
sig { returns(Integer) }
def foo
  Rails.cache.fetch('test') do 
    foo_impl
  end
end

sig { returns(Integer) }
def foo_impl
    5
end
```

Is there a better solution for this?
I can't type Rails.cache.fetch (afaik) since the return type can be a bunch of different things.

**Comment by connorshea** [comment]
I tried looking into this but I can't figure out a way to do this. The only other (I won't say better, because it's really not lol) way I can think of to do this is to use T.cast, but that doesn't really add typechecking in any meaningful way since it still doesn't actually have the ability to check what's returned by the inside of the block.

```ruby
sig { returns(Integer) }
def foo
  T.cast(Rails.cache.fetch('test') do 
    5
  end, Integer)
end
```

I'd be interested in this as well since there are a few places where this kind of pattern would be useful.

**Comment by jez** [comment]
I think you simply want to ensure that the `fetch` method is given a signature that says it returns whatever the block returns.

You can provide such a signature with [generic methods](https://sorbet.org/docs/generics#generic-methods).

```ruby
sig do
  type_parameters(:U)
    .params(
      key: String,
      blk: T.proc.returns(T.type_parameter(:U))
    )
    .returns(T.type_parameter(:U)
end
def fetch(key, &blk)
end
```

To provide that type annotation, you'll need to use an [RBI file](https://sorbet.org/docs/rbi). Someone might have written an RBI file annotation for that Rails method. You can look in either the sorbet-typed repo or Shopify's rbi-central repo if you're using Tapioca.
