### ISSUE TITLE
add unsafe nilable (for instance variables)

### ISSUE THREAD

**Issue by md-work** [sorbet/sorbet#5068]
In some situations it may be helpful to have an alternative to `T.nilable` which doesn't triggers errors. Similar to "old" languages like C++ or Java.  
E.g. cyclic injections can be such a scenario.

&nbsp;

**Example** ([sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0A%0Aclass%20A%0A%20%20attr_writer%20%3Ab%0A%0A%20%20def%20initialize%0A%20%20%20%20%40b%20%3D%20T.let%28nil%2C%20T.nilable%28B%29%29%0A%20%20end%0A%0A%20%20%23%20imagine%20many%20places%20in%20A%20using%20%40b%0A%20%20def%20example_method%0A%20%20%20%20T.must%28%40b%29.do_something%0A%20%20end%0Aend%0A%0A%0Aclass%20B%0A%20%20def%20initialize%28a%29%0A%20%20%20%20%40a%20%3D%20T.let%28a%2C%20A%29%0A%20%20end%0A%0A%20%20def%20do_something%3B%20end%0Aend%0A%0A%0Aclass%20Example%0A%20%20def%20self.main%0A%20%20%20%20a%20%3D%20A.new%0A%20%20%20%20b%20%3D%20B.new%28a%29%0A%20%20%20%20a.b%20%3D%20b%0A%20%20end%0Aend))
shortened:
```ruby
class A
  attr_writer :b

  def initialize
    @b = T.let(nil, T.nilable(B))
  end

  # imagine many places in A using @b
  def example_method
    T.must(@b).do_something
  end
end


class Example
  def self.main
    a = A.new
    b = B.new(a)
    a.b = b
  end
end
```
This may cause a lot of `T.must` in A. Although the programmer is sure to make A only in a place where it's mostly sure that B gets injected.  
`T.untyped` isn't a good alternative, because the programmer still wants all other errors (e.g. methods not existing on B).

&nbsp;

**Alternative A:** Disable runtime errors  
An ugly hack!
```ruby
class A
  attr_writer :b

  def initialize
    # T::cast is needed to silence the static checker.
    # And inline_type_error_handler needs to be modified to silence the runtime checker on T.cast
    old_inline_handler = T::Configuration.instance_variable_get('@inline_type_error_handler')
    begin
      T::Configuration.inline_type_error_handler = proc {}
      @b = T.let(T.cast(nil, B), B)
    ensure
      T::Configuration.inline_type_error_handler = old_inline_handler
    end
  end
 [...]
end
```

&nbsp;

**Alternative B:** T.must wrapper method  
This is quite clean. But it may require writing a lot of boiler plate methods if you have a lot of instance variables.
```ruby
class A
  extend T::Sig

  attr_writer :b

  sig { returns(B) }
  private def b
    T.must(B)
  end

  def initialize
    @b = T.let(nil, T.nilable(B))
  end

  # imagine many places in A using @b
  def example_method
    b.do_something
  end
end
```

&nbsp;

**Proposal:** Silent unsafe nilable  
unsafe_nilable will make @b behave like `T.untyped` regarding `nil` errors (similar to null errors in C++ or Java).  
But all other errors will be reported. E.g. `@b.method_not_existing_in_b_class` will be a static error.
```ruby
class A
  attr_writer :b

  def initialize
    @b = T.let(nil, T.unsafe_nilable(B))
  end

  # imagine many places in A using @b
  def example_method
    @b.do_something
  end
end
```

**Comment by jez** [comment]
There's another alternative, which is to use `T.unsafe` + the `checked: false` flag on `T.let`

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Arequire%20'sorbet-runtime'%0Aextend%20T%3A%3ASig%0A%0Aclass%20B%3B%20end%0Aclass%20A%0A%20%20attr_writer%20%3Ab%0A%0A%20%20def%20initialize%0A%20%20%20%20%40b%20%3D%20T.let%28T.unsafe%28nil%29%2C%20B%2C%20checked%3A%20false%29%0A%20%20end%0A%0A%20%20%23%20imagine%20many%20places%20in%20A%20using%20%40b%0A%20%20def%20example_method%0A%20%20%20%20%40b.do_something%0A%20%20end%0Aend%0A)

```ruby
# typed: true
require 'sorbet-runtime'
extend T::Sig

class B; end
class A
  attr_writer :b

  def initialize
    @b = T.let(T.unsafe(nil), B, checked: false)
  end

  # imagine many places in A using @b
  def example_method
    @b.do_something
  end
end
```

This seems like a better approach overall, because it requires fewer new concepts for the reader to learn (they will already be familiar with `T.unsafe` and `checked: false`), is explicit w.r.t. what's actually happening statically and at runtime, and does not require implementing a type system features that have been literally coined the billion dollar mistake.

Thanks for the suggestion, but I think we'll pass on this feature. Hope this workaround can work well enough for you.
