### ISSUE TITLE
[Proposal] Error on useless type aliases

### ISSUE THREAD

**Issue by Morriar** [sorbet/sorbet#5283]
### Problem

As we refactor code we sometimes replace a type alias in a signature by another "real" type making the original type alias useless.

### Proposed solution

Should we make an error of such cases?

```rb
  MyInteger = T.type_alias { Integer }
# ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ error: useless type alias, alias `MyInteger` is not used anywhere
```

Can you think of a case where it would make sense for a gem/lib to expose a type alias that would only be used by the client?

**Comment by jez** [comment]
While I can see the value here, I think this would be hard to support because:

- We would have to keep track of a “did we use this constant” bit. That could be done, but would present problems to some future changes we have planned to make constant resolution more incremental/more parallel.
- It’s hard to know whether a type alias is unused properly, or whether it is intended to be used by clients of a gem. For example, maybe a gem might define a large enum and define a subset of those enums in a type alias as a shorthand for clients.

Thanks again for the idea, but I think I’m going to close this for now.
