### ISSUE TITLE
Enable typing vanilla ruby Struct

### ISSUE THREAD

**Issue by jeffcarbs** [sorbet/sorbet#5600]
### Problem

We use `T::Struct` heavily throughout our codebase but we have some particularly hot/perf-sensitive places where the overhead is too high and we need to "drop down" to vanilla ruby structs. Sorbet [currently desugars](https://github.com/sorbet/sorbet/blob/master/rewriter/Struct.h) `Foo = Struct.new(:a, :b)` but the initialize and getters/setters are essentially untyped, which means to get static typing back you need to manually define an RBI. It would be nice if we could define this inline.

Another problem is that you can't type a file at `strict` if it contains `Struct.new(:foo, :bar)` because you get errors saying `This function does not have a sig` because of how struct get desugared (see [sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0AA%20%3D%20Struct.new%28%3Afoo%2C%20%3Abar%29))

### Proposed solution

An idea I've been toying around with that I think would be relatively ergonomic and not terrible to implement or maintain is to enable adding a `sig` to `Struct.new` essentially typing the `initialize` method, so something like:
```ruby
sig {  params(foo: String, bar: T.nilable(Integer)).void }
A = Struct.new(:foo, :bar)
```

would desugar into roughly:

```ruby
class A < Struct
  sig { returns(String) }
  def foo; end

  sig { params(String).returns(String) }
  def foo=(arg); arg; end

  sig { returns(T.nilable(Integer)) }
  def bar; end

  sig { params(T.nilable(Integer)).returns(T.nilable(Integer)) }
  def bar=(arg); arg; end


  sig { params(foo: String, bar: T.nilable(Integer)).void }
  def initialize(foo=nil, bar=nil)
    T.cast(nil, A)
  end
end
```

I'm happy to take a stab at implementing this, but wanted to check first if something like this would even be considered.

**Comment by jeffcarbs** [comment]
I was actually thinking that this _wouldn't_ have a runtime component. In general, I think `T::Struct` is great and much preferred for the majority of use-cases, but in perf-sensitive applications it would be nice to provide something where you still get the static typing without any runtime overhead.

What if this lived in the `WithoutRuntime` namespace to indicate that it doesn't provide any runtime support. So riffing on your suggestion:
```ruby
class T::Struct::WithoutRuntime
  def self.new(**props)
    Struct.new(*props.keys, keyword_init: true)
  end
end

A = T::Struct::WithoutRuntime.new(foo: String, bar: T.nilable(Integer))
A.new(foo: 'Hey', bar: 1)
=> #<struct A foo="Hey", bar=1>
```

**Comment by froydnj** [comment]
That's a good callout on explicitly avoiding runtime typechecking.  I have no issues with that.

I don't know where the right place to put things is.  I am inclined to switch things around and call it `T::WithoutRuntime::Struct` (for parallelism with `T::WithoutRuntime.sig`).  Both `T::WithoutRuntime::Struct` and `T::Struct::WithoutRuntime` can of course be confused with `T::Struct`, which I think is not desirable in this context.

This is certainly bikeshed territory, but maybe `T::Ruby::Struct` (`T::WithoutRuntime::Ruby::Struct`) or `T::RubyStdlib::Struct`?

**Comment by froydnj** [comment]
We talked about this at a team meeting and the consensus was:

1. We don't want this type in `sorbet-runtime`, because it'd be too easy to mixup with `T::Struct`.
2. We have no problems with this type being implemented in a separate gem and a rewriter pass that recognizes calls to `TheGem::TypedStruct.new` and does the appropriate rewriter magic.

(I think we might have issues if a lot of gems start requesting rewriter passes, but for now, one more rewriter pass doesn't seem too bad; at least it can share a lot of code with the existing `Struct` rewriter pass.)

Long-term, I think what we want is a way to enable type-checking of props in `T::Struct` based on `T::Configuration.default_checked_level` rather than the custom type-checking they do now.  And that might require disentangling props from their Stripe-specific heritage, etc.

**Comment by jeffcarbs** [comment]
Sounds good, thanks for the update!
