### ISSUE TITLE
Class constant assignments cannot be inherited or used as namespaces

### ISSUE THREAD

**Issue by fsateler** [sorbet/sorbet#5799]
Or somehow, `T.let` does not work for classes.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0A%0Aclass%20A%20%3C%20Object%0Aend%0A%0AB%20%3D%20T.let%28const_get%28'A'%29%2C%20T.class_of%28A%29%29%0A%0AT.reveal_type%28B%29%0A%0Aclass%20C%20%3C%20B%0Aend%0A%0Aclass%20B%3A%3AD%0Aend)

```ruby
# typed: true
extend T::Sig


class A < Object
end

B = T.let(const_get('A'), T.class_of(A))

T.reveal_type(B)

class C < B
end

class B::D
end
```

#### Observed output

```
editor.rb:15: Can't nest D under B because B is not a class or module https://srb.help/4015
    15 |class B::D
              ^^^^
    editor.rb:8: B defined here
     8 |B = T.let(const_get('A'), T.class_of(A))
        ^

editor.rb:12: The super class B of C does not derive from Class https://srb.help/5067
    12 |class C < B
        ^^^^^^^^^^^
    editor.rb:15: B defined here
    15 |class B::D
              ^^^^

editor.rb:10: Revealed type: T.class_of(B) https://srb.help/7014
    10 |T.reveal_type(B)
        ^^^^^^^^^^^^^^^^
  Got T.class_of(B) originating from:
    editor.rb:10:
    10 |T.reveal_type(B)
                      ^
Errors: 3
```

#### Expected behavior

`B` is usable as both a namespace and a parent class.

- - -

I'm trying to apply sorbet to a project that uses [active_type](https://github.com/makandra/active_type). This gem generates classes dynamically. I understand it is not possible to use it directly ([4002](https://sorbet.org/docs/error-reference#4002)). I thought `T.let` could be used to teach sorbet that `B` is a class that inherits from `A`, but it appears to not be possible. Current workaround is to hide the definitions from sorbet with `const_set`, and provide a fake definition (`class B < A`) out of band via rbi files.

**Comment by jez** [comment]
Unfortunately, this is either a feature or an accepted limitation of Sorbet depending on your viewpoint.

For performance, Sorbet resolves all classes and modules, including all mixins and superclass relationships, before it resolves constants assignments declared with `T.let`. This forces a strict separation between things that are classes/modules and other constants. We have no plans to change this architecture decision.

The current workaround for codebases that must structure their code this way (where the codebase itself can't be changed to stop relying on this pattern) is to use RBI files to declare constants as proper classes, and to hide the constant assignments with calls to `const_set` so that Sorbet only sees the definition in the RBI file, not in the source file.

**Comment by fsateler** [comment]
> Unfortunately, this is either a feature or an accepted limitation of Sorbet depending on your viewpoint.

OK, thanks for explaining.
