### ISSUE TITLE
`assert_type` does not raise an error (statically or at runtime) with `type_member`

### ISSUE THREAD

**Issue by ghiculescu** [sorbet/sorbet#5811]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Base%0A%20%20extend%20T%3A%3AGeneric%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20TObject%20%3D%20type_member%0A%0A%20%20def%20initialize%28object%29%0A%20%20%20%20%40object%20%3D%20T.let%28object%2C%20TObject%29%0A%20%20%20%20T.assert_type!%28%40object%2C%20TObject%29%0A%20%20end%0Aend%0A%0Aclass%20TypeA%3B%20end%0Aclass%20TypeB%3B%20end%0A%0Aclass%20A%20%3C%20Base%0A%20%20TObject%20%3D%20type_member%20%7B%20%7B%20fixed%3A%20TypeA%20%7D%20%7D%0Aend%0A%0AA.new%28TypeA.new%29%20%23%20good%0AA.new%28TypeB.new%29%20%23%20should%20crash)

```ruby
# typed: true

require "sorbet-runtime"

class Base
  extend T::Generic
  extend T::Sig

  TObject = type_member

  def initialize(object)
    @object = T.let(object, TObject)
    T.assert_type!(@object, TObject)
  end
end

class TypeA; end
class TypeB; end

class A < Base
  TObject = type_member { { fixed: TypeA } }
end

A.new(TypeA.new) # good
A.new(TypeB.new) # should crash
```

#### Observed output

No static or runtime errors.

#### Expected behavior

I would like `assert_type` to raise an error here where the wrong type is used.

#### Other notes

If I add a sig to the initializer ([see line 9](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Base%0A%20%20extend%20T%3A%3AGeneric%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20TObject%20%3D%20type_member%0A%0A%20%20sig%20%7B%20params%28object%3A%20TObject%29.void%20%7D%0A%20%20def%20initialize%28object%29%0A%20%20%20%20%40object%20%3D%20T.let%28object%2C%20TObject%29%0A%20%20%20%20T.assert_type!%28%40object%2C%20TObject%29%0A%20%20end%0Aend%0A%0Aclass%20TypeA%3B%20end%0Aclass%20TypeB%3B%20end%0A%0Aclass%20A%20%3C%20Base%0A%20%20TObject%20%3D%20type_member%20%7B%20%7B%20fixed%3A%20TypeA%20%7D%20%7D%0Aend%0A%0AA.new%28TypeA.new%29%20%23%20good%0AA.new%28TypeB.new%29%20%23%20should%20crash)), I get a static error but *not* a runtime error.

The static error:

```
editor.rb:24: Expected TypeA but found TypeB for argument object https://srb.help/7002
    24 |A.new(TypeB.new) # should crash
              ^^^^^^^^^
  Expected TypeA for argument object of method Base#initialize:
    editor.rb:9:
     9 |  sig { params(object: TObject).void }
                       ^^^^^^
  Got TypeB originating from:
    editor.rb:24:
    24 |A.new(TypeB.new) # should crash
              ^^^^^^^^^
Errors: 1
```

As far as I can tell, that's the runtime equivalent of doing `T.assert_type!(TypeB.new, TypeA)`, which does error at runtime.

**Comment by jez** [comment]
I don't think that this is how `T.assert_type!` should work.

- Generics are completely erased at runtime. [This is documented here](https://sorbet.org/docs/generics#generics-and-runtime-checks). That is not something we are likely to ever change. You will never get a runtime type error for any sort of type assertion (`T.let`, `T.assert_type!`, etc.) for a runtime violation of a type member type
- The `T.let` fails because `object` is untyped. That's not unique to type member, it happens for `Integer` too:

https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Base%0A%20%20extend%20T%3A%3AGeneric%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20def%20initialize%28object%29%0A%20%20%20%20%40object%20%3D%20T.let%28object%2C%20Integer%29%0A%20%20%20%20T.assert_type!%28%40object%2C%20Integer%29%0A%20%20end%0Aend%0A%0Aclass%20TypeA%3B%20end%0Aclass%20TypeB%3B%20end%0A%0Aclass%20A%20%3C%20Base%0Aend%0A%0AA.new%280%29%20%23%20good%0AA.new%28''%29%20%23%20should%20crash

So I think that this is not actually a bug. If I've misunderstood please let me know.

**Comment by ghiculescu** [comment]
> * Generics are completely erased at runtime. [This is documented here](https://sorbet.org/docs/generics#generics-and-runtime-checks).

Ahh, I missed that. Would it be worth mentioning that anywhere on https://sorbet.org/docs/type-assertions ?

> So I think that this is not actually a bug. If I've misunderstood please let me know.

You're right. I appreciate the explanation.
