### ISSUE TITLE
Parser error when method name is a language keyword

### ISSUE THREAD

**Issue by georgebrock** [sorbet/sorbet#5962]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Promise%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20returns%28Promise%29%20%7D%0A%20%20def%20then%0A%20%20%20%20self%0A%20%20end%0Aend%0A%0A%23%20Calling%20%23then%20on%20the%20same%20line%20works%0A%0APromise.new.then.then%0A%0A%23%20But%20adding%20a%20line%20break%20after%20the%20%60.%60%20causes%20an%20error%0A%0APromise.new.%0A%20%20then.%0A%20%20then)

```ruby
# typed: true

class Promise
  extend T::Sig

  sig { returns(Promise) }
  def then
    self
  end
end

# Calling #then on the same line works

Promise.new.then.then

# But adding a line break after the `.` causes an error

Promise.new.
  then.
  then
```

#### Observed output

```
editor.rb:19: unexpected token "then" https://srb.help/2001
    19 |  then.
          ^^^^
Errors: 1
```

#### Expected behavior

I would expect Sorbet to detect no errors in this code.

- - -

Ruby successfully interprets this input as a call to the `Promise#then` method, but Sorbet's parser seems to think it is an instance of the `then` language keyword.

In the wild I've encountered this with methods like `ActiveRecord::QueryMethods#or` and `Concurrent::Promise#then`.

While it is possible to work around by changing the wrapping style, it introduces a bit of friction to do so.

**Comment by georgebrock** [comment]
I figured I’d have a go at fixing this, but after reading through some of the lexer code, it looks like this is intentional behaviour rather than a bug:

https://github.com/sorbet/sorbet/blob/306fb9efbd4ef05ac37e77caa46990d29b93c502/parser/parser/cc/lexer.rl#L1834-L1858

Sorry for the noise 🙂

**Comment by patbl** [comment]
The workarounds I've thought for for this issue are

1. Put the dot at the beginning of the line instead of the end:

```
Promise.new
  .then
  .then
```

I actually favor this style, but the code base I'm working in universally puts the dots at the ends of lines rather than at the beginnings (we have a Rubocop rule that enforces this).

2. Use aliases for conflicting methods when possible. For example, use `yield_self` instead of `then`, and use [RSpec's `&`](https://relishapp.com/rspec/rspec-expectations/docs/compound-expectations) instead of  `and`.

This is fine, but my impression is that most people favor the "keyword" versions of these methods. `then` was added as an alias to `yield_self` because the former is more readable and shorter. So getting people to use the non-conflicting aliases is cutting against the grain a little bit.

3. Reformat the code. For example, put everything on one line, instead of having each method call on a different line. For example, change this

```ruby
Hippopotamus.
  where(foo_id: foo_ids).
  or(Hippopotamus.where(bar_id: bar_ids)).
  load
```

to this

```ruby
Hippopotamus.
  where(foo_id: foo_ids).or(
    Hippopotamus.where(bar_id: bar_ids)
  ).load
```

While there are some scenarios in which this is an OK solution, it usually results in formatting that's more unusual and harder to read.

If we go ahead with adopting Sorbet, I'll propose making the code-convention change described in (1). With Rubocop's auto-correct feature, it wouldn't be much work switching over to it (though it would add a substantial amount of noise to Git history).

I'm curious whether anyone has any other ideas about how to deal with this problem.
