### ISSUE TITLE
method overloading 

### ISSUE THREAD

**Issue by MuhammadAdam-CodeInterview** [sorbet/sorbet#5975]
Hi,
![issue](https://user-images.githubusercontent.com/101163464/176631055-c0fdda6e-edf8-4764-868e-2422a2817002.png)
Ruby does not support method overloading then why Sorbet is showing in the completions result?

**Comment by paracycle** [comment]
Ruby does not support method overloading, but the same method can act in overloaded ways at runtime. For example, if you call `Enumerable#each` with a block the behaviour is different to if you called it without a block. The parameters, their types and the return value and its type are usually different for the different ways one invokes the method.

Thus, Sorbet needs to support signature overloading for core and stdlib methods and because it has to. Hwoever, there is no support for signature overloading for user code.
