### ISSUE TITLE
Poor support for Symbol#to_proc with args

### ISSUE THREAD

**Issue by lugray** [sorbet/sorbet#6112]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0A%5B1%2C2%2C3%5D.reduce%28%26%3A%2B%29)

```ruby
[1,2,3].reduce(&:+)
```

#### Observed output

```
editor.rb:3: Not enough arguments provided for method Integer#+. Expected: 1, got: 0 https://srb.help/7004
     3 |[1,2,3].reduce(&:+)
                        ^^
    https://github.com/sorbet/sorbet/tree/master/rbi/core/integer.rbi#L182: Integer#+ defined here
     182 |  def +(arg0); end
            ^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

This should continue to be valid code.

**Comment by lugray** [comment]
A git bisect points to 4787d3392beb194d68ffbc2b7b9a5ceb898bf979 from #6087. cc @jez.

**Comment by lugray** [comment]
Interestingly, `[1,2,3].reduce(&(:+.to_proc))` is fine.

Looking more closely at the PR, it's clear that it surfaced this bug rather than creating it - it's not quite fair to call this a regression.

**Comment by jez** [comment]
Yes as you mention this has always been a problem, it’s just that in removing the `T.untyped` from reduce it made it surface in more places.

The workaround is simply to write

```ruby
xs.reduce {_1 + _2}
```

Sorbet’s support for Symbol#to_proc is naive. It always translates an expression `&:foo` to

```ruby
{ x.foo }
```

it would be neat to fix this, but it would involve deferring expansion of the block until infer (we don’t know the type of the receiver given to the block until then), which is hard because the block needs to be expanded at least by CFG builder.

I don’t have any good ideas for how to fix this at the moment.
