### ISSUE TITLE
JSON::ParserError on running srb init

### ISSUE THREAD

**Issue by thearchduke** [sorbet/sorbet#6134]
I'm trying to reinitialize sorbet on a project where the .rbi files got pretty out of sync. A lot of stuff happened in between the last time we ran it and now, so I can't really provide a useful changelog. I'd love to at least know where it's choking.

#### Input

```ruby
bundle exec srb init
```

#### Observed output

The LoadErrors are pretty normal, IIRC, but then:

```
...
LoadError: cannot load such file -- spring
LoadError: cannot load such file -- spring-watcher-listen
LoadError: cannot load such file -- sprockets-rails
/usr/local/bundle/gems/sorbet-0.5.10242/bin/srb: line 109: /usr/local/bundle/gems/sorbet-static-0.5.10242-universal-darwin-14/libexec/sorbet: cannot execute binary file: Exec format error
Traceback (most recent call last):
        11: from /usr/local/bundle/gems/sorbet-0.5.10242/bin/srb-rbi:256:in `<main>'
        10: from /usr/local/bundle/gems/sorbet-0.5.10242/bin/srb-rbi:215:in `main'
         9: from /usr/local/bundle/gems/sorbet-0.5.10242/bin/srb-rbi:135:in `init'
         8: from /usr/local/bundle/gems/sorbet-0.5.10242/bin/srb-rbi:251:in `block in make_step'
         7: from /usr/local/bundle/gems/sorbet-0.5.10242/lib/gem-generator-tracepoint.rb:38:in `main'
         6: from /usr/local/bundle/gems/sorbet-0.5.10242/lib/gem-generator-tracepoint/tracer.rb:80:in `trace'
         5: from /usr/local/bundle/gems/sorbet-0.5.10242/lib/gem-generator-tracepoint.rb:39:in `block in main'
         4: from /usr/local/bundle/gems/sorbet-0.5.10242/lib/require_everything.rb:20:in `require_everything'
         3: from /usr/local/bundle/gems/sorbet-0.5.10242/lib/require_everything.rb:46:in `require_all_files'
         2: from /usr/local/bundle/gems/sorbet-0.5.10242/lib/require_everything.rb:134:in `rb_file_paths'
         1: from /usr/local/bundle/gems/json-2.3.1/lib/json/common.rb:263:in `parse'
/usr/local/bundle/gems/json-2.3.1/lib/json/common.rb:263:in `parse': 784: unexpected token at '' (JSON::ParserError)
```

This is in a `ruby:2.6-alpine3.9` docker container on a mac.

#### Expected behavior

It initializes like normal.

Let me know what other info I can provide and I'll do my best!

**Comment by jez** [comment]
```
/usr/local/bundle/gems/sorbet-0.5.10242/bin/srb: line 109: /usr/local/bundle/gems/sorbet-static-0.5.10242-universal-darwin-14/libexec/sorbet: cannot execute binary file: Exec format error
```

`srb init` is trying to run `srb tc`, but the sorbet binary has the wrong executable file format.

it looks like bundle has managed to install `darwin-14`, which is the OS version for OS X Yosemite. This version of OS X is no longer receiving support

https://en.wikipedia.org/wiki/OS_X_Yosemite#Release_history

It is possible that bundler has found the wrong platform-specific binary for Sorbet. This is a bug in bundler upstream:

https://github.com/rubygems/rubygems/issues/5743

In any case, the JSON error is a red herring, because Sorbet itself failed to run (so it of course produced an empty JSON file).

Also, `srb init` is now in maintenance mode:

https://sorbet.org/blog/2022/07/27/srb-tapioca

As this doesn't look like a critical bug in `srb init` (and is instead a problem either with your environment, with a specific bundler version, or both), I'm going to close this out.

**Comment by thearchduke** [comment]
Thank you for the quick and helpful response!

If I get this working I will share the results here for others having this problem.
