### ISSUE TITLE
Typecheck return value of Enumerable#flat_map inner block

### ISSUE THREAD

**Issue by franklin-stripe** [sorbet/sorbet#632]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20A%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams(x%3A%20Integer).returns(T%3A%3AHash%5BInteger%2C%20Integer%5D)%7D%0A%20%20def%20bar(x)%0A%20%20%20%20%5Bx%2Cx%2B1%2Cx%2B2%5D.flat_map%20do%20%7Cx%7C%0A%20%20%20%20%20%20if%20x%20%25%202%20%3D%3D%200%0A%20%20%20%20%20%20%20%20%5B%5D%0A%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%5B1%2C%202%5D%20%23%20Should%20error%20since%20%60flat_map().to_h%60%20expects%20%5B%5B1%2C2%5D%5D%0A%20%20%20%20%20%20end%0A%20%20%20%20end.to_h%0A%20%20end%0Aend%0A%0Adef%20main%0A%20%20A.new.bar(91)%0Aend)

```ruby
# typed: true
class A
  extend T::Sig

  sig {params(x: Integer).returns(T::Hash[Integer, Integer])}
  def bar(x)
    [x,x+1,x+2].flat_map do |x|
      if x % 2 == 0
        []
      else
        [1, 2] # Should error since `flat_map().to_h` expects [[1,2]]
      end
    end.to_h
  end
end

def main
  A.new.bar(91)
end
```

#### Observed output

```
No errors! Great job.

```

#### Expected behavior

I'd expect this to raise a typechecking error since the output of the `flat_map` cannot be safely passed to `.to_h`

**Comment by jez** [comment]
This actually boils down to a problem with Sorbet's support for tuples.

The problem is that Sorbet infers the return type of the block to be `T.any([] (0-tuple), [Integer, Integer] (2-tuple))` and currently it gives up and says that this type is simply `T::Array[T.untyped]`.

That problem is tracked in #4203, so I'm going to close this as a duplicate.

- - - - -

It's actually possible to change the behavior in the example by using `T::Array[T.noreturn].new` instead of `[]` to represent the empty array:

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Amapped_bad%20%3D%20T%3A%3AArray%5BInteger%5D.new.flat_map%20do%20%7Cx%7C%0A%20%20if%20x%20%25%202%20%3D%3D%200%0A%20%20%20%20T%3A%3AArray%5BT.noreturn%5D.new%0A%20%20else%0A%20%20%20%20%5B1%2C%202%5D%0A%20%20end%0Aend%0Amapped_bad.to_h%0A%0Amapped_good%20%3D%20T%3A%3AArray%5BInteger%5D.new.flat_map%20do%20%7Cx%7C%0A%20%20if%20x%20%25%202%20%3D%3D%200%0A%20%20%20%20T%3A%3AArray%5BT.noreturn%5D.new%0A%20%20else%0A%20%20%20%20%5B%5B1%2C%202%5D%5D%0A%20%20end%0Aend%0Ares%20%3D%20mapped_good.to_h%0AT.reveal_type%28res%29)

```ruby
# typed: true

mapped_bad = T::Array[Integer].new.flat_map do |x|
  if x % 2 == 0
    T::Array[T.noreturn].new
  else
    [1, 2]
  end
end
mapped_bad.to_h

mapped_good = T::Array[Integer].new.flat_map do |x|
  if x % 2 == 0
    T::Array[T.noreturn].new
  else
    [[1, 2]]
  end
end
res = mapped_good.to_h
T.reveal_type(res)
```

#### Observed output

```
editor.rb:10: Expected T::Enumerable[[T.type_parameter(:U), T.type_parameter(:V)]] but found T::Array[Integer] for argument arg0 https://srb.help/7002
    10 |mapped_bad.to_h
        ^^^^^^^^^^
  Expected T::Enumerable[[T.type_parameter(:U), T.type_parameter(:V)]] for argument arg0 of method Sorbet::Private::Static.enumerable_to_h:
    https://github.com/sorbet/sorbet/tree/master/rbi/sorbet/sorbet.rbi#L55:
    55 |      arg0: T::Enumerable[[T.type_parameter(:U), T.type_parameter(:V)]],
              ^^^^
  Got T::Array[Integer] originating from:
    editor.rb:10:
    10 |mapped_bad.to_h
        ^^^^^^^^^^

editor.rb:20: Revealed type: T::Hash[Integer, Integer] https://srb.help/7014
    20 |T.reveal_type(res)
        ^^^^^^^^^^^^^^^^^^
  Got T::Hash[Integer, Integer] originating from:
    editor.rb:19:
    19 |res = mapped_good.to_h
              ^^^^^^^^^^^^^^^^
Errors: 2
```

That essentially forces Sorbet to keep the `[]` and the `[1, 2]` as a `T.any`, instead of trying to collapse the type to a `T::Array[T.untyped]`.
