### ISSUE TITLE
Remove `bind` from `T.proc` when in Initializer rewriter.

### ISSUE THREAD

**Issue by jez** [sorbet/sorbet#6848]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20C%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams%28blk%3A%20T.proc.bind%28String%29.void%29.void%20%7D%0A%20%20def%20initialize%28%26blk%29%0A%20%20%20%20%40blk%20%3D%20blk%0A%20%20end%0Aend%0A)

```ruby
# typed: true

class C
  extend T::Sig

  sig {params(blk: T.proc.bind(String).void).void }
  def initialize(&blk)
    @blk = blk
  end
end
```

#### Observed output

```
editor.rb:6: Using bind is not permitted here https://srb.help/5004
     6 |  sig {params(blk: T.proc.bind(String).void).void }
                           ^^^^^^^^^^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

When Sorbet copies the type annotation from a signature onto an instance variable declaration in `initialize`, it should strip the `.bind(...)` annotation from the block.

- - -

**Comment by egiurleo** [comment]
@pl-at-shopify and I are working on this!

**Comment by pl-at-shopify** [comment]
@egiurleo and me found out that `T.proc.bind` looks like a highly special cased construct that is allowed to be used on [blocks only](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20params%28blk%3A%20T.proc.bind%28String%29.void%29.void%0Aend%0Adef%20foo%28%26blk%29%0Aend%0A%0A) and does not allow [nesting](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20params%28blk%3A%20T.proc.params%28arg%3A%20T.proc.bind%28String%29.void%29.void%29.void%0Aend%0Adef%20foo%28%26blk%29%0Aend%0A%0A). The only correct usage [seems](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20params%28block%3A%20T.proc.bind%28String%29.void%29.void%0Aend%0Adef%20foo%28%26block%29%0Aend%0A%0A) to be `block: T.proc.bind(String)…`.

If this is so by design we might want to document the limitations and if it makes sense also the reasoning behind it.

In case the restrictions described above are artificial and there is a plan to remove them in the near future, we may want to make the change for this PR less special case specific (e.g. support nesting of `T.proc.bind`, specifying it as a type argument, using on non-block arguments). We think so because the current almost exact structure of AST is more or less trivial to traverse (but the code would not be flexible at all, see below) while for the general case we'd need to implement some tooling.

The said tooling might take a form of a `traverse()` function that could find patterns of nodes. We thought of making a prototype implementation that supports only several types of nodes and a fixed amount of "rules" to match.

On the other hand, if the special cased restrictions are here to stay we though of just hardcoding a traverse function that iterates over a `Call` linked list only, until finds `bind` and just removes it as described in the issue title.

What do you think?

**Comment by pl-at-shopify** [comment]
For now we went with the most straight forward solution as described in the issue title.
