### ISSUE TITLE
test_each loses type information if test_each'd array references a local variable

### ISSUE THREAD

**Issue by bhuga** [sorbet/sorbet#6962]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20self.test_each%28tests%2C%20%26blk%29%3B%20end%0Adef%20self.it%28%26blk%29%3B%20end%0A%0Aclass%20Thing%20%3C%20T%3A%3AStruct%0A%20%20const%20%3Agrace_minutes%2C%20Integer%0Aend%0A%20%20%0Agrace_minutes%20%3D%2015%0Atest_each%28%5B%0A%20%20Thing.new%28grace_minutes%3A%20grace_minutes%29%2C%0A%20%20%5D%29%20do%20%7Ci%7C%0A%20%20it%20%22%23%7Bi%7D%20should%20be%20struct%22%20do%0A%20%20%20%20T.reveal_type%28i%29%0A%20%20end%0Aend)

```ruby
# typed: true

def self.test_each(tests, &blk); end
def self.it(&blk); end

class Thing < T::Struct
  const :grace_minutes, Integer
end
  
grace_minutes = 15
test_each([
  Thing.new(grace_minutes: grace_minutes),
  ]) do |i|
  it "#{i} should be struct" do
    T.reveal_type(i)
  end
end
```

#### Observed output

```
editor.rb:15: Revealed type: T.untyped https://srb.help/7014
    15 |    T.reveal_type(i)
            ^^^^^^^^^^^^^^^^
  Got T.untyped originating from:
    editor.rb:13:
    13 |  ]) do |i|
                 ^
Errors: 1
```

#### Expected behavior

The loop variable for test_each should maintain the type of the array elements. Instead, it is untyped.

**Comment by bhuga** [comment]
[Compare with no local variable, the type is maintained](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Tests%0A%20%20def%20self.test_each%28tests%2C%20%26blk%29%3B%20end%0A%20%20def%20self.describe%28%26blk%29%3B%20end%0A%20%20def%20self.it%28%26blk%29%3B%20end%0A%20%20class%20Thing%20%3C%20T%3A%3AStruct%0A%20%20%20%20const%20%3Awhat%2C%20String%0A%20%20end%0A%20%20describe%20%22foo%22%20do%0A%20%20%20%20test_each%28%5B%0A%20%20%20%20%20%20Thing.new%28what%3A%20%22what%22%29%2C%0A%20%20%20%20%20%20Thing.new%28what%3A%20%22do%22%29%2C%0A%20%20%20%20%20%20Thing.new%28what%3A%20%22now%22%29%2C%0A%20%20%20%20%20%20%5D%29%20do%20%7Ci%7C%20%23%20hover%20over%20i%0A%20%20%20%20%20%20it%20%22%23%7Bi%7D%20should%20be%20struct%22%20do%0A%20%20%20%20%20%20%20%20T.reveal_type%28i%29%0A%20%20%20%20%20%20end%0A%20%20%20%20end%0A%20%20end%0Aend)

**Comment by jez** [comment]
While I agree this is not great, unfortunately that's likely the way this will have to be.

Sorbet models `test_each` by rewriting it to something like this:

```ruby
def it_should_be_struct
  [Thing.new(grace_minutes: 15)].each do |i|
    # ...
  end
end
```

if we were to naively do this with local variables, they would move out of the scope where they're defined:

```ruby
grace_minutes = 15
def it_should_be_struct
  [Thing.new(grace_minutes: grace_minutes)].each do |i|
                            ^^^^^^^^^^^^^ error: not defined inside this method
    # ...
  end
end
```

If it's possible to rewrite the test each to only mention constants, not local variables, [then you'll get types back](https://sorbet.run/#%23%20typed%3A%20true%0A%0Adef%20self.test_each%28tests%2C%20%26blk%29%3B%20end%0Adef%20self.it%28%26blk%29%3B%20end%0A%0Aclass%20Thing%20%3C%20T%3A%3AStruct%0A%20%20const%20%3Agrace_minutes%2C%20Integer%0Aend%0A%20%20%0AGrace_minutes%20%3D%2015%0Atest_each%28%5B%0A%20%20Thing.new%28grace_minutes%3A%20Grace_minutes%29%2C%0A%20%20%5D%29%20do%20%7Ci%7C%0A%20%20it%20%22%23%7Bi%7D%20should%20be%20struct%22%20do%0A%20%20%20%20T.reveal_type%28i%29%0A%20%20end%0Aend).

We _might_ technically be able to make this all go away, now that you can use `T.attached_class` on `T.proc.bind(...)`. As in, we could technically delete Sorbet's custom minitest support entirely (or at least the support for `it` blocks—the `before` blocks might want to stay) and simply let Sorbet type check calls to `it` like calls to `it`.

We haven't done that, because paradoxically that makes Sorbet slower. Some parts of Sorbet scale super-linearly in the size of a method body. That means having a lot of small methods is actually better than having one large method with a lot of `it` blocks.

Hope that gives some context as to why this is the case and how to work around it. Of course, you're always welcome to use `T.let` to ascribe a type manually.
