### ISSUE TITLE
Incorrect dead code detection when rescuing class that implements `===`

### ISSUE THREAD

**Issue by vinistock** [sorbet/sorbet#7376]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20def%20self.%3D%3D%3D%28other%29%0A%20%20%20%20true%0A%20%20end%0Aend%0A%0Abegin%0A%20%20raise%20StandardError%2C%20%22something%22%0Arescue%20A%0A%20%20puts%20%22hello%22%0Aend%0A)

```ruby
# typed: true

class A
  def self.===(other)
    true
  end
end

begin
  raise StandardError, "something"
rescue A
  puts "hello"
end
```

#### Observed output

```
editor.rb:12: This code is unreachable https://srb.help/7006
    12 |  puts "hello"
          ^^^^^^^^^^^^
    editor.rb:11: This condition was always falsy (T.untyped)
    11 |rescue A
               ^
  Got T.untyped originating from:
    editor.rb:11:
    11 |rescue A
               ^
Errors: 1
```

#### Expected behavior

Ruby can match rescued classes based on the implementation of `===`, so the code in the rescue branch is actually not dead. If you run that script, it will get inside the branch and print `hello` because `===` always returns `true`.

**Comment by froydnj** [comment]
But you can't `raise` things that don't derive from `StandardError`, so this seems like a plus?

**Comment by jez** [comment]
This is not specific to `rescue`: this is how `===` has worked (e.g. with `case` statements) since Sorbet was built:

```ruby
# typed: true

class A
  def self.===(other)
    true
  end
end

x = false
case x
when A
  T.reveal_type(x) # error: This code is unreachable
end
```

Sorbet is forced to either:

1.  Update its knowledge for all methods called `===`, assuming that they all behave like `Module#===` even if they don't.
2.  Only update knowledge for `===` if `Module#===` has not been overridden, and dispatches all the way to `Module#===`.
3.  Have some way for users to specify in their `Module#===` override whether it behaves like `Module#===` or not, which would require new, ad-hoc type syntax for this.

Sorbet chooses the first, because with the philosophical belief that it's an antipattern to change the meaning of `Module#===` like this.

The workaround for cases like this is just to lean into the weirdness, and use `T.unsafe` at the rescue:

```ruby
# typed: true

class A
  def self.===(other)
    true
  end
end

begin
  raise StandardError, "something"
rescue T.unsafe(A)
  puts "hello"
end
```

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20A%0A%20%20def%20self.%3D%3D%3D%28other%29%0A%20%20%20%20true%0A%20%20end%0Aend%0A%0Abegin%0A%20%20raise%20StandardError%2C%20%22something%22%0Arescue%20T.unsafe%28A%29%0A%20%20puts%20%22hello%22%0Aend%0A)

Unfortunately, I don't think that changing how Sorbet treats `===` is going to be something we're able to change.

**Comment by vinistock** [comment]
Thanks for the context, Jake. I agree, this is a fair tradeoff 👍.
