### ISSUE TITLE
Fails to type check upper type bounds that should type check on nested generics

### ISSUE THREAD

**Issue by rex-remind101** [sorbet/sorbet#7663]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Wrapper%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Schema%20%3D%20type_member%20%7B%20%7B%20upper%3A%20T%3A%3AHash%5BT.untyped%2C%20T.untyped%5D%20%7D%20%7D%0Aend%0A%0Aclass%20Concrete%20%3C%20Wrapper%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Schema%20%3D%20type_member%20%7B%20%7B%20fixed%3A%20%7Bfoo%3A%20Integer%2C%20bar%3A%20String%20%7D%20%7D%20%7D%0Aend%0A%0Amodule%20Thingy%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20AElem%20%3D%20type_member%20%7B%7B%20%0A%20%20%20%20upper%3A%20T%3A%3AArray%5BWrapper%5BT%3A%3AHash%5BT.untyped%2C%20T.untyped%5D%5D%5D%0A%20%20%7D%7D%0Aend%0A%0Aclass%20RealThing%0A%20%20extend%20T%3A%3AGeneric%0A%20%20include%20Thingy%0A%0A%20%20AElem%20%3D%20type_member%20%7B%7B%20%0A%20%20%20%20fixed%3A%20T%3A%3AArray%5BConcrete%5D%0A%20%20%7D%7D%0Aend%0A%0A%23%20A%20less%20complex%20example%20that%20fails.%0A%0Aclass%20Parent%3B%20end%0Aclass%20Child%20%3C%20Parent%3B%20end%0A%0Aclass%20SimpleWrapper%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Schema%20%3D%20type_member%20%7B%20%7B%20upper%3A%20Parent%20%7D%20%7D%0Aend%0A%0Aclass%20SimpleConcrete%20%3C%20SimpleWrapper%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20Schema%20%3D%20type_member%20%7B%20%7B%20fixed%3A%20Child%20%7D%20%7D%0Aend%0A%0Amodule%20SimpleThingy%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20AElem%20%3D%20type_member%20%7B%7B%20%0A%20%20%20%20upper%3A%20T%3A%3AArray%5BSimpleWrapper%5BParent%5D%5D%0A%20%20%7D%7D%0Aend%0A%0Aclass%20SimpleRealThing%0A%20%20extend%20T%3A%3AGeneric%0A%20%20include%20SimpleThingy%0A%0A%20%20AElem%20%3D%20type_member%20%7B%7B%20%0A%20%20%20%20fixed%3A%20T%3A%3AArray%5BSimpleConcrete%5D%0A%20%20%7D%7D%0Aend%0A%0A%23%20But%20an%20even%20less%20complex%20example%20that%20succeeds%3F%3F%0A%0Amodule%20SimplestThingy%0A%20%20extend%20T%3A%3AGeneric%0A%0A%20%20AElem%20%3D%20type_member%20%7B%7B%20%0A%20%20%20%20upper%3A%20T%3A%3AArray%5BParent%5D%0A%20%20%7D%7D%0Aend%0A%0Aclass%20SimplestRealThing%0A%20%20extend%20T%3A%3AGeneric%0A%20%20include%20SimplestThingy%0A%0A%20%20AElem%20%3D%20type_member%20%7B%7B%20%0A%20%20%20%20fixed%3A%20T%3A%3AArray%5BChild%5D%0A%20%20%7D%7D%0Aend%0A%0A)

```ruby
# typed: true
extend T::Sig

class Wrapper
  extend T::Generic

  Schema = type_member { { upper: T::Hash[T.untyped, T.untyped] } }
end

class Concrete < Wrapper
  extend T::Generic

  Schema = type_member { { fixed: {foo: Integer, bar: String } } }
end

module Thingy
  extend T::Generic

  AElem = type_member {{ 
    upper: T::Array[Wrapper[T::Hash[T.untyped, T.untyped]]]
  }}
end

class RealThing
  extend T::Generic
  include Thingy

  AElem = type_member {{ 
    fixed: T::Array[Concrete]
  }}
end
```

#### Observed output

```
editor.rb:29: The fixed type bound T::Array[Concrete] must be a subtype of the parent's upper type bound T::Array[Wrapper[T::Hash[T.untyped, T.untyped]]] for type_member AElem https://srb.help/5053
    29 |    fixed: T::Array[Concrete]
                   ^^^^^^^^^^^^^^^^^^
    editor.rb:19: Thingy::AElem defined in parent here
    19 |  AElem = type_member {{ 
    20 |    upper: T::Array[Wrapper[T::Hash[T.untyped, T.untyped]]]
    21 |  }}
  Autocorrect: Use -a to autocorrect
    editor.rb:29: Replace with T::Array[Wrapper[T::Hash[T.untyped, T.untyped]]]
    29 |    fixed: T::Array[Concrete]
                   ^^^^^^^^^^^^^^^^^^
```

#### Expected behavior

This type checks generic bounds since `Concrete` is a subtype of `Wrapper[T::Hash[T.untyped, T.untyped]`, proven by how there is no error in `Concrete`, only in it's usage in generic bounds later.

**Comment by jez** [comment]
This is a misunderstanding. The error has nothing to do with upperbound checking, it also reproduces with simple argument matching (i.e. all of the classes with AElem in the example above are unnecessary to demonstrate the behvaior).

The behavior is also correct, because `Schema` is invariant (not covariant, specified with `type_member(:out)` instead of `type_member`).

[Consider this example →](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Parent%3B%20end%0Aclass%20Child%20%3C%20Parent%3B%20end%0A%0Aclass%20InvariantUpperParent%0A%20%20extend%20T%3A%3AGeneric%0A%20%20X%20%3D%20type_member%20%7B%20%7B%20upper%3A%20Parent%20%7D%20%7D%0Aend%0Aclass%20InvariantFixedChild%20%3C%20InvariantUpperParent%0A%20%20extend%20T%3A%3AGeneric%0A%20%20X%20%3D%20type_member%20%7B%20%7B%20fixed%3A%20Child%20%7D%20%7D%0Aend%0Aclass%20InvariantFixedParent%20%3C%20InvariantUpperParent%0A%20%20extend%20T%3A%3AGeneric%0A%20%20X%20%3D%20type_member%20%7B%20%7B%20fixed%3A%20Parent%20%7D%20%7D%0Aend%0A%0A%0Asig%20%7B%20params%28x%3A%20InvariantUpperParent%5BParent%5D%29.void%20%7D%0Adef%20takes_invariant%28x%29%3B%20end%0A%0Asig%20%7B%20params%28x%3A%20InvariantFixedChild%29.void%20%7D%0Adef%20example1_1%28x%29%0A%20%20takes_invariant%28x%29%0Aend%0Asig%20%7B%20params%28x%3A%20InvariantFixedParent%29.void%20%7D%0Adef%20example1_2%28x%29%0A%20%20takes_invariant%28x%29%0Aend%0A%0A%23%20-------------%0A%0Aclass%20CovariantUpperParent%0A%20%20extend%20T%3A%3AGeneric%0A%20%20X%20%3D%20type_member%28%3Aout%29%20%7B%20%7B%20upper%3A%20Parent%20%7D%20%7D%0Aend%0Aclass%20CovariantFixedChild%20%3C%20CovariantUpperParent%0A%20%20extend%20T%3A%3AGeneric%0A%20%20X%20%3D%20type_member%28%3Aout%29%20%7B%20%7B%20fixed%3A%20Child%20%7D%20%7D%0Aend%0Aclass%20CovariantFixedParent%20%3C%20CovariantUpperParent%0A%20%20extend%20T%3A%3AGeneric%0A%20%20X%20%3D%20type_member%28%3Aout%29%20%7B%20%7B%20fixed%3A%20Parent%20%7D%20%7D%0Aend%0A%0A%0Asig%20%7B%20params%28x%3A%20CovariantUpperParent%5BParent%5D%29.void%20%7D%0Adef%20takes_covariant%28x%29%3B%20end%0A%0Asig%20%7B%20params%28x%3A%20CovariantFixedChild%29.void%20%7D%0Adef%20example2_1%28x%29%0A%20%20takes_covariant%28x%29%0Aend%0Asig%20%7B%20params%28x%3A%20CovariantFixedParent%29.void%20%7D%0Adef%20example2_2%28x%29%0A%20%20takes_covariant%28x%29%0Aend)

Going back to the original example in the ticket, adding `:out` to the definition of `Schema` on line 7 fixes the error.

**Comment by rex-remind101** [comment]
@jez thank you for the quick response and the work around.

I'm confused though if you don't mind explaining further. If `type_member` is invariant by default then I don't understand why this is definable at all:
```ruby
class InvariantUpperParent
  extend T::Generic
  X = type_member { { upper: Parent } }
end
class InvariantFixedChild < InvariantUpperParent
  extend T::Generic
  X = type_member { { fixed: Child } }
end
```
by virtue of using an `upper` constraint on the generic my expectation was that this would be usable in covariant positions everywhere (and contravariant positions in C^op), why else would I want to include that?
