### ISSUE TITLE
T.let gives unexpected behavior with instance variables

### ISSUE THREAD

**Issue by skatenerd** [sorbet/sorbet#7705]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7Bparams%28x%3A%20Integer%29.returns%28T%3A%3AArray%5BInteger%5D%29%7D%0A%20%20def%20lookup_for_me%28x%29%0A%20%20%20%20%40h%20%7C%7C%3D%20T.let%28%0A%20%20%20%20%20%20Hash.new%20%7B%20%5B%5D%20%7D%2C%0A%20%20%20%20%20%20T.nilable%28T%3A%3AHash%5BInteger%2C%20T%3A%3AArray%5BInteger%5D%5D%29%0A%20%20%20%20%29%0A%20%20%20%20T.reveal_type%28%40h%29%0A%20%20%20%20%5B%5D%0A%20%20end%0Aend%0A%0A)

```ruby
# typed: true
class Foo
  extend T::Sig

  sig {params(x: Integer).returns(T::Array[Integer])}
  def lookup_for_me(x)
    @h ||= T.let(
      Hash.new { [] },
      T.nilable(T::Hash[Integer, T::Array[Integer]])
    )
    T.reveal_type(@h)
    []
  end
end


```

#### Observed output

```
editor.rb:11: Revealed type: T::Hash[T.untyped, T.untyped] https://srb.help/7014
    11 |    T.reveal_type(@h)
            ^^^^^^^^^^^^^^^^^
  Got T::Hash[T.untyped, T.untyped] originating from:
    editor.rb:7:
     7 |    @h ||= T.let(
            ^^
    editor.rb:8:
     8 |      Hash.new { [] },
              ^^^^^^^^^^^^^^^
Errors: 1
```

#### Expected behavior

I would expect either:
* Some sort of warning that the type of `@h` is `T::Hash[T.Untyped, T.Untyped]`
* For the type of `@h` to be `T::Hash[Integer, T::Array[Integer]]`

With the current behavior, many people would expect that `@h` is of the type that is indicated by `T.let`.

When [I asked about this in slack](https://sorbet-ruby.slack.com/archives/CHN2L03NH/p1708021584043549?thread_ts=1707922912.177309&cid=CHN2L03NH), a maintainer explained that there will eventually be a warning, where the untyped code is highlighted.  I think that this could stand to be a warning in the output of `srb tc`, for people who don't have the editor integrations all configured.
- - -

**Comment by jez** [comment]
As I explained on Slack, this is not unique to instance variables, this is sort of just how variable assignments work. As long as the assignment to a "pinned" variable (a variable with an explicitly declared type) is compatible with the type it was pinned to, Sorbet will use the more narrow type of the variable if it is ever assigned to a second time.

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7B%20void%20%7D%0Adef%20lookup_for_me%0A%20%20x%20%3D%20T.let%280%2C%20Integer%29%0A%20%20x%20%3D%20T.unsafe%28''%29%0A%20%20T.reveal_type%28x%29%0Aend)

```ruby
# typed: true
extend T::Sig

sig { void }
def lookup_for_me
  x = T.let(0, Integer)
  x = T.unsafe('')
  T.reveal_type(x)
end
```

#### Observed output

```
editor.rb:8: Revealed type: T.untyped https://srb.help/7014
     8 |  T.reveal_type(x)
          ^^^^^^^^^^^^^^^^
  Got T.untyped originating from:
    editor.rb:7:
     7 |  x = T.unsafe('')
              ^^^^^^^^^^^^
Errors: 1
```

The issue here is simply that `T.untyped` is a subtype of all types, which is unsound but just the way that Sorbet works.

There are two separate issues you raise, which ought to be tracked separately:

1.  Reporting a "usage of untyped" warning if the usage happens nested somewhere in the type, like `T::Array[T.untyped] <: `T::Array[Integer]`, instead of at the top level, like `T.untyped <: T::Array[Integer]`.
2.  Adding a way to opt into this information in the `srb tc` output, because it is currently only available in editors.

**Comment by amanda-mitchell** [comment]
I don't understand this resolution. The assignment _explicitly_ specifies type parameters for the `T::Hash`, but those are thrown away. As a user, this makes no sense.

**Comment by amanda-mitchell** [comment]
If nothing else, this should be a clear sign that your documentation needs to be _much_ clearer about how `T.let` works.

**Comment by skatenerd** [comment]
There is some difference between instance variables and non-instance-variables here.  In [this example](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Ax%20%3D%20T.let%28%0A%20%20Hash.new%20%7B%20%5B%5D%20%7D%2C%0A%20%20T%3A%3AHash%5BInteger%2C%20Integer%5D%0A%29%0A%0AT.reveal_type%28x%29), the `T.let` is being respected when it should not be.  As opposed to the original issue, which is where `T.let` is incorrectly (appearing to a novice to be) ignored.
