### ISSUE TITLE
type_parameters error on default argument (T::Class) but not when passing the same argument in an invocation

### ISSUE THREAD

**Issue by marknuzz** [sorbet/sorbet#7780]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20frozen_string_literal%3A%20true%0A%23%20typed%3A%20true%0A%0Aclass%20P%0A%20%20extend%20T%3A%3ASig%0A%20%20class%20A%0A%20%20end%0A%0A%20%20sig%20do%0A%20%20%20%20type_parameters%28%3AT%29%0A%20%20%20%20%20%20.params%28t%3A%20T%3A%3AClass%5BT.all%28T.type_parameter%28%3AT%29%2C%20A%29%5D%29%0A%20%20%20%20%20%20.returns%28T.type_parameter%28%3AT%29%29%0A%20%20end%0A%20%20def%20foo%28t%3A%20A%29%20%23%20Why%20does%20this%20correctly-typed%20default%20value%20error%20here%3F%0A%20%20%20%20t.new%0A%20%20end%0A%0A%20%20def%20bar%0A%20%20%20%20a%20%3D%20foo%28t%3A%20A%29%20%23%20Why%20does%20this%20not%20error%20here%3F%0A%20%20end%0Aend%0A)

```ruby
# frozen_string_literal: true
# typed: true

class P
  extend T::Sig
  class A
  end

  sig do
    type_parameters(:T)
      .params(t: T::Class[T.all(T.type_parameter(:T), A)])
      .returns(T.type_parameter(:T))
  end
  def foo(t: A) # Why does this correctly-typed default value error here?
    t.new
  end

  def bar
    a = foo(t: A) # Why does this not error here?
  end
end

```

#### Observed output

```
editor.rb:14: Argument does not have asserted type T::Class[T.all(P::A, T.type_parameter(:T) (of P#foo))] https://srb.help/7007
    14 |  def foo(t: A) # Why does this correctly-typed default value error here?
                     ^
  Got T.class_of(P::A) originating from:
    editor.rb:14:
    14 |  def foo(t: A) # Why does this correctly-typed default value error here?
                     ^

editor.rb:15: Expected T.type_parameter(:T) (of P#foo) but found P::A for method result type https://srb.help/7005
    15 |    t.new
            ^^^^^
  Expected T.type_parameter(:T) (of P#foo) for result type of method foo:
    editor.rb:14:
    14 |  def foo(t: A) # Why does this correctly-typed default value error here?
          ^^^^^^^^^^^^^
  Got P::A originating from:
    editor.rb:15:
    15 |    t.new
            ^^^^^
Errors: 2
```

#### Expected behavior

Should be able to understand that the default value is the correct type. Passing the same parameter in an invocation does not error!
- - -

**Comment by jez** [comment]
This is not a bug, nor is the behavior is unique to `T::Class`: it's a feature of how all generics work. Consider this simpler example:

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters%28%3AU%29%0A%20%20%20%20.params%28x%3A%20T.type_parameter%28%3AU%29%29%0A%20%20%20%20.void%0Aend%0Adef%20example%28x%20%3D%200%29%0Aend%0A)

```ruby
# typed: true
extend T::Sig

sig do
  type_parameters(:U)
    .params(x: T.type_parameter(:U))
    .void
end
def example(x = 0)
end

```

#### Observed output

```
editor.rb:9: Argument does not have asserted type T.type_parameter(:U) (of Object#example) https://srb.help/7007
     9 |def example(x = 0)
                        ^
  Got Integer(0) originating from:
    editor.rb:9:
     9 |def example(x = 0)
                        ^
Errors: 1
```

This is also how both TypeScript ([example](https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcA8AVAfACgB4BciGiAvIgAwCUiA3gFCJOIQIDOcANgKYB0ncAOb4qAbnoBfIA)) and Mypy ([example](https://mypy-play.net/?mypy=latest&python=3.12&gist=a12b61e7932a71f366d19e17f3be2238)) handle this example.

The underlying reason for why type systems choose this behavior has to do with a property of type systems called [Parametricity](https://blog.jez.io/sorbet-parametricity/).

- - - - -

The reason why the lines you link in the standard library RBIs work is twofold:

- Method bodies are not typechecked in RBIs. The error is present there, but errors are silenced in those files.
- That definition doesn't actually care about the specific default value: it only cares that there _is_ a default value for `super_class`, because that definition has an [overloaded signature](https://sorbet.org/docs/overloads).

Overloaded signatures are discouraged outside of the standard library. It's almost always a better choice to make two methods, with different names, where one has one signature and one has another signature ([example](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aextend%20T%3A%3ASig%0Aclass%20A%0Aend%0A%0Asig%20do%0A%20%20type_parameters%28%3AT%29%0A%20%20%20%20.params%28t%3A%20T%3A%3AClass%5BT.all%28T.type_parameter%28%3AT%29%2C%20A%29%5D%29%0A%20%20%20%20.returns%28T.type_parameter%28%3AT%29%29%0Aend%0Adef%20foo1%28t%29%0A%20%20t.new%0Aend%0A%0Asig%20do%0A%20%20returns%28A%29%0Aend%0Adef%20foo2%0A%20%20A.new%0Aend%0A)).

If you cannot change the method you're attempting to write a signature for, there are instructions and warnings [in the docs](https://sorbet.org/docs/overloads) for overloaded signatures.
