### ISSUE TITLE
Hash#slice sig is incorrect

### ISSUE THREAD

**Issue by toregeschliman** [sorbet/sorbet#7821]
#### Input

[→ View on sorbet.run](https://sorbet.run/#x%20%3D%20T.let%28%7B%7D%2C%20T%3A%3AHash%5BSymbol%2C%20Integer%5D%29%0A%0Ax%5B%3Aa%5D%20%3D%201%0A%0Ax.slice%28%3Aa%29%20%23%20%3D%3E%20%7Ba%3A%201%7D%0Ax.slice%28nil%29%20%23%20%3D%3E%20%7B%7D)

```ruby
x = T.let({}, T::Hash[Symbol, Integer])

x[:a] = 1

x.slice(:a) # => {a: 1}
x.slice(nil) # => {}
```

#### Observed output

```
editor.rb:6: Expected Symbol but found NilClass for argument arg0 https://srb.help/7002
     6 |x.slice(nil) # => {}
                ^^^
  Expected Symbol for argument arg0 of method Hash#slice:
    https://github.com/sorbet/sorbet/tree/master/rbi/core/hash.rbi#L1148:
    1148 |        arg0: K,
                  ^^^^
  Got NilClass originating from:
    editor.rb:6:
     6 |x.slice(nil) # => {}
                ^^^
Errors: 1
```

#### Expected behavior

`x.slice(nil)` should not raise a type error, as it is both valid Ruby and _does_ return a `T::Hash[Symbol, Integer]` that happens to be empty.

**Comment by jez** [comment]
This is intentional. As far as this arguments goes:

> as is both valid Ruby and does return a `T::Hash[Symbol, Integer]`

the same argument could be used to say that we should allow

```ruby
x = T.let({a: 1}, T::Hash[Symbol, Integer])

x.slice('a') # => {}
```

All the arguments to `Hash#slice` are meant to be keys of `x`. If the type of one of the arguments is not `Symbol`, then it cannot be in `x` and likely indicates a logic error even though technically the method will not raise a `TypeError` when run.

This is intentional and is how basically all `Hash` functions work, including `slice` but also `[]`, `fetch`, etc.:

```ruby
x = T.let({a: 1}, T::Hash[Symbol, Integer])
x['a'] # error
x[nil] # error
```

The workaround is to either:

1. Explicitly handle `nil`, removing them from the arguments passed to `slice` before the call.
2. Explicitly widen the type to `T::Hash[T.nilable(Symbol), Integer]` (this is not as good as (1) because then the resulting hash will have type `T::Hash[T.nilable(Symbol), Integer]` instead of `T::Hash[Symbol, Integer]`.
3. Use `T.unsafe` to opt out of the type system checks for this particular call.
4. Define a separate, typed helper method with the semantics you'd prefer.

**Comment by toregeschliman** [comment]
Would you be open to allowing `T.nilable(K)` as the argument instead for some of these methods, like `slice`, `[]`, and `key?`? I can see the argument that cross-class inputs can be considered a risk of logic error, but `nil` is used as a special case in so many methods (including the signature for `Hash#[]`, which returns `T.nilable(V)`). While you could just ask users to make their keys nilable themselves, that can create wrong expectations for methods like `each_key` and `[]=`; I want the guarantee `nil` is never a key in my hash, while at the same time wanting to be able to handle things like chained lookups without littering the code with low-value manual nil-checking. (bad example, but e.g. `state_to_country[zip_to_state[zip]]`)

If that's already been discussed and rejected, we have already worked around it in code, I just found it to be a pretty surprising breaking change (though the new return sig did catch a couple of errors, so it still probably netted positive).
