### ISSUE TITLE
Unexpected return type mismatch for overridden method

### ISSUE THREAD

**Issue by andyw8** [sorbet/sorbet#7921]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0A%0Aclass%20Foo%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20returns%28T.attached_class%29%20%7D%0A%20%20def%20self.make%0A%20%20%20%20new%0A%20%20end%0Aend%0A%0Aclass%20Bar%20%3C%20Foo%0A%20%20sig%20%7B%20override.returns%28Bar%29%20%7D%0A%20%20def%20self.make%0A%20%20%20%20new%0A%20%20end%0Aend%0A%0Aclass%20Baz%20%3C%20Bar%0A%20%20sig%20%7B%20override.returns%28Baz%29%20%7D%0A%20%20def%20self.make%0A%20%20%20%20new%0A%20%20end%0Aend)

```ruby
# typed: true

class Foo
  extend T::Sig

  sig { returns(T.attached_class) }
  def self.make
    new
  end
end

class Bar < Foo
  sig { override.returns(Bar) }
  def self.make
    new
  end
end

class Baz < Bar
  sig { override.returns(Baz) }
  def self.make
    new
  end
end
```

#### Observed output

```
editor.rb:14: Return type Bar does not match return type of overridden method Foo.make https://srb.help/5035
    14 |  def self.make
          ^^^^^^^^^^^^^
    editor.rb:7: Super method defined here with return type T.attached_class (of Foo)
     7 |  def self.make
          ^^^^^^^^^^^^^
  Note:
    A method's return type must be a subtype of the return type on the super method.
Errors: 1
```

#### Expected behavior

We would have expected this to pass the typecheck.

cc @Morriar

**Comment by jez** [comment]
Sorbet is correct here.

[This sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Aclass%20Parent%0A%20%20extend%20T%3A%3ASig%0A%0A%20%20sig%20%7B%20returns%28T.attached_class%29%20%7D%0A%20%20def%20self.make%0A%20%20%20%20new%0A%20%20end%0Aend%0A%0Aclass%20Child%20%3C%20Parent%0A%20%20sig%20%7B%20override.returns%28Child%29%20%7D%0A%20%20def%20self.make%0A%20%20%20%20new%0A%20%20end%0Aend%0A%0Aclass%20GrandChild%20%3C%20Child%0A%20%20%23%20This%20override%20is%20compatible%20with%20the%20immediate%20parent%0A%20%20sig%20%7B%20override.returns%28Child%29%20%7D%0A%20%20def%20self.make%0A%20%20%20%20%23%20%60Child.new%60%20is%20a%20value%20of%20type%20%60Child%60%0A%20%20%20%20Child.new%0A%20%20end%0A%0A%20%20def%20only_on_grandchild%0A%20%20end%0Aend%0A%0Asig%20do%0A%20%20type_parameters%28%3AInstance%29%0A%20%20%20%20.params%28klass%3A%20T.class_of%28Parent%29%5BT.all%28T.type_parameter%28%3AInstance%29%2C%20Parent%29%5D%29%0A%20%20%20%20.returns%28T.type_parameter%28%3AInstance%29%29%0Aend%0Adef%20example%28klass%29%0A%20%20klass.make%0Aend%0A%0Ainst%20%3D%20example%28GrandChild%29%0A%0AT.reveal_type%28inst%29%20%23%20%F0%9F%92%A5%20GrandChild%20is%20wrong!%20It's%20only%20Child%20at%20runtime!%0Ap%28inst%29%20%23%20%3D%3E%20%23%3CChild%3A0x00000001051a6c00%3E%0Ainst.only_on_grandchild%20%23%20%F0%9F%92%A5%20NoMethodError%0A) shows a counter example.

The idea is that the type `T.attached_class` is _more_ restrictive/narrow than the type `Child`, even when a class's attached class would otherwise be upper bounded by `Child`.

**Comment by andyw8** [comment]
Thank you for the explanation!
