### ISSUE TITLE
Methods named `before` and `after` ignore bind types from signatures 

### ISSUE THREAD

**Issue by olivier-thatch** [sorbet/sorbet#7950]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Aclass%20Context%3B%20end%0A%0Amodule%20DSL%0A%20%20module%20ClassMethods%0A%20%20%20%20extend%20T%3A%3ASig%0A%0A%20%20%20%20sig%20%7B%20params%28block%3A%20T.proc.bind%28Context%29.void%29.void%20%7D%0A%20%20%20%20def%20before%28%26block%29%3B%20end%0A%0A%20%20%20%20sig%20%7B%20params%28block%3A%20T.proc.bind%28Context%29.void%29.void%20%7D%0A%20%20%20%20def%20before_validation%28%26block%29%3B%20end%0A%0A%20%20%20%20sig%20%7B%20params%28block%3A%20T.proc.bind%28Context%29.void%29.void%20%7D%0A%20%20%20%20def%20after%28%26block%29%3B%20end%0A%0A%20%20%20%20sig%20%7B%20params%28block%3A%20T.proc.bind%28Context%29.void%29.void%20%7D%0A%20%20%20%20def%20after_validation%28%26block%29%3B%20end%0A%20%20end%0Aend%0A%0Aclass%20Foo%0A%20%20extend%20DSL%3A%3AClassMethods%0Aend%0A%0Aclass%20Test%20%3C%20Foo%0A%20%20before%20do%0A%20%20%20%20T.reveal_type%28self%29%0A%20%20end%0A%0A%20%20before_validation%20do%0A%20%20%20%20T.reveal_type%28self%29%0A%20%20end%0A%0A%20%20after%20do%0A%20%20%20%20T.reveal_type%28self%29%0A%20%20end%0A%0A%20%20after_validation%20do%0A%20%20%20%20T.reveal_type%28self%29%0A%20%20end%0Aend%0A)

```ruby
# typed: strict
extend T::Sig

class Context; end

module DSL
  module ClassMethods
    extend T::Sig

    sig { params(block: T.proc.bind(Context).void).void }
    def before(&block); end

    sig { params(block: T.proc.bind(Context).void).void }
    def before_validation(&block); end

    sig { params(block: T.proc.bind(Context).void).void }
    def after(&block); end

    sig { params(block: T.proc.bind(Context).void).void }
    def after_validation(&block); end
  end
end

class Foo
  extend DSL::ClassMethods
end

class Test < Foo
  before do
    T.reveal_type(self)
  end

  before_validation do
    T.reveal_type(self)
  end

  after do
    T.reveal_type(self)
  end

  after_validation do
    T.reveal_type(self)
  end
end
```

#### Observed output

```
editor.rb:30: Revealed type: Test https://srb.help/7014
    30 |    T.reveal_type(self)
            ^^^^^^^^^^^^^^^^^^^

editor.rb:38: Revealed type: Test https://srb.help/7014
    38 |    T.reveal_type(self)
            ^^^^^^^^^^^^^^^^^^^

editor.rb:34: Revealed type: Context https://srb.help/7014
    34 |    T.reveal_type(self)
            ^^^^^^^^^^^^^^^^^^^
  Got Context originating from:
    editor.rb:13:
    13 |    sig { params(block: T.proc.bind(Context).void).void }
                         ^^^^^

editor.rb:42: Revealed type: Context https://srb.help/7014
    42 |    T.reveal_type(self)
            ^^^^^^^^^^^^^^^^^^^
  Got Context originating from:
    editor.rb:19:
    19 |    sig { params(block: T.proc.bind(Context).void).void }
                         ^^^^^
Errors: 4
```

#### Expected behavior

The revealed type should be `Context` in all cases.

- - -

I asked about this on Slack and @dmitry-stripe provided the following information:

> Caveat, I’m not on the Sorbet team anymore but:
> * it was intended at the time
> * it is implemented as[ syntactic rewrite](https://github.com/sorbet/sorbet/blob/d236f70abe9bf34d176dac44ac2c9c6f510bac82/rewriter/Minitest.cc)
> * it’s invoked [unconiditionally](https://github.com/sorbet/sorbet/blame/d236f70abe9bf34d176dac44ac2c9c6f510bac82/rewriter/rewriter.cc#L99) in phase that among other things implements attr_reader/attr_writer
> So the answer afaik is it’s expected and can’t be overriden

For context, I ran into this issue while writing a [Tapioca compiler](https://github.com/thatch-health/grape_sorbet?tab=readme-ov-file) for the [grape](https://github.com/ruby-grape/grape) gem, which exposes [callback methods](https://github.com/ruby-grape/grape?tab=readme-ov-file#before-after-and-finally) named `before` and `after` that accept a block that is executed in a different context.

As a workaround, using `T.bind(self, Context)` directly inside the block works, but the point of the Tapioca compiler is precisely to avoid having to do that.

**Comment by jez** [comment]
This is pretty load bearing for us, we want to allow people to define instance variables in minitest before blocks, but Sorbet only allows declaring them inside instance methods. So we can't just "delete all the before/after handling from Sorbet and replace it with two T.proc.bind annotations"

I know this because I tried it after Sorbet grew support for `T.proc.bind(T.attached_class)`:

https://github.com/sorbet/sorbet/pull/5759

- - - - -

The solution I prefer, which is annoying, yes, is to use `this = self`

https://sorbet.run/#%23%20typed%3A%20strict%0Aextend%20T%3A%3ASig%0A%0Aclass%20Context%3B%20end%0A%0Amodule%20DSL%0A%20%20module%20ClassMethods%0A%20%20%20%20extend%20T%3A%3ASig%0A%0A%20%20%20%20sig%20%7B%20params%28block%3A%20T.proc.bind%28Context%29.void%29.void%20%7D%0A%20%20%20%20def%20before%28%26block%29%3B%20end%0A%0A%20%20%20%20sig%20%7B%20params%28block%3A%20T.proc.bind%28Context%29.void%29.void%20%7D%0A%20%20%20%20def%20before_validation%28%26block%29%3B%20end%0A%0A%20%20%20%20sig%20%7B%20params%28block%3A%20T.proc.bind%28Context%29.void%29.void%20%7D%0A%20%20%20%20def%20after%28%26block%29%3B%20end%0A%0A%20%20%20%20sig%20%7B%20params%28block%3A%20T.proc.bind%28Context%29.void%29.void%20%7D%0A%20%20%20%20def%20after_validation%28%26block%29%3B%20end%0A%20%20end%0Aend%0A%0Aclass%20Foo%0A%20%20extend%20DSL%3A%3AClassMethods%0Aend%0A%0Aclass%20Test%20%3C%20Foo%0A%20%20this%20%3D%20self%0A%0A%20%20this.before%20do%0A%20%20%20%20T.reveal_type%28self%29%0A%20%20end%0A%0A%20%20before_validation%20do%0A%20%20%20%20T.reveal_type%28self%29%0A%20%20end%0A%0A%20%20this.after%20do%0A%20%20%20%20T.reveal_type%28self%29%0A%20%20end%0A%0A%20%20after_validation%20do%0A%20%20%20%20T.reveal_type%28self%29%0A%20%20end%0Aend%0A

```ruby
this = self
this.before { ... }
```

The only time this doesn't work is if `before` is a private method, because now there is an explicit receiver.

Otherwise, this is unlikely to change in the future, so I'm going to go ahead and close the ticket. Hope that helps.
