### ISSUE TITLE
Generics fails to detect nilable block types correctly in some cases

### ISSUE THREAD

**Issue by Tabby** [sorbet/sorbet#7965]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters%28%3AU%29.%0A%20%20%20%20params%28%0A%20%20%20%20%20%20block%3A%20T.proc.%0A%20%20%20%20%20%20%20%20params%28value%3A%20T.type_parameter%28%3AU%29%29.%0A%20%20%20%20%20%20%20%20returns%28T.type_parameter%28%3AU%29%29%2C%0A%20%20%20%20%29.%0A%20%20%20%20void%0Aend%0Adef%20foo%28%26block%29%3B%20end%0A%0A%23%20value%20should%20be%20T.nilable%28String%29%20but%20is%20T.noreturn%0Afoo%20do%20%7Cvalue%7C%0A%20%20%22bar%22%20if%20value.present%3F%0Aend)

```ruby
# typed: true
extend T::Sig

sig do
  type_parameters(:U).
    params(
      block: T.proc.
        params(value: T.type_parameter(:U)).
        returns(T.type_parameter(:U)),
    ).
    void
end
def foo(&block); end

# value should be T.nilable(String) but is T.noreturn
foo do |value|
  "bar" if value.present?
end
```

#### Observed output

```
editor.rb:19: This code is unreachable https://srb.help/7006
    19 |  "bar" if value.present?
                   ^^^^^^^^^^^^^^
    editor.rb:18: This expression always raises or can never be computed
    18 |foo do |value|
                ^^^^^
Errors: 1
```

#### Expected behavior

The detected type parameter ought to be `T.nilable(String)` as the only two possible return values are a string or `nil`

- - -

I realise this is perhaps a somewhat awkward example, but it seems like an error that the return types are not used to set the type parameter if it can't be determined from the input parameter

**Comment by Tabby** [comment]
The context is that this is a signature for a function that is added to ActiveRecord models, as part of an anonymisation gem, for defining a custom behaviour to use on one or more fields.

What I'm trying to do essentially is write a signature for a generic function that takes a list of field names (as `Symbol`s) and a block that takes as its parameter the current value of the field and returns a modified value to write back to the field, so the types of the parameter and the return of the block depend on the field in question.

A slightly longer example of how it would be used would be something like this:

```ruby
class Employee < ActiveRecord::Base do
  include Anony::Anonymisable

  anonymise do
    overwrite do
      with_strategy(:company_name, :first_name, :last_name) do |value|
       # Do something with value and return an anonymised value of the same type to overwrite the column with
       value.reverse
      end
    end
  end
end
```

Where `with_strategy` is the equivalent of `foo` in the minimal example, and it simply stores the block in a hash using the field name as a key

I accept that I may be expecting too much from Sorbet here, and/or that it doesn't work in a way that could allow this which would mean this is not a bug. I assumed it would work because other type systems I've used would use the return value to deduce the parameter value if it had nothing else to go on, but it seems puzzling to me that it's decided the parameter has to be `T.noreturn` instead of at least `T.untyped` or `T.nilable(BasicObject)` or something very generic like that

I did also try telling Sorbet that the parameter is a string on the basis that it's a pretty unreasonable thing to ask it to figure out, like this (going back to the minimal example):
```ruby
foo do |value|
  T.let(value, String)
  "bar"
end
```

But Sorbet just goes "no you're wrong, that's a `T.noreturn`" so I'm not really sure what the right way to achieve this is

I have tried setting a bound as well, using `T.all(T.type_parameter(:U), T.nilable(Object))` but I guess `T.noreturn` is a subclass of `Object` too, so it still settles on that

Actually, I wonder if it would work to have a `T.any` with all the possible types that a model field can be and use that with the generic type... (as in `T.all(T.type_parameter(:U), T.any(String, Integer, T::Boolean, ...etc))` or something)

**Comment by Tabby** [comment]
All of which is to say, if this isn't a bug, it isn't a bug and at some point I'll figure out how to do this with a DSL compiler which would hopefully have more context, instead of making horrible shims 😅 

It just wasn't the behaviour I would have expected _at all_, so seemed like it might be a bug

**Comment by jez** [comment]
Going back to the example in the issue description, the unreachable code error you're seeing is actually correct given the signature for `foo`:

#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20do%0A%20%20type_parameters%28%3AU%29.%0A%20%20%20%20params%28%0A%20%20%20%20%20%20block%3A%20T.proc.%0A%20%20%20%20%20%20%20%20params%28value%3A%20T.type_parameter%28%3AU%29%29.%0A%20%20%20%20%20%20%20%20returns%28T.type_parameter%28%3AU%29%29%2C%0A%20%20%20%20%29.%0A%20%20%20%20void%0Aend%0Adef%20foo%28%26block%29%0A%20%20yield%0A%20%20yield%20nil%0A%20%20yield%200%0Aend%0A%0A%23%20value%20should%20be%20T.nilable%28String%29%20but%20is%20T.noreturn%0Afoo%20do%20%7Cvalue%7C%0A%20%20%22bar%22%20if%20value.present%3F%0Aend)

```ruby
# typed: true
extend T::Sig

sig do
  type_parameters(:U).
    params(
      block: T.proc.
        params(value: T.type_parameter(:U)).
        returns(T.type_parameter(:U)),
    ).
    void
end
def foo(&block)
  yield
  yield nil
  yield 0
end

# value should be T.nilable(String) but is T.noreturn
foo do |value|
  "bar" if value.present?
end
```

#### Observed output

```
editor.rb:14: Not enough arguments provided for method Proc1#call. Expected: 1, got: 0 https://srb.help/7004
    14 |  yield
          ^^^^^
    https://github.com/sorbet/sorbet/tree/master/rbi/procs.rbi#L26: Proc1#call defined here
    26 |  def call(arg0); end
          ^^^^^^^^^^^^^^

editor.rb:15: Expected T.type_parameter(:U) (of Object#foo) but found NilClass for argument arg0 https://srb.help/7002
    15 |  yield nil
                ^^^
  Expected T.type_parameter(:U) (of Object#foo) for argument arg0 of method Proc1#call:
    https://github.com/sorbet/sorbet/tree/master/rbi/procs.rbi#L22:
    22 |      arg0: Arg0,
              ^^^^
  Got NilClass originating from:
    editor.rb:15:
    15 |  yield nil
                ^^^

editor.rb:16: Expected T.type_parameter(:U) (of Object#foo) but found Integer(0) for argument arg0 https://srb.help/7002
    16 |  yield 0
                ^
  Expected T.type_parameter(:U) (of Object#foo) for argument arg0 of method Proc1#call:
    https://github.com/sorbet/sorbet/tree/master/rbi/procs.rbi#L22:
    22 |      arg0: Arg0,
              ^^^^
  Got Integer(0) originating from:
    editor.rb:16:
    16 |  yield 0
                ^

editor.rb:21: This code is unreachable https://srb.help/7006
    21 |  "bar" if value.present?
                   ^^^^^^^^^^^^^^
    editor.rb:20: This expression always raises or can never be computed
    20 |foo do |value|
                ^^^^^
Errors: 4
```

All attempts to call this block are impossible—the signature says that this block must be given one argument, but it's not possible to produce a value of type `T.type_parameter(:U)` within the body of `foo`, because no such value has been given.

> I assumed it would work because other type systems I've used would use the return value to deduce the parameter value if it had nothing else to go on

I would be curious to see an example in another typed language that behaves the way you describe—I'm not aware of any. For example, here's a [comparable TypeScript example](https://www.typescriptlang.org/play/?#code/PTAEHUFMBsGMHsC2lQBd5oBYoCoE8AHSAZVgCcBLA1UABWgEM8BzM+AVwDsATAGiwoBnUENANQAd0gAjQRVSQAUCEmYKsTKGYUAbpGF4OY0BoadYKdJMoL+gzAzIoz3UNEiPOofEVKVqAHSKymAAmkYI7NCuqGqcANag8ABmIjQUXrFOKBJMggBcISGgoAC0oACCbvCwDKgU8JkY7p7ehCTkVDQS2E6gnPCxGcwmZqDSTgzxxWWVoASMFmgYkAAeRJTInN3ymj4d-jSCeNsMq-wuoPaOltigAKoASgAywhK7SbGQZIIz5VWCFzSeCrZagNYbChbHaxUDcCjJZLfSDbExIAgUdxkUBIursJzCFJtXydajBZJcWD1Ro4+DwAA8OAAfAAKZL5UAslmrDk4ACUoAAvEzvHyBQBvRQlErJFl8gDcUulss4UWgCqVMpZAAYNQBfcl0rmrAXC0CS6WgJyofFeVYBJx6H6QRV6vlAA) which behaves almost exactly like Sorbet, with the exception that it allows the call site to go through, instead of complaining that it's not actually possible for any of the code in the method body to be called.

> I did also try telling Sorbet that the parameter is a string [...] But Sorbet just goes "no you're wrong, that's a T.noreturn" so I'm not really sure what the right way to achieve this is

To use this strategy, you'll need to change the signature so that Sorbet thinks it's possible to call the method. That would mean either declaring the block's `value` argument as either `T.anything` or `T.untyped` or something else (like `T.any(String, Integer, T::Boolean, etc., ...)`).

> A slightly longer example of how it would be used would be something like this: [...] Where with_strategy is the equivalent of foo in the minimal example, and it simply stores the block in a hash using the field name as a key

Generics are not a solution to this problem. Generics are used when the function works _for all_ choices of `T.type_parameter(:U)`. In your case, you want a function which works for some choices of `T.type_parameter(:U)`, and the choice of _which one_ is not knowable from the parameters given to the function.

Unless you're willing to change the API of `with_strategy` (which it seems you're unwilling to do, because it comes from a gem outside of your control), you'll have to settle for the fact that writing a super-precise type for this method's block parameter is not possible.

**Comment by Tabby** [comment]
Thanks very much both of you, that's super helpful (and I'll definitely join the slack community too) :)
