### ISSUE TITLE
False unreachable code with multiple assignment

### ISSUE THREAD

**Issue by azdavis** [sorbet/sorbet#981]
#### Input

[→ View on sorbet.run](https://sorbet.run/#%23%20typed%3A%20true%0Aextend%20T%3A%3ASig%0A%0Asig%20%7Breturns(T.nilable(T%3A%3AArray%5BInteger%5D))%7D%0Adef%20foo%0A%20%20nil%0Aend%0A%0Aif%20(a%2C%20b%20%3D%20foo)%0A%20%20puts%201%0Aelse%0A%20%20puts%202%0Aend%0A)

```ruby
# typed: true
extend T::Sig

sig {returns(T.nilable(T::Array[Integer]))}
def foo
  nil
end

if (a, b = foo)
  puts 1
else
  puts 2
end
```

#### Observed output

```
editor.rb:12: This code is unreachable https://srb.help/7006
    12 |  puts 2
               ^
Errors: 1
```

But running with ruby outputs 2.

#### Expected behavior

No errors.

**Comment by XrXr** [comment]
It looks like Magic.expand-splat always returns an array. Since array is always truthy it tricks the dead code detector. excerpt from cfg: 

(
![Screen Shot 2019-06-21 at 2 24 07 PM](https://user-images.githubusercontent.com/6457510/59943716-e9997480-9430-11e9-8594-55431d1c13cf.png)
Using a nilable int here but same thing.)
